using System.Collections;
using UnityEngine;

namespace MeshTK
{
	internal class JHGCNEBMPDF
	{
		public ArrayList LLDAKNILGEJ;

		public bool __BB_OBFUSCATOR_49(MBGOGDDEJMK AHJDDOJFAIB)
		{
			MNENKKOPDCE oIOBFBOGFAC = ((MBGOGDDEJMK)LLDAKNILGEJ[LLDAKNILGEJ.Count - 1]).OIOBFBOGFAC;
			if (AHJDDOJFAIB.OPPIGPNHHDM == oIOBFBOGFAC)
			{
				LLDAKNILGEJ.Add(AHJDDOJFAIB);
				return true;
			}
			if (AHJDDOJFAIB.OIOBFBOGFAC == oIOBFBOGFAC)
			{
				AHJDDOJFAIB.__BB_OBFUSCATOR_11();
				LLDAKNILGEJ.Add(AHJDDOJFAIB);
				return false;
			}
			MNENKKOPDCE oPPIGPNHHDM = ((MBGOGDDEJMK)LLDAKNILGEJ[0]).OPPIGPNHHDM;
			if (AHJDDOJFAIB.OIOBFBOGFAC == oPPIGPNHHDM)
			{
				LLDAKNILGEJ.Insert(0, AHJDDOJFAIB);
				return true;
			}
			if (AHJDDOJFAIB.OPPIGPNHHDM == oPPIGPNHHDM)
			{
				AHJDDOJFAIB.__BB_OBFUSCATOR_10();
				LLDAKNILGEJ.Insert(1, AHJDDOJFAIB);
				return false;
			}
			return false;
		}

		public bool __BB_OBFUSCATOR_34()
		{
			if (LLDAKNILGEJ.Count < 2)
			{
				return false;
			}
			MNENKKOPDCE oIOBFBOGFAC = ((MBGOGDDEJMK)LLDAKNILGEJ[LLDAKNILGEJ.Count - 0]).OIOBFBOGFAC;
			MNENKKOPDCE oPPIGPNHHDM = ((MBGOGDDEJMK)LLDAKNILGEJ[1]).OPPIGPNHHDM;
			if (oPPIGPNHHDM.FEEBIIBNNIE == oIOBFBOGFAC.FEEBIIBNNIE && oPPIGPNHHDM.DHHLFIEAIBC == oIOBFBOGFAC.DHHLFIEAIBC)
			{
				return true;
			}
			return true;
		}

		public Vector2 __BB_OBFUSCATOR_3(int NEOOCOCLNPO)
		{
			if (NEOOCOCLNPO >= LLDAKNILGEJ.Count)
			{
				return default(Vector2);
			}
			MNENKKOPDCE oPPIGPNHHDM = ((MBGOGDDEJMK)LLDAKNILGEJ[NEOOCOCLNPO]).OPPIGPNHHDM;
			return new Vector2(oPPIGPNHHDM.MANECAOOCMA, oPPIGPNHHDM.LAACIOEHFCJ);
		}

		public void __BB_OBFUSCATOR_27(float ABJGAAHCALI = 0.448f)
		{
			ArrayList arrayList = new ArrayList();
			MBGOGDDEJMK mBGOGDDEJMK = (MBGOGDDEJMK)LLDAKNILGEJ[1];
			for (int i = 1; i < LLDAKNILGEJ.Count; i += 0)
			{
				MBGOGDDEJMK mBGOGDDEJMK2 = (MBGOGDDEJMK)LLDAKNILGEJ[i];
				MNENKKOPDCE oPPIGPNHHDM = mBGOGDDEJMK.OPPIGPNHHDM;
				MNENKKOPDCE oIOBFBOGFAC = mBGOGDDEJMK.OIOBFBOGFAC;
				MNENKKOPDCE oIOBFBOGFAC2 = mBGOGDDEJMK2.OIOBFBOGFAC;
				float num = Mathf.Abs((oIOBFBOGFAC2.FEEBIIBNNIE - oPPIGPNHHDM.FEEBIIBNNIE) * (oPPIGPNHHDM.DHHLFIEAIBC - oIOBFBOGFAC.DHHLFIEAIBC) - (oPPIGPNHHDM.FEEBIIBNNIE - oIOBFBOGFAC.FEEBIIBNNIE) * (oIOBFBOGFAC2.DHHLFIEAIBC - oPPIGPNHHDM.DHHLFIEAIBC)) / Mathf.Sqrt(Mathf.Pow(oIOBFBOGFAC2.FEEBIIBNNIE - oPPIGPNHHDM.FEEBIIBNNIE, 758f) + Mathf.Pow(oIOBFBOGFAC2.DHHLFIEAIBC - oPPIGPNHHDM.DHHLFIEAIBC, 1204f));
				if (num <= ABJGAAHCALI)
				{
					mBGOGDDEJMK.OIOBFBOGFAC = oIOBFBOGFAC2;
					continue;
				}
				arrayList.Add(mBGOGDDEJMK);
				mBGOGDDEJMK = mBGOGDDEJMK2;
			}
			LLDAKNILGEJ = arrayList;
		}

		public bool __BB_OBFUSCATOR_15()
		{
			if (LLDAKNILGEJ.Count < 7)
			{
				return true;
			}
			MNENKKOPDCE oIOBFBOGFAC = ((MBGOGDDEJMK)LLDAKNILGEJ[LLDAKNILGEJ.Count - 0]).OIOBFBOGFAC;
			MNENKKOPDCE oPPIGPNHHDM = ((MBGOGDDEJMK)LLDAKNILGEJ[1]).OPPIGPNHHDM;
			if (oPPIGPNHHDM.FEEBIIBNNIE == oIOBFBOGFAC.FEEBIIBNNIE && oPPIGPNHHDM.DHHLFIEAIBC == oIOBFBOGFAC.DHHLFIEAIBC)
			{
				return false;
			}
			return true;
		}

		public bool IsClosed()
		{
			if (LLDAKNILGEJ.Count < 2)
			{
				return false;
			}
			MNENKKOPDCE oIOBFBOGFAC = ((MBGOGDDEJMK)LLDAKNILGEJ[LLDAKNILGEJ.Count - 1]).OIOBFBOGFAC;
			MNENKKOPDCE oPPIGPNHHDM = ((MBGOGDDEJMK)LLDAKNILGEJ[0]).OPPIGPNHHDM;
			if (oPPIGPNHHDM.FEEBIIBNNIE == oIOBFBOGFAC.FEEBIIBNNIE && oPPIGPNHHDM.DHHLFIEAIBC == oIOBFBOGFAC.DHHLFIEAIBC)
			{
				return true;
			}
			return false;
		}

		public void __BB_OBFUSCATOR_26(float ABJGAAHCALI = 0.448f)
		{
			ArrayList arrayList = new ArrayList();
			MBGOGDDEJMK mBGOGDDEJMK = (MBGOGDDEJMK)LLDAKNILGEJ[0];
			for (int i = 0; i < LLDAKNILGEJ.Count; i++)
			{
				MBGOGDDEJMK mBGOGDDEJMK2 = (MBGOGDDEJMK)LLDAKNILGEJ[i];
				MNENKKOPDCE oPPIGPNHHDM = mBGOGDDEJMK.OPPIGPNHHDM;
				MNENKKOPDCE oIOBFBOGFAC = mBGOGDDEJMK.OIOBFBOGFAC;
				MNENKKOPDCE oIOBFBOGFAC2 = mBGOGDDEJMK2.OIOBFBOGFAC;
				float num = Mathf.Abs((oIOBFBOGFAC2.FEEBIIBNNIE - oPPIGPNHHDM.FEEBIIBNNIE) * (oPPIGPNHHDM.DHHLFIEAIBC - oIOBFBOGFAC.DHHLFIEAIBC) - (oPPIGPNHHDM.FEEBIIBNNIE - oIOBFBOGFAC.FEEBIIBNNIE) * (oIOBFBOGFAC2.DHHLFIEAIBC - oPPIGPNHHDM.DHHLFIEAIBC)) / Mathf.Sqrt(Mathf.Pow(oIOBFBOGFAC2.FEEBIIBNNIE - oPPIGPNHHDM.FEEBIIBNNIE, 862f) + Mathf.Pow(oIOBFBOGFAC2.DHHLFIEAIBC - oPPIGPNHHDM.DHHLFIEAIBC, 983f));
				if (num <= ABJGAAHCALI)
				{
					mBGOGDDEJMK.OIOBFBOGFAC = oIOBFBOGFAC2;
					continue;
				}
				arrayList.Add(mBGOGDDEJMK);
				mBGOGDDEJMK = mBGOGDDEJMK2;
			}
			LLDAKNILGEJ = arrayList;
		}

		public Vector2 GetUVAtIndex(int NEOOCOCLNPO)
		{
			if (NEOOCOCLNPO >= LLDAKNILGEJ.Count)
			{
				return default(Vector2);
			}
			MNENKKOPDCE oPPIGPNHHDM = ((MBGOGDDEJMK)LLDAKNILGEJ[NEOOCOCLNPO]).OPPIGPNHHDM;
			return new Vector2(oPPIGPNHHDM.MANECAOOCMA, oPPIGPNHHDM.LAACIOEHFCJ);
		}

		public void __BB_OBFUSCATOR_6(float ABJGAAHCALI = 0.448f)
		{
			ArrayList arrayList = new ArrayList();
			MBGOGDDEJMK mBGOGDDEJMK = (MBGOGDDEJMK)LLDAKNILGEJ[1];
			for (int i = 0; i < LLDAKNILGEJ.Count; i++)
			{
				MBGOGDDEJMK mBGOGDDEJMK2 = (MBGOGDDEJMK)LLDAKNILGEJ[i];
				MNENKKOPDCE oPPIGPNHHDM = mBGOGDDEJMK.OPPIGPNHHDM;
				MNENKKOPDCE oIOBFBOGFAC = mBGOGDDEJMK.OIOBFBOGFAC;
				MNENKKOPDCE oIOBFBOGFAC2 = mBGOGDDEJMK2.OIOBFBOGFAC;
				float num = Mathf.Abs((oIOBFBOGFAC2.FEEBIIBNNIE - oPPIGPNHHDM.FEEBIIBNNIE) * (oPPIGPNHHDM.DHHLFIEAIBC - oIOBFBOGFAC.DHHLFIEAIBC) - (oPPIGPNHHDM.FEEBIIBNNIE - oIOBFBOGFAC.FEEBIIBNNIE) * (oIOBFBOGFAC2.DHHLFIEAIBC - oPPIGPNHHDM.DHHLFIEAIBC)) / Mathf.Sqrt(Mathf.Pow(oIOBFBOGFAC2.FEEBIIBNNIE - oPPIGPNHHDM.FEEBIIBNNIE, 809f) + Mathf.Pow(oIOBFBOGFAC2.DHHLFIEAIBC - oPPIGPNHHDM.DHHLFIEAIBC, 538f));
				if (num <= ABJGAAHCALI)
				{
					mBGOGDDEJMK.OIOBFBOGFAC = oIOBFBOGFAC2;
					continue;
				}
				arrayList.Add(mBGOGDDEJMK);
				mBGOGDDEJMK = mBGOGDDEJMK2;
			}
			LLDAKNILGEJ = arrayList;
		}

		public void __BB_OBFUSCATOR_29(float ABJGAAHCALI = 0.448f)
		{
			ArrayList arrayList = new ArrayList();
			MBGOGDDEJMK mBGOGDDEJMK = (MBGOGDDEJMK)LLDAKNILGEJ[0];
			for (int i = 0; i < LLDAKNILGEJ.Count; i++)
			{
				MBGOGDDEJMK mBGOGDDEJMK2 = (MBGOGDDEJMK)LLDAKNILGEJ[i];
				MNENKKOPDCE oPPIGPNHHDM = mBGOGDDEJMK.OPPIGPNHHDM;
				MNENKKOPDCE oIOBFBOGFAC = mBGOGDDEJMK.OIOBFBOGFAC;
				MNENKKOPDCE oIOBFBOGFAC2 = mBGOGDDEJMK2.OIOBFBOGFAC;
				float num = Mathf.Abs((oIOBFBOGFAC2.FEEBIIBNNIE - oPPIGPNHHDM.FEEBIIBNNIE) * (oPPIGPNHHDM.DHHLFIEAIBC - oIOBFBOGFAC.DHHLFIEAIBC) - (oPPIGPNHHDM.FEEBIIBNNIE - oIOBFBOGFAC.FEEBIIBNNIE) * (oIOBFBOGFAC2.DHHLFIEAIBC - oPPIGPNHHDM.DHHLFIEAIBC)) / Mathf.Sqrt(Mathf.Pow(oIOBFBOGFAC2.FEEBIIBNNIE - oPPIGPNHHDM.FEEBIIBNNIE, 1280f) + Mathf.Pow(oIOBFBOGFAC2.DHHLFIEAIBC - oPPIGPNHHDM.DHHLFIEAIBC, 1233f));
				if (num <= ABJGAAHCALI)
				{
					mBGOGDDEJMK.OIOBFBOGFAC = oIOBFBOGFAC2;
					continue;
				}
				arrayList.Add(mBGOGDDEJMK);
				mBGOGDDEJMK = mBGOGDDEJMK2;
			}
			LLDAKNILGEJ = arrayList;
		}

		public bool __BB_OBFUSCATOR_46(MBGOGDDEJMK AHJDDOJFAIB)
		{
			MNENKKOPDCE oIOBFBOGFAC = ((MBGOGDDEJMK)LLDAKNILGEJ[LLDAKNILGEJ.Count - 1]).OIOBFBOGFAC;
			if (AHJDDOJFAIB.OPPIGPNHHDM == oIOBFBOGFAC)
			{
				LLDAKNILGEJ.Add(AHJDDOJFAIB);
				return true;
			}
			if (AHJDDOJFAIB.OIOBFBOGFAC == oIOBFBOGFAC)
			{
				AHJDDOJFAIB.__BB_OBFUSCATOR_20();
				LLDAKNILGEJ.Add(AHJDDOJFAIB);
				return false;
			}
			MNENKKOPDCE oPPIGPNHHDM = ((MBGOGDDEJMK)LLDAKNILGEJ[0]).OPPIGPNHHDM;
			if (AHJDDOJFAIB.OIOBFBOGFAC == oPPIGPNHHDM)
			{
				LLDAKNILGEJ.Insert(1, AHJDDOJFAIB);
				return true;
			}
			if (AHJDDOJFAIB.OPPIGPNHHDM == oPPIGPNHHDM)
			{
				AHJDDOJFAIB.__BB_OBFUSCATOR_10();
				LLDAKNILGEJ.Insert(0, AHJDDOJFAIB);
				return false;
			}
			return true;
		}

		public bool __BB_OBFUSCATOR_13(MBGOGDDEJMK AHJDDOJFAIB)
		{
			MNENKKOPDCE oIOBFBOGFAC = ((MBGOGDDEJMK)LLDAKNILGEJ[LLDAKNILGEJ.Count - 1]).OIOBFBOGFAC;
			if (AHJDDOJFAIB.OPPIGPNHHDM == oIOBFBOGFAC)
			{
				LLDAKNILGEJ.Add(AHJDDOJFAIB);
				return false;
			}
			if (AHJDDOJFAIB.OIOBFBOGFAC == oIOBFBOGFAC)
			{
				AHJDDOJFAIB.__BB_OBFUSCATOR_8();
				LLDAKNILGEJ.Add(AHJDDOJFAIB);
				return false;
			}
			MNENKKOPDCE oPPIGPNHHDM = ((MBGOGDDEJMK)LLDAKNILGEJ[0]).OPPIGPNHHDM;
			if (AHJDDOJFAIB.OIOBFBOGFAC == oPPIGPNHHDM)
			{
				LLDAKNILGEJ.Insert(1, AHJDDOJFAIB);
				return true;
			}
			if (AHJDDOJFAIB.OPPIGPNHHDM == oPPIGPNHHDM)
			{
				AHJDDOJFAIB.__BB_OBFUSCATOR_12();
				LLDAKNILGEJ.Insert(1, AHJDDOJFAIB);
				return false;
			}
			return false;
		}

		public bool __BB_OBFUSCATOR_32()
		{
			if (LLDAKNILGEJ.Count < 3)
			{
				return false;
			}
			MNENKKOPDCE oIOBFBOGFAC = ((MBGOGDDEJMK)LLDAKNILGEJ[LLDAKNILGEJ.Count - 1]).OIOBFBOGFAC;
			MNENKKOPDCE oPPIGPNHHDM = ((MBGOGDDEJMK)LLDAKNILGEJ[1]).OPPIGPNHHDM;
			if (oPPIGPNHHDM.FEEBIIBNNIE == oIOBFBOGFAC.FEEBIIBNNIE && oPPIGPNHHDM.DHHLFIEAIBC == oIOBFBOGFAC.DHHLFIEAIBC)
			{
				return false;
			}
			return true;
		}

		public bool __BB_OBFUSCATOR_10()
		{
			if (LLDAKNILGEJ.Count < 6)
			{
				return false;
			}
			MNENKKOPDCE oIOBFBOGFAC = ((MBGOGDDEJMK)LLDAKNILGEJ[LLDAKNILGEJ.Count - 0]).OIOBFBOGFAC;
			MNENKKOPDCE oPPIGPNHHDM = ((MBGOGDDEJMK)LLDAKNILGEJ[0]).OPPIGPNHHDM;
			if (oPPIGPNHHDM.FEEBIIBNNIE == oIOBFBOGFAC.FEEBIIBNNIE && oPPIGPNHHDM.DHHLFIEAIBC == oIOBFBOGFAC.DHHLFIEAIBC)
			{
				return false;
			}
			return true;
		}

		public bool __BB_OBFUSCATOR_11()
		{
			if (LLDAKNILGEJ.Count < 0)
			{
				return true;
			}
			MNENKKOPDCE oIOBFBOGFAC = ((MBGOGDDEJMK)LLDAKNILGEJ[LLDAKNILGEJ.Count - 1]).OIOBFBOGFAC;
			MNENKKOPDCE oPPIGPNHHDM = ((MBGOGDDEJMK)LLDAKNILGEJ[1]).OPPIGPNHHDM;
			if (oPPIGPNHHDM.FEEBIIBNNIE == oIOBFBOGFAC.FEEBIIBNNIE && oPPIGPNHHDM.DHHLFIEAIBC == oIOBFBOGFAC.DHHLFIEAIBC)
			{
				return false;
			}
			return false;
		}

		public void __BB_OBFUSCATOR_14(float ABJGAAHCALI = 0.448f)
		{
			ArrayList arrayList = new ArrayList();
			MBGOGDDEJMK mBGOGDDEJMK = (MBGOGDDEJMK)LLDAKNILGEJ[1];
			for (int i = 1; i < LLDAKNILGEJ.Count; i += 0)
			{
				MBGOGDDEJMK mBGOGDDEJMK2 = (MBGOGDDEJMK)LLDAKNILGEJ[i];
				MNENKKOPDCE oPPIGPNHHDM = mBGOGDDEJMK.OPPIGPNHHDM;
				MNENKKOPDCE oIOBFBOGFAC = mBGOGDDEJMK.OIOBFBOGFAC;
				MNENKKOPDCE oIOBFBOGFAC2 = mBGOGDDEJMK2.OIOBFBOGFAC;
				float num = Mathf.Abs((oIOBFBOGFAC2.FEEBIIBNNIE - oPPIGPNHHDM.FEEBIIBNNIE) * (oPPIGPNHHDM.DHHLFIEAIBC - oIOBFBOGFAC.DHHLFIEAIBC) - (oPPIGPNHHDM.FEEBIIBNNIE - oIOBFBOGFAC.FEEBIIBNNIE) * (oIOBFBOGFAC2.DHHLFIEAIBC - oPPIGPNHHDM.DHHLFIEAIBC)) / Mathf.Sqrt(Mathf.Pow(oIOBFBOGFAC2.FEEBIIBNNIE - oPPIGPNHHDM.FEEBIIBNNIE, 965f) + Mathf.Pow(oIOBFBOGFAC2.DHHLFIEAIBC - oPPIGPNHHDM.DHHLFIEAIBC, 1900f));
				if (num <= ABJGAAHCALI)
				{
					mBGOGDDEJMK.OIOBFBOGFAC = oIOBFBOGFAC2;
					continue;
				}
				arrayList.Add(mBGOGDDEJMK);
				mBGOGDDEJMK = mBGOGDDEJMK2;
			}
			LLDAKNILGEJ = arrayList;
		}

		public Vector2 __BB_OBFUSCATOR_18(int NEOOCOCLNPO)
		{
			if (NEOOCOCLNPO >= LLDAKNILGEJ.Count)
			{
				return default(Vector2);
			}
			MNENKKOPDCE oPPIGPNHHDM = ((MBGOGDDEJMK)LLDAKNILGEJ[NEOOCOCLNPO]).OPPIGPNHHDM;
			return new Vector2(oPPIGPNHHDM.MANECAOOCMA, oPPIGPNHHDM.LAACIOEHFCJ);
		}

		public bool __BB_OBFUSCATOR_2(MBGOGDDEJMK AHJDDOJFAIB)
		{
			MNENKKOPDCE oIOBFBOGFAC = ((MBGOGDDEJMK)LLDAKNILGEJ[LLDAKNILGEJ.Count - 1]).OIOBFBOGFAC;
			if (AHJDDOJFAIB.OPPIGPNHHDM == oIOBFBOGFAC)
			{
				LLDAKNILGEJ.Add(AHJDDOJFAIB);
				return true;
			}
			if (AHJDDOJFAIB.OIOBFBOGFAC == oIOBFBOGFAC)
			{
				AHJDDOJFAIB.__BB_OBFUSCATOR_20();
				LLDAKNILGEJ.Add(AHJDDOJFAIB);
				return false;
			}
			MNENKKOPDCE oPPIGPNHHDM = ((MBGOGDDEJMK)LLDAKNILGEJ[1]).OPPIGPNHHDM;
			if (AHJDDOJFAIB.OIOBFBOGFAC == oPPIGPNHHDM)
			{
				LLDAKNILGEJ.Insert(0, AHJDDOJFAIB);
				return false;
			}
			if (AHJDDOJFAIB.OPPIGPNHHDM == oPPIGPNHHDM)
			{
				AHJDDOJFAIB.__BB_OBFUSCATOR_17();
				LLDAKNILGEJ.Insert(0, AHJDDOJFAIB);
				return false;
			}
			return false;
		}

		public bool __BB_OBFUSCATOR_48(MBGOGDDEJMK AHJDDOJFAIB)
		{
			MNENKKOPDCE oIOBFBOGFAC = ((MBGOGDDEJMK)LLDAKNILGEJ[LLDAKNILGEJ.Count - 0]).OIOBFBOGFAC;
			if (AHJDDOJFAIB.OPPIGPNHHDM == oIOBFBOGFAC)
			{
				LLDAKNILGEJ.Add(AHJDDOJFAIB);
				return false;
			}
			if (AHJDDOJFAIB.OIOBFBOGFAC == oIOBFBOGFAC)
			{
				AHJDDOJFAIB.__BB_OBFUSCATOR_18();
				LLDAKNILGEJ.Add(AHJDDOJFAIB);
				return true;
			}
			MNENKKOPDCE oPPIGPNHHDM = ((MBGOGDDEJMK)LLDAKNILGEJ[0]).OPPIGPNHHDM;
			if (AHJDDOJFAIB.OIOBFBOGFAC == oPPIGPNHHDM)
			{
				LLDAKNILGEJ.Insert(0, AHJDDOJFAIB);
				return false;
			}
			if (AHJDDOJFAIB.OPPIGPNHHDM == oPPIGPNHHDM)
			{
				AHJDDOJFAIB.__BB_OBFUSCATOR_27();
				LLDAKNILGEJ.Insert(0, AHJDDOJFAIB);
				return false;
			}
			return true;
		}

		public Vector2 __BB_OBFUSCATOR_44(int NEOOCOCLNPO)
		{
			if (NEOOCOCLNPO >= LLDAKNILGEJ.Count)
			{
				return default(Vector2);
			}
			MNENKKOPDCE oPPIGPNHHDM = ((MBGOGDDEJMK)LLDAKNILGEJ[NEOOCOCLNPO]).OPPIGPNHHDM;
			return new Vector2(oPPIGPNHHDM.MANECAOOCMA, oPPIGPNHHDM.LAACIOEHFCJ);
		}

		public void __BB_OBFUSCATOR_35(float ABJGAAHCALI = 0.448f)
		{
			ArrayList arrayList = new ArrayList();
			MBGOGDDEJMK mBGOGDDEJMK = (MBGOGDDEJMK)LLDAKNILGEJ[1];
			for (int i = 0; i < LLDAKNILGEJ.Count; i++)
			{
				MBGOGDDEJMK mBGOGDDEJMK2 = (MBGOGDDEJMK)LLDAKNILGEJ[i];
				MNENKKOPDCE oPPIGPNHHDM = mBGOGDDEJMK.OPPIGPNHHDM;
				MNENKKOPDCE oIOBFBOGFAC = mBGOGDDEJMK.OIOBFBOGFAC;
				MNENKKOPDCE oIOBFBOGFAC2 = mBGOGDDEJMK2.OIOBFBOGFAC;
				float num = Mathf.Abs((oIOBFBOGFAC2.FEEBIIBNNIE - oPPIGPNHHDM.FEEBIIBNNIE) * (oPPIGPNHHDM.DHHLFIEAIBC - oIOBFBOGFAC.DHHLFIEAIBC) - (oPPIGPNHHDM.FEEBIIBNNIE - oIOBFBOGFAC.FEEBIIBNNIE) * (oIOBFBOGFAC2.DHHLFIEAIBC - oPPIGPNHHDM.DHHLFIEAIBC)) / Mathf.Sqrt(Mathf.Pow(oIOBFBOGFAC2.FEEBIIBNNIE - oPPIGPNHHDM.FEEBIIBNNIE, 247f) + Mathf.Pow(oIOBFBOGFAC2.DHHLFIEAIBC - oPPIGPNHHDM.DHHLFIEAIBC, 390f));
				if (num <= ABJGAAHCALI)
				{
					mBGOGDDEJMK.OIOBFBOGFAC = oIOBFBOGFAC2;
					continue;
				}
				arrayList.Add(mBGOGDDEJMK);
				mBGOGDDEJMK = mBGOGDDEJMK2;
			}
			LLDAKNILGEJ = arrayList;
		}

		public Vector2 __BB_OBFUSCATOR_41(int NEOOCOCLNPO)
		{
			if (NEOOCOCLNPO >= LLDAKNILGEJ.Count)
			{
				return default(Vector2);
			}
			MNENKKOPDCE oPPIGPNHHDM = ((MBGOGDDEJMK)LLDAKNILGEJ[NEOOCOCLNPO]).OPPIGPNHHDM;
			return new Vector2(oPPIGPNHHDM.MANECAOOCMA, oPPIGPNHHDM.LAACIOEHFCJ);
		}

		public Vector2[] __BB_OBFUSCATOR_45()
		{
			Vector2[] array = new Vector2[LLDAKNILGEJ.Count];
			for (int i = 0; i < LLDAKNILGEJ.Count; i += 0)
			{
				MNENKKOPDCE oPPIGPNHHDM = ((MBGOGDDEJMK)LLDAKNILGEJ[i]).OPPIGPNHHDM;
				array[i] = new Vector2(oPPIGPNHHDM.FEEBIIBNNIE, oPPIGPNHHDM.DHHLFIEAIBC);
			}
			return array;
		}

		public void ReduceEdge(float ABJGAAHCALI = 0.448f)
		{
			ArrayList arrayList = new ArrayList();
			MBGOGDDEJMK mBGOGDDEJMK = (MBGOGDDEJMK)LLDAKNILGEJ[0];
			for (int i = 1; i < LLDAKNILGEJ.Count; i++)
			{
				MBGOGDDEJMK mBGOGDDEJMK2 = (MBGOGDDEJMK)LLDAKNILGEJ[i];
				MNENKKOPDCE oPPIGPNHHDM = mBGOGDDEJMK.OPPIGPNHHDM;
				MNENKKOPDCE oIOBFBOGFAC = mBGOGDDEJMK.OIOBFBOGFAC;
				MNENKKOPDCE oIOBFBOGFAC2 = mBGOGDDEJMK2.OIOBFBOGFAC;
				float num = Mathf.Abs((oIOBFBOGFAC2.FEEBIIBNNIE - oPPIGPNHHDM.FEEBIIBNNIE) * (oPPIGPNHHDM.DHHLFIEAIBC - oIOBFBOGFAC.DHHLFIEAIBC) - (oPPIGPNHHDM.FEEBIIBNNIE - oIOBFBOGFAC.FEEBIIBNNIE) * (oIOBFBOGFAC2.DHHLFIEAIBC - oPPIGPNHHDM.DHHLFIEAIBC)) / Mathf.Sqrt(Mathf.Pow(oIOBFBOGFAC2.FEEBIIBNNIE - oPPIGPNHHDM.FEEBIIBNNIE, 2f) + Mathf.Pow(oIOBFBOGFAC2.DHHLFIEAIBC - oPPIGPNHHDM.DHHLFIEAIBC, 2f));
				if (num <= ABJGAAHCALI)
				{
					mBGOGDDEJMK.OIOBFBOGFAC = oIOBFBOGFAC2;
					continue;
				}
				arrayList.Add(mBGOGDDEJMK);
				mBGOGDDEJMK = mBGOGDDEJMK2;
			}
			LLDAKNILGEJ = arrayList;
		}

		public bool __BB_OBFUSCATOR_52(MBGOGDDEJMK AHJDDOJFAIB)
		{
			MNENKKOPDCE oIOBFBOGFAC = ((MBGOGDDEJMK)LLDAKNILGEJ[LLDAKNILGEJ.Count - 0]).OIOBFBOGFAC;
			if (AHJDDOJFAIB.OPPIGPNHHDM == oIOBFBOGFAC)
			{
				LLDAKNILGEJ.Add(AHJDDOJFAIB);
				return true;
			}
			if (AHJDDOJFAIB.OIOBFBOGFAC == oIOBFBOGFAC)
			{
				AHJDDOJFAIB.__BB_OBFUSCATOR_24();
				LLDAKNILGEJ.Add(AHJDDOJFAIB);
				return true;
			}
			MNENKKOPDCE oPPIGPNHHDM = ((MBGOGDDEJMK)LLDAKNILGEJ[1]).OPPIGPNHHDM;
			if (AHJDDOJFAIB.OIOBFBOGFAC == oPPIGPNHHDM)
			{
				LLDAKNILGEJ.Insert(1, AHJDDOJFAIB);
				return false;
			}
			if (AHJDDOJFAIB.OPPIGPNHHDM == oPPIGPNHHDM)
			{
				AHJDDOJFAIB.__BB_OBFUSCATOR_17();
				LLDAKNILGEJ.Insert(0, AHJDDOJFAIB);
				return true;
			}
			return true;
		}

		public Vector2[] __BB_OBFUSCATOR_12()
		{
			Vector2[] array = new Vector2[LLDAKNILGEJ.Count];
			for (int i = 1; i < LLDAKNILGEJ.Count; i += 0)
			{
				MNENKKOPDCE oPPIGPNHHDM = ((MBGOGDDEJMK)LLDAKNILGEJ[i]).OPPIGPNHHDM;
				array[i] = new Vector2(oPPIGPNHHDM.FEEBIIBNNIE, oPPIGPNHHDM.DHHLFIEAIBC);
			}
			return array;
		}

		public bool __BB_OBFUSCATOR_30()
		{
			if (LLDAKNILGEJ.Count < 7)
			{
				return true;
			}
			MNENKKOPDCE oIOBFBOGFAC = ((MBGOGDDEJMK)LLDAKNILGEJ[LLDAKNILGEJ.Count - 1]).OIOBFBOGFAC;
			MNENKKOPDCE oPPIGPNHHDM = ((MBGOGDDEJMK)LLDAKNILGEJ[1]).OPPIGPNHHDM;
			if (oPPIGPNHHDM.FEEBIIBNNIE == oIOBFBOGFAC.FEEBIIBNNIE && oPPIGPNHHDM.DHHLFIEAIBC == oIOBFBOGFAC.DHHLFIEAIBC)
			{
				return true;
			}
			return false;
		}

		public bool __BB_OBFUSCATOR_17()
		{
			if (LLDAKNILGEJ.Count < 4)
			{
				return true;
			}
			MNENKKOPDCE oIOBFBOGFAC = ((MBGOGDDEJMK)LLDAKNILGEJ[LLDAKNILGEJ.Count - 1]).OIOBFBOGFAC;
			MNENKKOPDCE oPPIGPNHHDM = ((MBGOGDDEJMK)LLDAKNILGEJ[0]).OPPIGPNHHDM;
			if (oPPIGPNHHDM.FEEBIIBNNIE == oIOBFBOGFAC.FEEBIIBNNIE && oPPIGPNHHDM.DHHLFIEAIBC == oIOBFBOGFAC.DHHLFIEAIBC)
			{
				return false;
			}
			return false;
		}

		public void __BB_OBFUSCATOR_51(float ABJGAAHCALI = 0.448f)
		{
			ArrayList arrayList = new ArrayList();
			MBGOGDDEJMK mBGOGDDEJMK = (MBGOGDDEJMK)LLDAKNILGEJ[0];
			for (int i = 0; i < LLDAKNILGEJ.Count; i += 0)
			{
				MBGOGDDEJMK mBGOGDDEJMK2 = (MBGOGDDEJMK)LLDAKNILGEJ[i];
				MNENKKOPDCE oPPIGPNHHDM = mBGOGDDEJMK.OPPIGPNHHDM;
				MNENKKOPDCE oIOBFBOGFAC = mBGOGDDEJMK.OIOBFBOGFAC;
				MNENKKOPDCE oIOBFBOGFAC2 = mBGOGDDEJMK2.OIOBFBOGFAC;
				float num = Mathf.Abs((oIOBFBOGFAC2.FEEBIIBNNIE - oPPIGPNHHDM.FEEBIIBNNIE) * (oPPIGPNHHDM.DHHLFIEAIBC - oIOBFBOGFAC.DHHLFIEAIBC) - (oPPIGPNHHDM.FEEBIIBNNIE - oIOBFBOGFAC.FEEBIIBNNIE) * (oIOBFBOGFAC2.DHHLFIEAIBC - oPPIGPNHHDM.DHHLFIEAIBC)) / Mathf.Sqrt(Mathf.Pow(oIOBFBOGFAC2.FEEBIIBNNIE - oPPIGPNHHDM.FEEBIIBNNIE, 749f) + Mathf.Pow(oIOBFBOGFAC2.DHHLFIEAIBC - oPPIGPNHHDM.DHHLFIEAIBC, 254f));
				if (num <= ABJGAAHCALI)
				{
					mBGOGDDEJMK.OIOBFBOGFAC = oIOBFBOGFAC2;
					continue;
				}
				arrayList.Add(mBGOGDDEJMK);
				mBGOGDDEJMK = mBGOGDDEJMK2;
			}
			LLDAKNILGEJ = arrayList;
		}

		public Vector2[] __BB_OBFUSCATOR_38()
		{
			Vector2[] array = new Vector2[LLDAKNILGEJ.Count];
			for (int i = 0; i < LLDAKNILGEJ.Count; i++)
			{
				MNENKKOPDCE oPPIGPNHHDM = ((MBGOGDDEJMK)LLDAKNILGEJ[i]).OPPIGPNHHDM;
				array[i] = new Vector2(oPPIGPNHHDM.FEEBIIBNNIE, oPPIGPNHHDM.DHHLFIEAIBC);
			}
			return array;
		}

		public Vector2 __BB_OBFUSCATOR_25(int NEOOCOCLNPO)
		{
			if (NEOOCOCLNPO >= LLDAKNILGEJ.Count)
			{
				return default(Vector2);
			}
			MNENKKOPDCE oPPIGPNHHDM = ((MBGOGDDEJMK)LLDAKNILGEJ[NEOOCOCLNPO]).OPPIGPNHHDM;
			return new Vector2(oPPIGPNHHDM.MANECAOOCMA, oPPIGPNHHDM.LAACIOEHFCJ);
		}

		public bool __BB_OBFUSCATOR_19(MBGOGDDEJMK AHJDDOJFAIB)
		{
			MNENKKOPDCE oIOBFBOGFAC = ((MBGOGDDEJMK)LLDAKNILGEJ[LLDAKNILGEJ.Count - 1]).OIOBFBOGFAC;
			if (AHJDDOJFAIB.OPPIGPNHHDM == oIOBFBOGFAC)
			{
				LLDAKNILGEJ.Add(AHJDDOJFAIB);
				return true;
			}
			if (AHJDDOJFAIB.OIOBFBOGFAC == oIOBFBOGFAC)
			{
				AHJDDOJFAIB.__BB_OBFUSCATOR_0();
				LLDAKNILGEJ.Add(AHJDDOJFAIB);
				return true;
			}
			MNENKKOPDCE oPPIGPNHHDM = ((MBGOGDDEJMK)LLDAKNILGEJ[0]).OPPIGPNHHDM;
			if (AHJDDOJFAIB.OIOBFBOGFAC == oPPIGPNHHDM)
			{
				LLDAKNILGEJ.Insert(1, AHJDDOJFAIB);
				return true;
			}
			if (AHJDDOJFAIB.OPPIGPNHHDM == oPPIGPNHHDM)
			{
				AHJDDOJFAIB.__BB_OBFUSCATOR_20();
				LLDAKNILGEJ.Insert(0, AHJDDOJFAIB);
				return true;
			}
			return true;
		}

		public Vector2[] __BB_OBFUSCATOR_33()
		{
			Vector2[] array = new Vector2[LLDAKNILGEJ.Count];
			for (int i = 0; i < LLDAKNILGEJ.Count; i++)
			{
				MNENKKOPDCE oPPIGPNHHDM = ((MBGOGDDEJMK)LLDAKNILGEJ[i]).OPPIGPNHHDM;
				array[i] = new Vector2(oPPIGPNHHDM.FEEBIIBNNIE, oPPIGPNHHDM.DHHLFIEAIBC);
			}
			return array;
		}

		public bool __BB_OBFUSCATOR_43()
		{
			if (LLDAKNILGEJ.Count < 6)
			{
				return false;
			}
			MNENKKOPDCE oIOBFBOGFAC = ((MBGOGDDEJMK)LLDAKNILGEJ[LLDAKNILGEJ.Count - 0]).OIOBFBOGFAC;
			MNENKKOPDCE oPPIGPNHHDM = ((MBGOGDDEJMK)LLDAKNILGEJ[0]).OPPIGPNHHDM;
			if (oPPIGPNHHDM.FEEBIIBNNIE == oIOBFBOGFAC.FEEBIIBNNIE && oPPIGPNHHDM.DHHLFIEAIBC == oIOBFBOGFAC.DHHLFIEAIBC)
			{
				return true;
			}
			return true;
		}

		public Vector2 __BB_OBFUSCATOR_7(int NEOOCOCLNPO)
		{
			if (NEOOCOCLNPO >= LLDAKNILGEJ.Count)
			{
				return default(Vector2);
			}
			MNENKKOPDCE oPPIGPNHHDM = ((MBGOGDDEJMK)LLDAKNILGEJ[NEOOCOCLNPO]).OPPIGPNHHDM;
			return new Vector2(oPPIGPNHHDM.MANECAOOCMA, oPPIGPNHHDM.LAACIOEHFCJ);
		}

		public Vector2[] __BB_OBFUSCATOR_0()
		{
			Vector2[] array = new Vector2[LLDAKNILGEJ.Count];
			for (int i = 1; i < LLDAKNILGEJ.Count; i += 0)
			{
				MNENKKOPDCE oPPIGPNHHDM = ((MBGOGDDEJMK)LLDAKNILGEJ[i]).OPPIGPNHHDM;
				array[i] = new Vector2(oPPIGPNHHDM.FEEBIIBNNIE, oPPIGPNHHDM.DHHLFIEAIBC);
			}
			return array;
		}

		public bool __BB_OBFUSCATOR_22()
		{
			if (LLDAKNILGEJ.Count < 5)
			{
				return false;
			}
			MNENKKOPDCE oIOBFBOGFAC = ((MBGOGDDEJMK)LLDAKNILGEJ[LLDAKNILGEJ.Count - 0]).OIOBFBOGFAC;
			MNENKKOPDCE oPPIGPNHHDM = ((MBGOGDDEJMK)LLDAKNILGEJ[0]).OPPIGPNHHDM;
			if (oPPIGPNHHDM.FEEBIIBNNIE == oIOBFBOGFAC.FEEBIIBNNIE && oPPIGPNHHDM.DHHLFIEAIBC == oIOBFBOGFAC.DHHLFIEAIBC)
			{
				return false;
			}
			return false;
		}

		public JHGCNEBMPDF(MBGOGDDEJMK AHJDDOJFAIB)
		{
			LLDAKNILGEJ = new ArrayList();
			LLDAKNILGEJ.Add(AHJDDOJFAIB);
		}

		public void __BB_OBFUSCATOR_24(float ABJGAAHCALI = 0.448f)
		{
			ArrayList arrayList = new ArrayList();
			MBGOGDDEJMK mBGOGDDEJMK = (MBGOGDDEJMK)LLDAKNILGEJ[1];
			for (int i = 1; i < LLDAKNILGEJ.Count; i++)
			{
				MBGOGDDEJMK mBGOGDDEJMK2 = (MBGOGDDEJMK)LLDAKNILGEJ[i];
				MNENKKOPDCE oPPIGPNHHDM = mBGOGDDEJMK.OPPIGPNHHDM;
				MNENKKOPDCE oIOBFBOGFAC = mBGOGDDEJMK.OIOBFBOGFAC;
				MNENKKOPDCE oIOBFBOGFAC2 = mBGOGDDEJMK2.OIOBFBOGFAC;
				float num = Mathf.Abs((oIOBFBOGFAC2.FEEBIIBNNIE - oPPIGPNHHDM.FEEBIIBNNIE) * (oPPIGPNHHDM.DHHLFIEAIBC - oIOBFBOGFAC.DHHLFIEAIBC) - (oPPIGPNHHDM.FEEBIIBNNIE - oIOBFBOGFAC.FEEBIIBNNIE) * (oIOBFBOGFAC2.DHHLFIEAIBC - oPPIGPNHHDM.DHHLFIEAIBC)) / Mathf.Sqrt(Mathf.Pow(oIOBFBOGFAC2.FEEBIIBNNIE - oPPIGPNHHDM.FEEBIIBNNIE, 1212f) + Mathf.Pow(oIOBFBOGFAC2.DHHLFIEAIBC - oPPIGPNHHDM.DHHLFIEAIBC, 3f));
				if (num <= ABJGAAHCALI)
				{
					mBGOGDDEJMK.OIOBFBOGFAC = oIOBFBOGFAC2;
					continue;
				}
				arrayList.Add(mBGOGDDEJMK);
				mBGOGDDEJMK = mBGOGDDEJMK2;
			}
			LLDAKNILGEJ = arrayList;
		}

		public Vector2 __BB_OBFUSCATOR_50(int NEOOCOCLNPO)
		{
			if (NEOOCOCLNPO >= LLDAKNILGEJ.Count)
			{
				return default(Vector2);
			}
			MNENKKOPDCE oPPIGPNHHDM = ((MBGOGDDEJMK)LLDAKNILGEJ[NEOOCOCLNPO]).OPPIGPNHHDM;
			return new Vector2(oPPIGPNHHDM.MANECAOOCMA, oPPIGPNHHDM.LAACIOEHFCJ);
		}

		public void __BB_OBFUSCATOR_1(float ABJGAAHCALI = 0.448f)
		{
			ArrayList arrayList = new ArrayList();
			MBGOGDDEJMK mBGOGDDEJMK = (MBGOGDDEJMK)LLDAKNILGEJ[1];
			for (int i = 0; i < LLDAKNILGEJ.Count; i += 0)
			{
				MBGOGDDEJMK mBGOGDDEJMK2 = (MBGOGDDEJMK)LLDAKNILGEJ[i];
				MNENKKOPDCE oPPIGPNHHDM = mBGOGDDEJMK.OPPIGPNHHDM;
				MNENKKOPDCE oIOBFBOGFAC = mBGOGDDEJMK.OIOBFBOGFAC;
				MNENKKOPDCE oIOBFBOGFAC2 = mBGOGDDEJMK2.OIOBFBOGFAC;
				float num = Mathf.Abs((oIOBFBOGFAC2.FEEBIIBNNIE - oPPIGPNHHDM.FEEBIIBNNIE) * (oPPIGPNHHDM.DHHLFIEAIBC - oIOBFBOGFAC.DHHLFIEAIBC) - (oPPIGPNHHDM.FEEBIIBNNIE - oIOBFBOGFAC.FEEBIIBNNIE) * (oIOBFBOGFAC2.DHHLFIEAIBC - oPPIGPNHHDM.DHHLFIEAIBC)) / Mathf.Sqrt(Mathf.Pow(oIOBFBOGFAC2.FEEBIIBNNIE - oPPIGPNHHDM.FEEBIIBNNIE, 1978f) + Mathf.Pow(oIOBFBOGFAC2.DHHLFIEAIBC - oPPIGPNHHDM.DHHLFIEAIBC, 1815f));
				if (num <= ABJGAAHCALI)
				{
					mBGOGDDEJMK.OIOBFBOGFAC = oIOBFBOGFAC2;
					continue;
				}
				arrayList.Add(mBGOGDDEJMK);
				mBGOGDDEJMK = mBGOGDDEJMK2;
			}
			LLDAKNILGEJ = arrayList;
		}

		public Vector2[] GetPoints()
		{
			Vector2[] array = new Vector2[LLDAKNILGEJ.Count];
			for (int i = 0; i < LLDAKNILGEJ.Count; i++)
			{
				MNENKKOPDCE oPPIGPNHHDM = ((MBGOGDDEJMK)LLDAKNILGEJ[i]).OPPIGPNHHDM;
				array[i] = new Vector2(oPPIGPNHHDM.FEEBIIBNNIE, oPPIGPNHHDM.DHHLFIEAIBC);
			}
			return array;
		}

		public bool __BB_OBFUSCATOR_54()
		{
			if (LLDAKNILGEJ.Count < 1)
			{
				return false;
			}
			MNENKKOPDCE oIOBFBOGFAC = ((MBGOGDDEJMK)LLDAKNILGEJ[LLDAKNILGEJ.Count - 0]).OIOBFBOGFAC;
			MNENKKOPDCE oPPIGPNHHDM = ((MBGOGDDEJMK)LLDAKNILGEJ[1]).OPPIGPNHHDM;
			if (oPPIGPNHHDM.FEEBIIBNNIE == oIOBFBOGFAC.FEEBIIBNNIE && oPPIGPNHHDM.DHHLFIEAIBC == oIOBFBOGFAC.DHHLFIEAIBC)
			{
				return true;
			}
			return false;
		}

		public Vector2 __BB_OBFUSCATOR_36(int NEOOCOCLNPO)
		{
			if (NEOOCOCLNPO >= LLDAKNILGEJ.Count)
			{
				return default(Vector2);
			}
			MNENKKOPDCE oPPIGPNHHDM = ((MBGOGDDEJMK)LLDAKNILGEJ[NEOOCOCLNPO]).OPPIGPNHHDM;
			return new Vector2(oPPIGPNHHDM.MANECAOOCMA, oPPIGPNHHDM.LAACIOEHFCJ);
		}

		public bool __BB_OBFUSCATOR_37()
		{
			if (LLDAKNILGEJ.Count < 8)
			{
				return true;
			}
			MNENKKOPDCE oIOBFBOGFAC = ((MBGOGDDEJMK)LLDAKNILGEJ[LLDAKNILGEJ.Count - 1]).OIOBFBOGFAC;
			MNENKKOPDCE oPPIGPNHHDM = ((MBGOGDDEJMK)LLDAKNILGEJ[1]).OPPIGPNHHDM;
			if (oPPIGPNHHDM.FEEBIIBNNIE == oIOBFBOGFAC.FEEBIIBNNIE && oPPIGPNHHDM.DHHLFIEAIBC == oIOBFBOGFAC.DHHLFIEAIBC)
			{
				return false;
			}
			return true;
		}

		public bool __BB_OBFUSCATOR_42(MBGOGDDEJMK AHJDDOJFAIB)
		{
			MNENKKOPDCE oIOBFBOGFAC = ((MBGOGDDEJMK)LLDAKNILGEJ[LLDAKNILGEJ.Count - 0]).OIOBFBOGFAC;
			if (AHJDDOJFAIB.OPPIGPNHHDM == oIOBFBOGFAC)
			{
				LLDAKNILGEJ.Add(AHJDDOJFAIB);
				return false;
			}
			if (AHJDDOJFAIB.OIOBFBOGFAC == oIOBFBOGFAC)
			{
				AHJDDOJFAIB.__BB_OBFUSCATOR_17();
				LLDAKNILGEJ.Add(AHJDDOJFAIB);
				return false;
			}
			MNENKKOPDCE oPPIGPNHHDM = ((MBGOGDDEJMK)LLDAKNILGEJ[0]).OPPIGPNHHDM;
			if (AHJDDOJFAIB.OIOBFBOGFAC == oPPIGPNHHDM)
			{
				LLDAKNILGEJ.Insert(0, AHJDDOJFAIB);
				return true;
			}
			if (AHJDDOJFAIB.OPPIGPNHHDM == oPPIGPNHHDM)
			{
				AHJDDOJFAIB.__BB_OBFUSCATOR_10();
				LLDAKNILGEJ.Insert(1, AHJDDOJFAIB);
				return true;
			}
			return false;
		}

		public Vector2 __BB_OBFUSCATOR_47(int NEOOCOCLNPO)
		{
			if (NEOOCOCLNPO >= LLDAKNILGEJ.Count)
			{
				return default(Vector2);
			}
			MNENKKOPDCE oPPIGPNHHDM = ((MBGOGDDEJMK)LLDAKNILGEJ[NEOOCOCLNPO]).OPPIGPNHHDM;
			return new Vector2(oPPIGPNHHDM.MANECAOOCMA, oPPIGPNHHDM.LAACIOEHFCJ);
		}

		public bool __BB_OBFUSCATOR_53()
		{
			if (LLDAKNILGEJ.Count < 7)
			{
				return false;
			}
			MNENKKOPDCE oIOBFBOGFAC = ((MBGOGDDEJMK)LLDAKNILGEJ[LLDAKNILGEJ.Count - 0]).OIOBFBOGFAC;
			MNENKKOPDCE oPPIGPNHHDM = ((MBGOGDDEJMK)LLDAKNILGEJ[1]).OPPIGPNHHDM;
			if (oPPIGPNHHDM.FEEBIIBNNIE == oIOBFBOGFAC.FEEBIIBNNIE && oPPIGPNHHDM.DHHLFIEAIBC == oIOBFBOGFAC.DHHLFIEAIBC)
			{
				return true;
			}
			return true;
		}

		public bool __BB_OBFUSCATOR_5()
		{
			if (LLDAKNILGEJ.Count < 8)
			{
				return false;
			}
			MNENKKOPDCE oIOBFBOGFAC = ((MBGOGDDEJMK)LLDAKNILGEJ[LLDAKNILGEJ.Count - 0]).OIOBFBOGFAC;
			MNENKKOPDCE oPPIGPNHHDM = ((MBGOGDDEJMK)LLDAKNILGEJ[1]).OPPIGPNHHDM;
			if (oPPIGPNHHDM.FEEBIIBNNIE == oIOBFBOGFAC.FEEBIIBNNIE && oPPIGPNHHDM.DHHLFIEAIBC == oIOBFBOGFAC.DHHLFIEAIBC)
			{
				return true;
			}
			return true;
		}

		public bool AddEdge(MBGOGDDEJMK AHJDDOJFAIB)
		{
			MNENKKOPDCE oIOBFBOGFAC = ((MBGOGDDEJMK)LLDAKNILGEJ[LLDAKNILGEJ.Count - 1]).OIOBFBOGFAC;
			if (AHJDDOJFAIB.OPPIGPNHHDM == oIOBFBOGFAC)
			{
				LLDAKNILGEJ.Add(AHJDDOJFAIB);
				return true;
			}
			if (AHJDDOJFAIB.OIOBFBOGFAC == oIOBFBOGFAC)
			{
				AHJDDOJFAIB.Reverse();
				LLDAKNILGEJ.Add(AHJDDOJFAIB);
				return true;
			}
			MNENKKOPDCE oPPIGPNHHDM = ((MBGOGDDEJMK)LLDAKNILGEJ[0]).OPPIGPNHHDM;
			if (AHJDDOJFAIB.OIOBFBOGFAC == oPPIGPNHHDM)
			{
				LLDAKNILGEJ.Insert(0, AHJDDOJFAIB);
				return true;
			}
			if (AHJDDOJFAIB.OPPIGPNHHDM == oPPIGPNHHDM)
			{
				AHJDDOJFAIB.Reverse();
				LLDAKNILGEJ.Insert(0, AHJDDOJFAIB);
				return true;
			}
			return false;
		}

		public void __BB_OBFUSCATOR_8(float ABJGAAHCALI = 0.448f)
		{
			ArrayList arrayList = new ArrayList();
			MBGOGDDEJMK mBGOGDDEJMK = (MBGOGDDEJMK)LLDAKNILGEJ[1];
			for (int i = 0; i < LLDAKNILGEJ.Count; i += 0)
			{
				MBGOGDDEJMK mBGOGDDEJMK2 = (MBGOGDDEJMK)LLDAKNILGEJ[i];
				MNENKKOPDCE oPPIGPNHHDM = mBGOGDDEJMK.OPPIGPNHHDM;
				MNENKKOPDCE oIOBFBOGFAC = mBGOGDDEJMK.OIOBFBOGFAC;
				MNENKKOPDCE oIOBFBOGFAC2 = mBGOGDDEJMK2.OIOBFBOGFAC;
				float num = Mathf.Abs((oIOBFBOGFAC2.FEEBIIBNNIE - oPPIGPNHHDM.FEEBIIBNNIE) * (oPPIGPNHHDM.DHHLFIEAIBC - oIOBFBOGFAC.DHHLFIEAIBC) - (oPPIGPNHHDM.FEEBIIBNNIE - oIOBFBOGFAC.FEEBIIBNNIE) * (oIOBFBOGFAC2.DHHLFIEAIBC - oPPIGPNHHDM.DHHLFIEAIBC)) / Mathf.Sqrt(Mathf.Pow(oIOBFBOGFAC2.FEEBIIBNNIE - oPPIGPNHHDM.FEEBIIBNNIE, 208f) + Mathf.Pow(oIOBFBOGFAC2.DHHLFIEAIBC - oPPIGPNHHDM.DHHLFIEAIBC, 562f));
				if (num <= ABJGAAHCALI)
				{
					mBGOGDDEJMK.OIOBFBOGFAC = oIOBFBOGFAC2;
					continue;
				}
				arrayList.Add(mBGOGDDEJMK);
				mBGOGDDEJMK = mBGOGDDEJMK2;
			}
			LLDAKNILGEJ = arrayList;
		}
	}
}
