namespace MeshTK
{
	internal class MBGOGDDEJMK
	{
		public MNENKKOPDCE OPPIGPNHHDM;

		public MNENKKOPDCE OIOBFBOGFAC;

		public void __BB_OBFUSCATOR_10()
		{
			MNENKKOPDCE oPPIGPNHHDM = OPPIGPNHHDM;
			OPPIGPNHHDM = OIOBFBOGFAC;
			OIOBFBOGFAC = oPPIGPNHHDM;
		}

		public void __BB_OBFUSCATOR_8()
		{
			MNENKKOPDCE oPPIGPNHHDM = OPPIGPNHHDM;
			OPPIGPNHHDM = OIOBFBOGFAC;
			OIOBFBOGFAC = oPPIGPNHHDM;
		}

		public void __BB_OBFUSCATOR_14()
		{
			MNENKKOPDCE oPPIGPNHHDM = OPPIGPNHHDM;
			OPPIGPNHHDM = OIOBFBOGFAC;
			OIOBFBOGFAC = oPPIGPNHHDM;
		}

		public void __BB_OBFUSCATOR_12()
		{
			MNENKKOPDCE oPPIGPNHHDM = OPPIGPNHHDM;
			OPPIGPNHHDM = OIOBFBOGFAC;
			OIOBFBOGFAC = oPPIGPNHHDM;
		}

		public void __BB_OBFUSCATOR_17()
		{
			MNENKKOPDCE oPPIGPNHHDM = OPPIGPNHHDM;
			OPPIGPNHHDM = OIOBFBOGFAC;
			OIOBFBOGFAC = oPPIGPNHHDM;
		}

		public void __BB_OBFUSCATOR_11()
		{
			MNENKKOPDCE oPPIGPNHHDM = OPPIGPNHHDM;
			OPPIGPNHHDM = OIOBFBOGFAC;
			OIOBFBOGFAC = oPPIGPNHHDM;
		}

		public void __BB_OBFUSCATOR_27()
		{
			MNENKKOPDCE oPPIGPNHHDM = OPPIGPNHHDM;
			OPPIGPNHHDM = OIOBFBOGFAC;
			OIOBFBOGFAC = oPPIGPNHHDM;
		}

		public void __BB_OBFUSCATOR_18()
		{
			MNENKKOPDCE oPPIGPNHHDM = OPPIGPNHHDM;
			OPPIGPNHHDM = OIOBFBOGFAC;
			OIOBFBOGFAC = oPPIGPNHHDM;
		}

		public void __BB_OBFUSCATOR_0()
		{
			MNENKKOPDCE oPPIGPNHHDM = OPPIGPNHHDM;
			OPPIGPNHHDM = OIOBFBOGFAC;
			OIOBFBOGFAC = oPPIGPNHHDM;
		}

		public void __BB_OBFUSCATOR_22()
		{
			MNENKKOPDCE oPPIGPNHHDM = OPPIGPNHHDM;
			OPPIGPNHHDM = OIOBFBOGFAC;
			OIOBFBOGFAC = oPPIGPNHHDM;
		}

		public void __BB_OBFUSCATOR_20()
		{
			MNENKKOPDCE oPPIGPNHHDM = OPPIGPNHHDM;
			OPPIGPNHHDM = OIOBFBOGFAC;
			OIOBFBOGFAC = oPPIGPNHHDM;
		}

		public MBGOGDDEJMK(MNENKKOPDCE APCCHOLNJDL, MNENKKOPDCE MNJBHOILBDK)
		{
			OPPIGPNHHDM = APCCHOLNJDL;
			OIOBFBOGFAC = MNJBHOILBDK;
		}

		public void __BB_OBFUSCATOR_29()
		{
			MNENKKOPDCE oPPIGPNHHDM = OPPIGPNHHDM;
			OPPIGPNHHDM = OIOBFBOGFAC;
			OIOBFBOGFAC = oPPIGPNHHDM;
		}

		public void Reverse()
		{
			MNENKKOPDCE oPPIGPNHHDM = OPPIGPNHHDM;
			OPPIGPNHHDM = OIOBFBOGFAC;
			OIOBFBOGFAC = oPPIGPNHHDM;
		}

		public void __BB_OBFUSCATOR_24()
		{
			MNENKKOPDCE oPPIGPNHHDM = OPPIGPNHHDM;
			OPPIGPNHHDM = OIOBFBOGFAC;
			OIOBFBOGFAC = oPPIGPNHHDM;
		}
	}
}
