using System;
using System.IO;
using System.Security.Cryptography;

namespace Mono.CompilerServices.SymbolWriter
{
	public class SourceFileEntry
	{
		public readonly int Index;

		private int DataOffset;

		private MonoSymbolFile file;

		private string file_name;

		private byte[] guid;

		private byte[] hash;

		private bool creating;

		private bool auto_generated;

		public static int Size
		{
			get
			{
				return 8;
			}
		}

		public string FileName
		{
			get
			{
				return file_name;
			}
		}

		public bool AutoGenerated
		{
			get
			{
				return auto_generated;
			}
		}

		public SourceFileEntry(MonoSymbolFile file, string file_name)
		{
			this.file = file;
			this.file_name = file_name;
			Index = file.AddSource(this);
			creating = true;
		}

		public SourceFileEntry(MonoSymbolFile file, string file_name, byte[] guid, byte[] checksum)
			: this(file, file_name)
		{
			this.guid = guid;
			hash = checksum;
		}

		internal SourceFileEntry(MonoSymbolFile file, MyBinaryReader reader)
		{
			this.file = file;
			Index = reader.ReadInt32();
			DataOffset = reader.ReadInt32();
			int num = (int)reader.BaseStream.Position;
			reader.BaseStream.Position = DataOffset;
			file_name = reader.ReadString();
			guid = reader.ReadBytes(16);
			hash = reader.ReadBytes(16);
			auto_generated = reader.ReadByte() == 1;
			reader.BaseStream.Position = num;
		}

		internal void WriteData(MyBinaryWriter bw)
		{
			DataOffset = (int)bw.BaseStream.Position;
			bw.Write(file_name);
			if (guid == null)
			{
				guid = Guid.NewGuid().ToByteArray();
				try
				{
					using (FileStream inputStream = new FileStream(file_name, FileMode.Open, FileAccess.Read))
					{
						MD5 mD = MD5.Create();
						hash = mD.ComputeHash(inputStream);
					}
				}
				catch
				{
					hash = new byte[16];
				}
			}
			bw.Write(guid);
			bw.Write(hash);
			bw.Write((byte)(auto_generated ? 1u : 0u));
		}

		internal void Write(BinaryWriter bw)
		{
			bw.Write(Index);
			bw.Write(DataOffset);
		}

		public void SetAutoGenerated()
		{
			if (!creating)
			{
				throw new InvalidOperationException();
			}
			auto_generated = true;
			file.OffsetTable.FileFlags |= OffsetTable.Flags.IsAspxSource;
		}

		public bool CheckChecksum()
		{
			//Discarded unreachable code: IL_004e, IL_0060, IL_006e
			try
			{
				using (FileStream inputStream = new FileStream(file_name, FileMode.Open))
				{
					MD5 mD = MD5.Create();
					byte[] array = mD.ComputeHash(inputStream);
					for (int i = 0; i < 16; i++)
					{
						if (array[i] != hash[i])
						{
							return false;
						}
					}
					return true;
				}
			}
			catch
			{
				return false;
			}
		}

		public override string ToString()
		{
			return string.Format("SourceFileEntry ({0}:{1})", Index, DataOffset);
		}
	}
}
