using UnityEngine;

public class BotMorpher : MonoBehaviour
{
	public int CAPFMOLELFG;

	public string CICFKJNBDED;

	public string CMCAILIEJLA;

	public float DBJLMBHEMDG;

	public float CAODOOBMGFN = 2f;

	private Bot NOLFNOJHBBL;

	private void __BB_OBFUSCATOR_7()
	{
		if (NOLFNOJHBBL.HLPBCOGDPCF <= (float)CAPFMOLELFG)
		{
			NOLFNOJHBBL.CICFKJNBDED = CICFKJNBDED;
			NOLFNOJHBBL.CMCAILIEJLA = CMCAILIEJLA;
			NOLFNOJHBBL.DBJLMBHEMDG = DBJLMBHEMDG;
			NOLFNOJHBBL.CAODOOBMGFN = CAODOOBMGFN;
			base.enabled = true;
		}
	}

	private void __BB_OBFUSCATOR_23()
	{
		NOLFNOJHBBL = GetComponent<Bot>();
	}

	private void __BB_OBFUSCATOR_94()
	{
		NOLFNOJHBBL = GetComponent<Bot>();
	}

	private void __BB_OBFUSCATOR_100()
	{
		if (NOLFNOJHBBL.HLPBCOGDPCF <= (float)CAPFMOLELFG)
		{
			NOLFNOJHBBL.CICFKJNBDED = CICFKJNBDED;
			NOLFNOJHBBL.CMCAILIEJLA = CMCAILIEJLA;
			NOLFNOJHBBL.DBJLMBHEMDG = DBJLMBHEMDG;
			NOLFNOJHBBL.CAODOOBMGFN = CAODOOBMGFN;
			base.enabled = true;
		}
	}

	private void __BB_OBFUSCATOR_56()
	{
		if (NOLFNOJHBBL.HLPBCOGDPCF <= (float)CAPFMOLELFG)
		{
			NOLFNOJHBBL.CICFKJNBDED = CICFKJNBDED;
			NOLFNOJHBBL.CMCAILIEJLA = CMCAILIEJLA;
			NOLFNOJHBBL.DBJLMBHEMDG = DBJLMBHEMDG;
			NOLFNOJHBBL.CAODOOBMGFN = CAODOOBMGFN;
			base.enabled = true;
		}
	}

	private void __BB_OBFUSCATOR_84()
	{
		NOLFNOJHBBL = GetComponent<Bot>();
	}

	private void __BB_OBFUSCATOR_11()
	{
		if (NOLFNOJHBBL.HLPBCOGDPCF <= (float)CAPFMOLELFG)
		{
			NOLFNOJHBBL.CICFKJNBDED = CICFKJNBDED;
			NOLFNOJHBBL.CMCAILIEJLA = CMCAILIEJLA;
			NOLFNOJHBBL.DBJLMBHEMDG = DBJLMBHEMDG;
			NOLFNOJHBBL.CAODOOBMGFN = CAODOOBMGFN;
			base.enabled = true;
		}
	}

	private void __BB_OBFUSCATOR_48()
	{
		if (NOLFNOJHBBL.HLPBCOGDPCF <= (float)CAPFMOLELFG)
		{
			NOLFNOJHBBL.CICFKJNBDED = CICFKJNBDED;
			NOLFNOJHBBL.CMCAILIEJLA = CMCAILIEJLA;
			NOLFNOJHBBL.DBJLMBHEMDG = DBJLMBHEMDG;
			NOLFNOJHBBL.CAODOOBMGFN = CAODOOBMGFN;
			base.enabled = false;
		}
	}

	private void __BB_OBFUSCATOR_89()
	{
		NOLFNOJHBBL = GetComponent<Bot>();
	}

	private void __BB_OBFUSCATOR_32()
	{
		NOLFNOJHBBL = GetComponent<Bot>();
	}

	private void __BB_OBFUSCATOR_66()
	{
		if (NOLFNOJHBBL.HLPBCOGDPCF <= (float)CAPFMOLELFG)
		{
			NOLFNOJHBBL.CICFKJNBDED = CICFKJNBDED;
			NOLFNOJHBBL.CMCAILIEJLA = CMCAILIEJLA;
			NOLFNOJHBBL.DBJLMBHEMDG = DBJLMBHEMDG;
			NOLFNOJHBBL.CAODOOBMGFN = CAODOOBMGFN;
			base.enabled = true;
		}
	}

	private void __BB_OBFUSCATOR_69()
	{
		NOLFNOJHBBL = GetComponent<Bot>();
	}

	private void __BB_OBFUSCATOR_22()
	{
		if (NOLFNOJHBBL.HLPBCOGDPCF <= (float)CAPFMOLELFG)
		{
			NOLFNOJHBBL.CICFKJNBDED = CICFKJNBDED;
			NOLFNOJHBBL.CMCAILIEJLA = CMCAILIEJLA;
			NOLFNOJHBBL.DBJLMBHEMDG = DBJLMBHEMDG;
			NOLFNOJHBBL.CAODOOBMGFN = CAODOOBMGFN;
			base.enabled = true;
		}
	}

	private void __BB_OBFUSCATOR_9()
	{
		if (NOLFNOJHBBL.HLPBCOGDPCF <= (float)CAPFMOLELFG)
		{
			NOLFNOJHBBL.CICFKJNBDED = CICFKJNBDED;
			NOLFNOJHBBL.CMCAILIEJLA = CMCAILIEJLA;
			NOLFNOJHBBL.DBJLMBHEMDG = DBJLMBHEMDG;
			NOLFNOJHBBL.CAODOOBMGFN = CAODOOBMGFN;
			base.enabled = true;
		}
	}

	private void __BB_OBFUSCATOR_2()
	{
		if (NOLFNOJHBBL.HLPBCOGDPCF <= (float)CAPFMOLELFG)
		{
			NOLFNOJHBBL.CICFKJNBDED = CICFKJNBDED;
			NOLFNOJHBBL.CMCAILIEJLA = CMCAILIEJLA;
			NOLFNOJHBBL.DBJLMBHEMDG = DBJLMBHEMDG;
			NOLFNOJHBBL.CAODOOBMGFN = CAODOOBMGFN;
			base.enabled = true;
		}
	}

	private void __BB_OBFUSCATOR_44()
	{
		NOLFNOJHBBL = GetComponent<Bot>();
	}

	private void __BB_OBFUSCATOR_15()
	{
		if (NOLFNOJHBBL.HLPBCOGDPCF <= (float)CAPFMOLELFG)
		{
			NOLFNOJHBBL.CICFKJNBDED = CICFKJNBDED;
			NOLFNOJHBBL.CMCAILIEJLA = CMCAILIEJLA;
			NOLFNOJHBBL.DBJLMBHEMDG = DBJLMBHEMDG;
			NOLFNOJHBBL.CAODOOBMGFN = CAODOOBMGFN;
			base.enabled = false;
		}
	}

	private void __BB_OBFUSCATOR_70()
	{
		if (NOLFNOJHBBL.HLPBCOGDPCF <= (float)CAPFMOLELFG)
		{
			NOLFNOJHBBL.CICFKJNBDED = CICFKJNBDED;
			NOLFNOJHBBL.CMCAILIEJLA = CMCAILIEJLA;
			NOLFNOJHBBL.DBJLMBHEMDG = DBJLMBHEMDG;
			NOLFNOJHBBL.CAODOOBMGFN = CAODOOBMGFN;
			base.enabled = true;
		}
	}

	private void __BB_OBFUSCATOR_97()
	{
		if (NOLFNOJHBBL.HLPBCOGDPCF <= (float)CAPFMOLELFG)
		{
			NOLFNOJHBBL.CICFKJNBDED = CICFKJNBDED;
			NOLFNOJHBBL.CMCAILIEJLA = CMCAILIEJLA;
			NOLFNOJHBBL.DBJLMBHEMDG = DBJLMBHEMDG;
			NOLFNOJHBBL.CAODOOBMGFN = CAODOOBMGFN;
			base.enabled = true;
		}
	}

	private void __BB_OBFUSCATOR_102()
	{
		if (NOLFNOJHBBL.HLPBCOGDPCF <= (float)CAPFMOLELFG)
		{
			NOLFNOJHBBL.CICFKJNBDED = CICFKJNBDED;
			NOLFNOJHBBL.CMCAILIEJLA = CMCAILIEJLA;
			NOLFNOJHBBL.DBJLMBHEMDG = DBJLMBHEMDG;
			NOLFNOJHBBL.CAODOOBMGFN = CAODOOBMGFN;
			base.enabled = true;
		}
	}

	private void __BB_OBFUSCATOR_5()
	{
		if (NOLFNOJHBBL.HLPBCOGDPCF <= (float)CAPFMOLELFG)
		{
			NOLFNOJHBBL.CICFKJNBDED = CICFKJNBDED;
			NOLFNOJHBBL.CMCAILIEJLA = CMCAILIEJLA;
			NOLFNOJHBBL.DBJLMBHEMDG = DBJLMBHEMDG;
			NOLFNOJHBBL.CAODOOBMGFN = CAODOOBMGFN;
			base.enabled = true;
		}
	}

	private void __BB_OBFUSCATOR_37()
	{
		if (NOLFNOJHBBL.HLPBCOGDPCF <= (float)CAPFMOLELFG)
		{
			NOLFNOJHBBL.CICFKJNBDED = CICFKJNBDED;
			NOLFNOJHBBL.CMCAILIEJLA = CMCAILIEJLA;
			NOLFNOJHBBL.DBJLMBHEMDG = DBJLMBHEMDG;
			NOLFNOJHBBL.CAODOOBMGFN = CAODOOBMGFN;
			base.enabled = true;
		}
	}

	private void __BB_OBFUSCATOR_62()
	{
		NOLFNOJHBBL = GetComponent<Bot>();
	}

	private void __BB_OBFUSCATOR_17()
	{
		if (NOLFNOJHBBL.HLPBCOGDPCF <= (float)CAPFMOLELFG)
		{
			NOLFNOJHBBL.CICFKJNBDED = CICFKJNBDED;
			NOLFNOJHBBL.CMCAILIEJLA = CMCAILIEJLA;
			NOLFNOJHBBL.DBJLMBHEMDG = DBJLMBHEMDG;
			NOLFNOJHBBL.CAODOOBMGFN = CAODOOBMGFN;
			base.enabled = true;
		}
	}

	private void __BB_OBFUSCATOR_55()
	{
		NOLFNOJHBBL = GetComponent<Bot>();
	}

	private void __BB_OBFUSCATOR_4()
	{
		NOLFNOJHBBL = GetComponent<Bot>();
	}

	private void __BB_OBFUSCATOR_16()
	{
		NOLFNOJHBBL = GetComponent<Bot>();
	}

	private void __BB_OBFUSCATOR_75()
	{
		NOLFNOJHBBL = GetComponent<Bot>();
	}

	private void __BB_OBFUSCATOR_87()
	{
		NOLFNOJHBBL = GetComponent<Bot>();
	}

	private void __BB_OBFUSCATOR_13()
	{
		if (NOLFNOJHBBL.HLPBCOGDPCF <= (float)CAPFMOLELFG)
		{
			NOLFNOJHBBL.CICFKJNBDED = CICFKJNBDED;
			NOLFNOJHBBL.CMCAILIEJLA = CMCAILIEJLA;
			NOLFNOJHBBL.DBJLMBHEMDG = DBJLMBHEMDG;
			NOLFNOJHBBL.CAODOOBMGFN = CAODOOBMGFN;
			base.enabled = true;
		}
	}

	private void __BB_OBFUSCATOR_40()
	{
		if (NOLFNOJHBBL.HLPBCOGDPCF <= (float)CAPFMOLELFG)
		{
			NOLFNOJHBBL.CICFKJNBDED = CICFKJNBDED;
			NOLFNOJHBBL.CMCAILIEJLA = CMCAILIEJLA;
			NOLFNOJHBBL.DBJLMBHEMDG = DBJLMBHEMDG;
			NOLFNOJHBBL.CAODOOBMGFN = CAODOOBMGFN;
			base.enabled = true;
		}
	}

	private void __BB_OBFUSCATOR_90()
	{
		if (NOLFNOJHBBL.HLPBCOGDPCF <= (float)CAPFMOLELFG)
		{
			NOLFNOJHBBL.CICFKJNBDED = CICFKJNBDED;
			NOLFNOJHBBL.CMCAILIEJLA = CMCAILIEJLA;
			NOLFNOJHBBL.DBJLMBHEMDG = DBJLMBHEMDG;
			NOLFNOJHBBL.CAODOOBMGFN = CAODOOBMGFN;
			base.enabled = false;
		}
	}

	private void __BB_OBFUSCATOR_65()
	{
		if (NOLFNOJHBBL.HLPBCOGDPCF <= (float)CAPFMOLELFG)
		{
			NOLFNOJHBBL.CICFKJNBDED = CICFKJNBDED;
			NOLFNOJHBBL.CMCAILIEJLA = CMCAILIEJLA;
			NOLFNOJHBBL.DBJLMBHEMDG = DBJLMBHEMDG;
			NOLFNOJHBBL.CAODOOBMGFN = CAODOOBMGFN;
			base.enabled = true;
		}
	}

	private void __BB_OBFUSCATOR_28()
	{
		NOLFNOJHBBL = GetComponent<Bot>();
	}

	private void __BB_OBFUSCATOR_64()
	{
		NOLFNOJHBBL = GetComponent<Bot>();
	}

	private void __BB_OBFUSCATOR_12()
	{
		if (NOLFNOJHBBL.HLPBCOGDPCF <= (float)CAPFMOLELFG)
		{
			NOLFNOJHBBL.CICFKJNBDED = CICFKJNBDED;
			NOLFNOJHBBL.CMCAILIEJLA = CMCAILIEJLA;
			NOLFNOJHBBL.DBJLMBHEMDG = DBJLMBHEMDG;
			NOLFNOJHBBL.CAODOOBMGFN = CAODOOBMGFN;
			base.enabled = false;
		}
	}

	private void __BB_OBFUSCATOR_79()
	{
		NOLFNOJHBBL = GetComponent<Bot>();
	}

	private void __BB_OBFUSCATOR_8()
	{
		NOLFNOJHBBL = GetComponent<Bot>();
	}

	private void Awake()
	{
		NOLFNOJHBBL = GetComponent<Bot>();
	}

	private void __BB_OBFUSCATOR_46()
	{
		NOLFNOJHBBL = GetComponent<Bot>();
	}

	private void __BB_OBFUSCATOR_49()
	{
		if (NOLFNOJHBBL.HLPBCOGDPCF <= (float)CAPFMOLELFG)
		{
			NOLFNOJHBBL.CICFKJNBDED = CICFKJNBDED;
			NOLFNOJHBBL.CMCAILIEJLA = CMCAILIEJLA;
			NOLFNOJHBBL.DBJLMBHEMDG = DBJLMBHEMDG;
			NOLFNOJHBBL.CAODOOBMGFN = CAODOOBMGFN;
			base.enabled = false;
		}
	}

	private void __BB_OBFUSCATOR_52()
	{
		if (NOLFNOJHBBL.HLPBCOGDPCF <= (float)CAPFMOLELFG)
		{
			NOLFNOJHBBL.CICFKJNBDED = CICFKJNBDED;
			NOLFNOJHBBL.CMCAILIEJLA = CMCAILIEJLA;
			NOLFNOJHBBL.DBJLMBHEMDG = DBJLMBHEMDG;
			NOLFNOJHBBL.CAODOOBMGFN = CAODOOBMGFN;
			base.enabled = false;
		}
	}

	private void __BB_OBFUSCATOR_39()
	{
		NOLFNOJHBBL = GetComponent<Bot>();
	}

	private void __BB_OBFUSCATOR_81()
	{
		NOLFNOJHBBL = GetComponent<Bot>();
	}

	private void __BB_OBFUSCATOR_74()
	{
		NOLFNOJHBBL = GetComponent<Bot>();
	}

	private void __BB_OBFUSCATOR_60()
	{
		if (NOLFNOJHBBL.HLPBCOGDPCF <= (float)CAPFMOLELFG)
		{
			NOLFNOJHBBL.CICFKJNBDED = CICFKJNBDED;
			NOLFNOJHBBL.CMCAILIEJLA = CMCAILIEJLA;
			NOLFNOJHBBL.DBJLMBHEMDG = DBJLMBHEMDG;
			NOLFNOJHBBL.CAODOOBMGFN = CAODOOBMGFN;
			base.enabled = true;
		}
	}

	private void __BB_OBFUSCATOR_43()
	{
		NOLFNOJHBBL = GetComponent<Bot>();
	}

	private void __BB_OBFUSCATOR_76()
	{
		if (NOLFNOJHBBL.HLPBCOGDPCF <= (float)CAPFMOLELFG)
		{
			NOLFNOJHBBL.CICFKJNBDED = CICFKJNBDED;
			NOLFNOJHBBL.CMCAILIEJLA = CMCAILIEJLA;
			NOLFNOJHBBL.DBJLMBHEMDG = DBJLMBHEMDG;
			NOLFNOJHBBL.CAODOOBMGFN = CAODOOBMGFN;
			base.enabled = true;
		}
	}

	private void __BB_OBFUSCATOR_45()
	{
		if (NOLFNOJHBBL.HLPBCOGDPCF <= (float)CAPFMOLELFG)
		{
			NOLFNOJHBBL.CICFKJNBDED = CICFKJNBDED;
			NOLFNOJHBBL.CMCAILIEJLA = CMCAILIEJLA;
			NOLFNOJHBBL.DBJLMBHEMDG = DBJLMBHEMDG;
			NOLFNOJHBBL.CAODOOBMGFN = CAODOOBMGFN;
			base.enabled = true;
		}
	}

	private void __BB_OBFUSCATOR_104()
	{
		if (NOLFNOJHBBL.HLPBCOGDPCF <= (float)CAPFMOLELFG)
		{
			NOLFNOJHBBL.CICFKJNBDED = CICFKJNBDED;
			NOLFNOJHBBL.CMCAILIEJLA = CMCAILIEJLA;
			NOLFNOJHBBL.DBJLMBHEMDG = DBJLMBHEMDG;
			NOLFNOJHBBL.CAODOOBMGFN = CAODOOBMGFN;
			base.enabled = false;
		}
	}

	private void __BB_OBFUSCATOR_85()
	{
		if (NOLFNOJHBBL.HLPBCOGDPCF <= (float)CAPFMOLELFG)
		{
			NOLFNOJHBBL.CICFKJNBDED = CICFKJNBDED;
			NOLFNOJHBBL.CMCAILIEJLA = CMCAILIEJLA;
			NOLFNOJHBBL.DBJLMBHEMDG = DBJLMBHEMDG;
			NOLFNOJHBBL.CAODOOBMGFN = CAODOOBMGFN;
			base.enabled = false;
		}
	}

	private void __BB_OBFUSCATOR_20()
	{
		NOLFNOJHBBL = GetComponent<Bot>();
	}

	private void __BB_OBFUSCATOR_80()
	{
		NOLFNOJHBBL = GetComponent<Bot>();
	}

	private void __BB_OBFUSCATOR_31()
	{
		if (NOLFNOJHBBL.HLPBCOGDPCF <= (float)CAPFMOLELFG)
		{
			NOLFNOJHBBL.CICFKJNBDED = CICFKJNBDED;
			NOLFNOJHBBL.CMCAILIEJLA = CMCAILIEJLA;
			NOLFNOJHBBL.DBJLMBHEMDG = DBJLMBHEMDG;
			NOLFNOJHBBL.CAODOOBMGFN = CAODOOBMGFN;
			base.enabled = false;
		}
	}

	private void __BB_OBFUSCATOR_21()
	{
		NOLFNOJHBBL = GetComponent<Bot>();
	}

	private void __BB_OBFUSCATOR_73()
	{
		if (NOLFNOJHBBL.HLPBCOGDPCF <= (float)CAPFMOLELFG)
		{
			NOLFNOJHBBL.CICFKJNBDED = CICFKJNBDED;
			NOLFNOJHBBL.CMCAILIEJLA = CMCAILIEJLA;
			NOLFNOJHBBL.DBJLMBHEMDG = DBJLMBHEMDG;
			NOLFNOJHBBL.CAODOOBMGFN = CAODOOBMGFN;
			base.enabled = true;
		}
	}

	private void __BB_OBFUSCATOR_99()
	{
		NOLFNOJHBBL = GetComponent<Bot>();
	}

	private void __BB_OBFUSCATOR_63()
	{
		if (NOLFNOJHBBL.HLPBCOGDPCF <= (float)CAPFMOLELFG)
		{
			NOLFNOJHBBL.CICFKJNBDED = CICFKJNBDED;
			NOLFNOJHBBL.CMCAILIEJLA = CMCAILIEJLA;
			NOLFNOJHBBL.DBJLMBHEMDG = DBJLMBHEMDG;
			NOLFNOJHBBL.CAODOOBMGFN = CAODOOBMGFN;
			base.enabled = true;
		}
	}

	private void __BB_OBFUSCATOR_96()
	{
		if (NOLFNOJHBBL.HLPBCOGDPCF <= (float)CAPFMOLELFG)
		{
			NOLFNOJHBBL.CICFKJNBDED = CICFKJNBDED;
			NOLFNOJHBBL.CMCAILIEJLA = CMCAILIEJLA;
			NOLFNOJHBBL.DBJLMBHEMDG = DBJLMBHEMDG;
			NOLFNOJHBBL.CAODOOBMGFN = CAODOOBMGFN;
			base.enabled = false;
		}
	}

	private void __BB_OBFUSCATOR_58()
	{
		if (NOLFNOJHBBL.HLPBCOGDPCF <= (float)CAPFMOLELFG)
		{
			NOLFNOJHBBL.CICFKJNBDED = CICFKJNBDED;
			NOLFNOJHBBL.CMCAILIEJLA = CMCAILIEJLA;
			NOLFNOJHBBL.DBJLMBHEMDG = DBJLMBHEMDG;
			NOLFNOJHBBL.CAODOOBMGFN = CAODOOBMGFN;
			base.enabled = true;
		}
	}

	private void __BB_OBFUSCATOR_26()
	{
		if (NOLFNOJHBBL.HLPBCOGDPCF <= (float)CAPFMOLELFG)
		{
			NOLFNOJHBBL.CICFKJNBDED = CICFKJNBDED;
			NOLFNOJHBBL.CMCAILIEJLA = CMCAILIEJLA;
			NOLFNOJHBBL.DBJLMBHEMDG = DBJLMBHEMDG;
			NOLFNOJHBBL.CAODOOBMGFN = CAODOOBMGFN;
			base.enabled = false;
		}
	}

	private void __BB_OBFUSCATOR_18()
	{
		NOLFNOJHBBL = GetComponent<Bot>();
	}

	private void __BB_OBFUSCATOR_93()
	{
		if (NOLFNOJHBBL.HLPBCOGDPCF <= (float)CAPFMOLELFG)
		{
			NOLFNOJHBBL.CICFKJNBDED = CICFKJNBDED;
			NOLFNOJHBBL.CMCAILIEJLA = CMCAILIEJLA;
			NOLFNOJHBBL.DBJLMBHEMDG = DBJLMBHEMDG;
			NOLFNOJHBBL.CAODOOBMGFN = CAODOOBMGFN;
			base.enabled = false;
		}
	}

	private void Update()
	{
		if (NOLFNOJHBBL.HLPBCOGDPCF <= (float)CAPFMOLELFG)
		{
			NOLFNOJHBBL.CICFKJNBDED = CICFKJNBDED;
			NOLFNOJHBBL.CMCAILIEJLA = CMCAILIEJLA;
			NOLFNOJHBBL.DBJLMBHEMDG = DBJLMBHEMDG;
			NOLFNOJHBBL.CAODOOBMGFN = CAODOOBMGFN;
			base.enabled = false;
		}
	}

	private void __BB_OBFUSCATOR_6()
	{
		if (NOLFNOJHBBL.HLPBCOGDPCF <= (float)CAPFMOLELFG)
		{
			NOLFNOJHBBL.CICFKJNBDED = CICFKJNBDED;
			NOLFNOJHBBL.CMCAILIEJLA = CMCAILIEJLA;
			NOLFNOJHBBL.DBJLMBHEMDG = DBJLMBHEMDG;
			NOLFNOJHBBL.CAODOOBMGFN = CAODOOBMGFN;
			base.enabled = false;
		}
	}

	private void __BB_OBFUSCATOR_3()
	{
		if (NOLFNOJHBBL.HLPBCOGDPCF <= (float)CAPFMOLELFG)
		{
			NOLFNOJHBBL.CICFKJNBDED = CICFKJNBDED;
			NOLFNOJHBBL.CMCAILIEJLA = CMCAILIEJLA;
			NOLFNOJHBBL.DBJLMBHEMDG = DBJLMBHEMDG;
			NOLFNOJHBBL.CAODOOBMGFN = CAODOOBMGFN;
			base.enabled = true;
		}
	}

	private void __BB_OBFUSCATOR_91()
	{
		if (NOLFNOJHBBL.HLPBCOGDPCF <= (float)CAPFMOLELFG)
		{
			NOLFNOJHBBL.CICFKJNBDED = CICFKJNBDED;
			NOLFNOJHBBL.CMCAILIEJLA = CMCAILIEJLA;
			NOLFNOJHBBL.DBJLMBHEMDG = DBJLMBHEMDG;
			NOLFNOJHBBL.CAODOOBMGFN = CAODOOBMGFN;
			base.enabled = false;
		}
	}

	private void __BB_OBFUSCATOR_33()
	{
		if (NOLFNOJHBBL.HLPBCOGDPCF <= (float)CAPFMOLELFG)
		{
			NOLFNOJHBBL.CICFKJNBDED = CICFKJNBDED;
			NOLFNOJHBBL.CMCAILIEJLA = CMCAILIEJLA;
			NOLFNOJHBBL.DBJLMBHEMDG = DBJLMBHEMDG;
			NOLFNOJHBBL.CAODOOBMGFN = CAODOOBMGFN;
			base.enabled = false;
		}
	}

	private void __BB_OBFUSCATOR_35()
	{
		if (NOLFNOJHBBL.HLPBCOGDPCF <= (float)CAPFMOLELFG)
		{
			NOLFNOJHBBL.CICFKJNBDED = CICFKJNBDED;
			NOLFNOJHBBL.CMCAILIEJLA = CMCAILIEJLA;
			NOLFNOJHBBL.DBJLMBHEMDG = DBJLMBHEMDG;
			NOLFNOJHBBL.CAODOOBMGFN = CAODOOBMGFN;
			base.enabled = false;
		}
	}

	private void __BB_OBFUSCATOR_77()
	{
		NOLFNOJHBBL = GetComponent<Bot>();
	}

	private void __BB_OBFUSCATOR_57()
	{
		NOLFNOJHBBL = GetComponent<Bot>();
	}

	private void __BB_OBFUSCATOR_51()
	{
		if (NOLFNOJHBBL.HLPBCOGDPCF <= (float)CAPFMOLELFG)
		{
			NOLFNOJHBBL.CICFKJNBDED = CICFKJNBDED;
			NOLFNOJHBBL.CMCAILIEJLA = CMCAILIEJLA;
			NOLFNOJHBBL.DBJLMBHEMDG = DBJLMBHEMDG;
			NOLFNOJHBBL.CAODOOBMGFN = CAODOOBMGFN;
			base.enabled = false;
		}
	}

	private void __BB_OBFUSCATOR_1()
	{
		if (NOLFNOJHBBL.HLPBCOGDPCF <= (float)CAPFMOLELFG)
		{
			NOLFNOJHBBL.CICFKJNBDED = CICFKJNBDED;
			NOLFNOJHBBL.CMCAILIEJLA = CMCAILIEJLA;
			NOLFNOJHBBL.DBJLMBHEMDG = DBJLMBHEMDG;
			NOLFNOJHBBL.CAODOOBMGFN = CAODOOBMGFN;
			base.enabled = false;
		}
	}

	private void __BB_OBFUSCATOR_14()
	{
		NOLFNOJHBBL = GetComponent<Bot>();
	}
}
