using UnityEngine;

[RequireComponent(typeof(Detonator))]
[AddComponentMenu("Detonator/Shockwave")]
public class DetonatorShockwave : DetonatorComponent
{
	private float KBGFHOJODBF = 1f;

	private float BNCCIDBIPBF = 0.25f;

	private Vector3 KNEAEEDKCGD = new Vector3(0f, 0f, 0f);

	private Color LNKOBAPEIIM = Color.white;

	private GameObject OPEBENDACBH;

	private DetonatorBurstEmitter OIKIEPLEAEL;

	public Material LPBFFNKMPBF;

	public ParticleRenderMode CJHNCFAGLIG;

	public void __BB_OBFUSCATOR_92()
	{
		OPEBENDACBH.transform.localPosition = Vector3.Scale(BJGOJGBLDMN, new Vector3(EEDMLOPHDJA, EEDMLOPHDJA, EEDMLOPHDJA));
		OIKIEPLEAEL.IOFNOJHNJAJ = IOFNOJHNJAJ;
		OIKIEPLEAEL.LCLHCEHHBNM = LCLHCEHHBNM;
		OIKIEPLEAEL.HEKGFKJHMFJ = LCLHCEHHBNM * 706f;
		OIKIEPLEAEL.FGMDPKFFANG = 389f;
		OIKIEPLEAEL.NCGMMIBMBEL = 1666f;
		OIKIEPLEAEL.HPKOOPBINIH = 309f;
		OIKIEPLEAEL.EKKCIFKDCNC = 200f;
		OIKIEPLEAEL.PACAMLAINIK = new Vector3(389f, 211f, 90f);
		OIKIEPLEAEL.MFAPGCJPFFH = 8f;
		OIKIEPLEAEL.NMPKCAOOHIJ = 1879f;
		OIKIEPLEAEL.EEDMLOPHDJA = EEDMLOPHDJA;
		OIKIEPLEAEL.BHDOLBHLDGC = BHDOLBHLDGC;
		OIKIEPLEAEL.DHMOAEAKEBD = DHMOAEAKEBD;
		OIKIEPLEAEL.CJHNCFAGLIG = CJHNCFAGLIG;
	}

	public void __BB_OBFUSCATOR_65()
	{
		OPEBENDACBH.transform.localPosition = Vector3.Scale(BJGOJGBLDMN, new Vector3(EEDMLOPHDJA, EEDMLOPHDJA, EEDMLOPHDJA));
		OIKIEPLEAEL.IOFNOJHNJAJ = IOFNOJHNJAJ;
		OIKIEPLEAEL.LCLHCEHHBNM = LCLHCEHHBNM;
		OIKIEPLEAEL.HEKGFKJHMFJ = LCLHCEHHBNM * 86f;
		OIKIEPLEAEL.FGMDPKFFANG = 1112f;
		OIKIEPLEAEL.NCGMMIBMBEL = 703f;
		OIKIEPLEAEL.HPKOOPBINIH = 828f;
		OIKIEPLEAEL.EKKCIFKDCNC = 1007f;
		OIKIEPLEAEL.PACAMLAINIK = new Vector3(408f, 4f, 1727f);
		OIKIEPLEAEL.MFAPGCJPFFH = 1638f;
		OIKIEPLEAEL.NMPKCAOOHIJ = 126f;
		OIKIEPLEAEL.EEDMLOPHDJA = EEDMLOPHDJA;
		OIKIEPLEAEL.BHDOLBHLDGC = BHDOLBHLDGC;
		OIKIEPLEAEL.DHMOAEAKEBD = DHMOAEAKEBD;
		OIKIEPLEAEL.CJHNCFAGLIG = CJHNCFAGLIG;
	}

	public void __BB_OBFUSCATOR_94(bool PHDOMKDEDMO)
	{
		if (!LPBFFNKMPBF || PHDOMKDEDMO)
		{
			LPBFFNKMPBF = MyDetonator().LPBFFNKMPBF;
		}
	}

	public void __BB_OBFUSCATOR_15(bool PHDOMKDEDMO)
	{
		if (!LPBFFNKMPBF || PHDOMKDEDMO)
		{
			LPBFFNKMPBF = MyDetonator().LPBFFNKMPBF;
		}
	}

	public void __BB_OBFUSCATOR_35()
	{
		OPEBENDACBH.transform.localPosition = Vector3.Scale(BJGOJGBLDMN, new Vector3(EEDMLOPHDJA, EEDMLOPHDJA, EEDMLOPHDJA));
		OIKIEPLEAEL.IOFNOJHNJAJ = IOFNOJHNJAJ;
		OIKIEPLEAEL.LCLHCEHHBNM = LCLHCEHHBNM;
		OIKIEPLEAEL.HEKGFKJHMFJ = LCLHCEHHBNM * 564f;
		OIKIEPLEAEL.FGMDPKFFANG = 432f;
		OIKIEPLEAEL.NCGMMIBMBEL = 1357f;
		OIKIEPLEAEL.HPKOOPBINIH = 1744f;
		OIKIEPLEAEL.EKKCIFKDCNC = 449f;
		OIKIEPLEAEL.PACAMLAINIK = new Vector3(23f, 460f, 189f);
		OIKIEPLEAEL.MFAPGCJPFFH = 1614f;
		OIKIEPLEAEL.NMPKCAOOHIJ = 359f;
		OIKIEPLEAEL.EEDMLOPHDJA = EEDMLOPHDJA;
		OIKIEPLEAEL.BHDOLBHLDGC = BHDOLBHLDGC;
		OIKIEPLEAEL.DHMOAEAKEBD = DHMOAEAKEBD;
		OIKIEPLEAEL.CJHNCFAGLIG = CJHNCFAGLIG;
	}

	public void __BB_OBFUSCATOR_102()
	{
		OPEBENDACBH = new GameObject("_Distortion");
		OIKIEPLEAEL = OPEBENDACBH.AddComponent<DetonatorBurstEmitter>();
		OPEBENDACBH.transform.parent = base.transform;
		OPEBENDACBH.transform.localRotation = Quaternion.identity;
		OPEBENDACBH.transform.localPosition = BJGOJGBLDMN;
		OIKIEPLEAEL.MFOLDHOAMNN = LPBFFNKMPBF;
		OIKIEPLEAEL.HBNEHNACADK = true;
		OIKIEPLEAEL.MJHAPHHGGHI = MyDetonator().MJHAPHHGGHI;
	}

	public virtual void __BB_OBFUSCATOR_106()
	{
		__BB_OBFUSCATOR_110(true);
		__BB_OBFUSCATOR_114();
	}

	public void __BB_OBFUSCATOR_62(bool PHDOMKDEDMO)
	{
		if (!LPBFFNKMPBF || PHDOMKDEDMO)
		{
			LPBFFNKMPBF = MyDetonator().LPBFFNKMPBF;
		}
	}

	public void __BB_OBFUSCATOR_60(bool PHDOMKDEDMO)
	{
		if (!LPBFFNKMPBF || PHDOMKDEDMO)
		{
			LPBFFNKMPBF = MyDetonator().LPBFFNKMPBF;
		}
	}

	public virtual void __BB_OBFUSCATOR_73()
	{
		__BB_OBFUSCATOR_0(true);
		__BB_OBFUSCATOR_10();
	}

	public void __BB_OBFUSCATOR_42()
	{
		OPEBENDACBH = new GameObject("A player has been caught");
		OIKIEPLEAEL = OPEBENDACBH.AddComponent<DetonatorBurstEmitter>();
		OPEBENDACBH.transform.parent = base.transform;
		OPEBENDACBH.transform.localRotation = Quaternion.identity;
		OPEBENDACBH.transform.localPosition = BJGOJGBLDMN;
		OIKIEPLEAEL.MFOLDHOAMNN = LPBFFNKMPBF;
		OIKIEPLEAEL.HBNEHNACADK = true;
		OIKIEPLEAEL.MJHAPHHGGHI = MyDetonator().MJHAPHHGGHI;
	}

	public virtual void __BB_OBFUSCATOR_26()
	{
		__BB_OBFUSCATOR_108(false);
		__BB_OBFUSCATOR_114();
	}

	public void __BB_OBFUSCATOR_61(bool PHDOMKDEDMO)
	{
		if (!LPBFFNKMPBF || PHDOMKDEDMO)
		{
			LPBFFNKMPBF = MyDetonator().LPBFFNKMPBF;
		}
	}

	public void __BB_OBFUSCATOR_18()
	{
		OPEBENDACBH.transform.localPosition = Vector3.Scale(BJGOJGBLDMN, new Vector3(EEDMLOPHDJA, EEDMLOPHDJA, EEDMLOPHDJA));
		OIKIEPLEAEL.IOFNOJHNJAJ = IOFNOJHNJAJ;
		OIKIEPLEAEL.LCLHCEHHBNM = LCLHCEHHBNM;
		OIKIEPLEAEL.HEKGFKJHMFJ = LCLHCEHHBNM * 1880f;
		OIKIEPLEAEL.FGMDPKFFANG = 182f;
		OIKIEPLEAEL.NCGMMIBMBEL = 1788f;
		OIKIEPLEAEL.HPKOOPBINIH = 1101f;
		OIKIEPLEAEL.EKKCIFKDCNC = 895f;
		OIKIEPLEAEL.PACAMLAINIK = new Vector3(121f, 1584f, 971f);
		OIKIEPLEAEL.MFAPGCJPFFH = 1521f;
		OIKIEPLEAEL.NMPKCAOOHIJ = 1074f;
		OIKIEPLEAEL.EEDMLOPHDJA = EEDMLOPHDJA;
		OIKIEPLEAEL.BHDOLBHLDGC = BHDOLBHLDGC;
		OIKIEPLEAEL.DHMOAEAKEBD = DHMOAEAKEBD;
		OIKIEPLEAEL.CJHNCFAGLIG = CJHNCFAGLIG;
	}

	public void __BB_OBFUSCATOR_44()
	{
		__BB_OBFUSCATOR_50(false);
		GMAIEMJKMJD = false;
		EEDMLOPHDJA = KBGFHOJODBF;
		LCLHCEHHBNM = BNCCIDBIPBF;
		BHDOLBHLDGC = 1113f;
		DHMOAEAKEBD = 151f;
		IOFNOJHNJAJ = LNKOBAPEIIM;
		PACAMLAINIK = KNEAEEDKCGD;
	}

	public virtual void __BB_OBFUSCATOR_29()
	{
		if (GMAIEMJKMJD)
		{
			__BB_OBFUSCATOR_34();
			OIKIEPLEAEL.Explode();
		}
	}

	public void __BB_OBFUSCATOR_50(bool PHDOMKDEDMO)
	{
		if (!LPBFFNKMPBF || PHDOMKDEDMO)
		{
			LPBFFNKMPBF = MyDetonator().LPBFFNKMPBF;
		}
	}

	public virtual void __BB_OBFUSCATOR_16()
	{
		__BB_OBFUSCATOR_110(true);
		__BB_OBFUSCATOR_70();
	}

	public void __BB_OBFUSCATOR_103()
	{
		OPEBENDACBH.transform.localPosition = Vector3.Scale(BJGOJGBLDMN, new Vector3(EEDMLOPHDJA, EEDMLOPHDJA, EEDMLOPHDJA));
		OIKIEPLEAEL.IOFNOJHNJAJ = IOFNOJHNJAJ;
		OIKIEPLEAEL.LCLHCEHHBNM = LCLHCEHHBNM;
		OIKIEPLEAEL.HEKGFKJHMFJ = LCLHCEHHBNM * 1388f;
		OIKIEPLEAEL.FGMDPKFFANG = 937f;
		OIKIEPLEAEL.NCGMMIBMBEL = 1497f;
		OIKIEPLEAEL.HPKOOPBINIH = 1377f;
		OIKIEPLEAEL.EKKCIFKDCNC = 255f;
		OIKIEPLEAEL.PACAMLAINIK = new Vector3(1316f, 1459f, 858f);
		OIKIEPLEAEL.MFAPGCJPFFH = 1856f;
		OIKIEPLEAEL.NMPKCAOOHIJ = 1377f;
		OIKIEPLEAEL.EEDMLOPHDJA = EEDMLOPHDJA;
		OIKIEPLEAEL.BHDOLBHLDGC = BHDOLBHLDGC;
		OIKIEPLEAEL.DHMOAEAKEBD = DHMOAEAKEBD;
		OIKIEPLEAEL.CJHNCFAGLIG = CJHNCFAGLIG;
	}

	public void __BB_OBFUSCATOR_115()
	{
		__BB_OBFUSCATOR_111(true);
		GMAIEMJKMJD = true;
		EEDMLOPHDJA = KBGFHOJODBF;
		LCLHCEHHBNM = BNCCIDBIPBF;
		BHDOLBHLDGC = 1614f;
		DHMOAEAKEBD = 1705f;
		IOFNOJHNJAJ = LNKOBAPEIIM;
		PACAMLAINIK = KNEAEEDKCGD;
	}

	public void __BB_OBFUSCATOR_22()
	{
		OPEBENDACBH = new GameObject("_TimeX");
		OIKIEPLEAEL = OPEBENDACBH.AddComponent<DetonatorBurstEmitter>();
		OPEBENDACBH.transform.parent = base.transform;
		OPEBENDACBH.transform.localRotation = Quaternion.identity;
		OPEBENDACBH.transform.localPosition = BJGOJGBLDMN;
		OIKIEPLEAEL.MFOLDHOAMNN = LPBFFNKMPBF;
		OIKIEPLEAEL.HBNEHNACADK = false;
		OIKIEPLEAEL.MJHAPHHGGHI = MyDetonator().MJHAPHHGGHI;
	}

	public void __BB_OBFUSCATOR_68(bool PHDOMKDEDMO)
	{
		if (!LPBFFNKMPBF || PHDOMKDEDMO)
		{
			LPBFFNKMPBF = MyDetonator().LPBFFNKMPBF;
		}
	}

	public virtual void __BB_OBFUSCATOR_88()
	{
		if (GMAIEMJKMJD)
		{
			__BB_OBFUSCATOR_58();
			OIKIEPLEAEL.Explode();
		}
	}

	public virtual void __BB_OBFUSCATOR_53()
	{
		__BB_OBFUSCATOR_111(false);
		__BB_OBFUSCATOR_113();
	}

	public virtual void __BB_OBFUSCATOR_67()
	{
		if (GMAIEMJKMJD)
		{
			__BB_OBFUSCATOR_6();
			OIKIEPLEAEL.Explode();
		}
	}

	public void __BB_OBFUSCATOR_40()
	{
		OPEBENDACBH = new GameObject("Diffuse");
		OIKIEPLEAEL = OPEBENDACBH.AddComponent<DetonatorBurstEmitter>();
		OPEBENDACBH.transform.parent = base.transform;
		OPEBENDACBH.transform.localRotation = Quaternion.identity;
		OPEBENDACBH.transform.localPosition = BJGOJGBLDMN;
		OIKIEPLEAEL.MFOLDHOAMNN = LPBFFNKMPBF;
		OIKIEPLEAEL.HBNEHNACADK = false;
		OIKIEPLEAEL.MJHAPHHGGHI = MyDetonator().MJHAPHHGGHI;
	}

	public virtual void __BB_OBFUSCATOR_121()
	{
		if (GMAIEMJKMJD)
		{
			__BB_OBFUSCATOR_58();
			OIKIEPLEAEL.Explode();
		}
	}

	public void __BB_OBFUSCATOR_8()
	{
		__BB_OBFUSCATOR_68(false);
		GMAIEMJKMJD = false;
		EEDMLOPHDJA = KBGFHOJODBF;
		LCLHCEHHBNM = BNCCIDBIPBF;
		BHDOLBHLDGC = 1597f;
		DHMOAEAKEBD = 319f;
		IOFNOJHNJAJ = LNKOBAPEIIM;
		PACAMLAINIK = KNEAEEDKCGD;
	}

	public virtual void __BB_OBFUSCATOR_82()
	{
		if (GMAIEMJKMJD)
		{
			__BB_OBFUSCATOR_103();
			OIKIEPLEAEL.Explode();
		}
	}

	public void __BB_OBFUSCATOR_63()
	{
		__BB_OBFUSCATOR_60(false);
		GMAIEMJKMJD = false;
		EEDMLOPHDJA = KBGFHOJODBF;
		LCLHCEHHBNM = BNCCIDBIPBF;
		BHDOLBHLDGC = 1819f;
		DHMOAEAKEBD = 1260f;
		IOFNOJHNJAJ = LNKOBAPEIIM;
		PACAMLAINIK = KNEAEEDKCGD;
	}

	public void __BB_OBFUSCATOR_3()
	{
		__BB_OBFUSCATOR_17(false);
		GMAIEMJKMJD = false;
		EEDMLOPHDJA = KBGFHOJODBF;
		LCLHCEHHBNM = BNCCIDBIPBF;
		BHDOLBHLDGC = 683f;
		DHMOAEAKEBD = 282f;
		IOFNOJHNJAJ = LNKOBAPEIIM;
		PACAMLAINIK = KNEAEEDKCGD;
	}

	public void __BB_OBFUSCATOR_55()
	{
		OPEBENDACBH.transform.localPosition = Vector3.Scale(BJGOJGBLDMN, new Vector3(EEDMLOPHDJA, EEDMLOPHDJA, EEDMLOPHDJA));
		OIKIEPLEAEL.IOFNOJHNJAJ = IOFNOJHNJAJ;
		OIKIEPLEAEL.LCLHCEHHBNM = LCLHCEHHBNM;
		OIKIEPLEAEL.HEKGFKJHMFJ = LCLHCEHHBNM * 383f;
		OIKIEPLEAEL.FGMDPKFFANG = 284f;
		OIKIEPLEAEL.NCGMMIBMBEL = 1119f;
		OIKIEPLEAEL.HPKOOPBINIH = 877f;
		OIKIEPLEAEL.EKKCIFKDCNC = 1622f;
		OIKIEPLEAEL.PACAMLAINIK = new Vector3(353f, 792f, 152f);
		OIKIEPLEAEL.MFAPGCJPFFH = 1586f;
		OIKIEPLEAEL.NMPKCAOOHIJ = 979f;
		OIKIEPLEAEL.EEDMLOPHDJA = EEDMLOPHDJA;
		OIKIEPLEAEL.BHDOLBHLDGC = BHDOLBHLDGC;
		OIKIEPLEAEL.DHMOAEAKEBD = DHMOAEAKEBD;
		OIKIEPLEAEL.CJHNCFAGLIG = CJHNCFAGLIG;
	}

	public override void Init()
	{
		FillMaterials(false);
		BuildShockwave();
	}

	public void Reset()
	{
		FillMaterials(true);
		GMAIEMJKMJD = true;
		EEDMLOPHDJA = KBGFHOJODBF;
		LCLHCEHHBNM = BNCCIDBIPBF;
		BHDOLBHLDGC = 0f;
		DHMOAEAKEBD = 0f;
		IOFNOJHNJAJ = LNKOBAPEIIM;
		PACAMLAINIK = KNEAEEDKCGD;
	}

	public void __BB_OBFUSCATOR_9()
	{
		OPEBENDACBH = new GameObject("Mouse");
		OIKIEPLEAEL = OPEBENDACBH.AddComponent<DetonatorBurstEmitter>();
		OPEBENDACBH.transform.parent = base.transform;
		OPEBENDACBH.transform.localRotation = Quaternion.identity;
		OPEBENDACBH.transform.localPosition = BJGOJGBLDMN;
		OIKIEPLEAEL.MFOLDHOAMNN = LPBFFNKMPBF;
		OIKIEPLEAEL.HBNEHNACADK = false;
		OIKIEPLEAEL.MJHAPHHGGHI = MyDetonator().MJHAPHHGGHI;
	}

	public void __BB_OBFUSCATOR_107()
	{
		OPEBENDACBH.transform.localPosition = Vector3.Scale(BJGOJGBLDMN, new Vector3(EEDMLOPHDJA, EEDMLOPHDJA, EEDMLOPHDJA));
		OIKIEPLEAEL.IOFNOJHNJAJ = IOFNOJHNJAJ;
		OIKIEPLEAEL.LCLHCEHHBNM = LCLHCEHHBNM;
		OIKIEPLEAEL.HEKGFKJHMFJ = LCLHCEHHBNM * 1854f;
		OIKIEPLEAEL.FGMDPKFFANG = 441f;
		OIKIEPLEAEL.NCGMMIBMBEL = 953f;
		OIKIEPLEAEL.HPKOOPBINIH = 1303f;
		OIKIEPLEAEL.EKKCIFKDCNC = 153f;
		OIKIEPLEAEL.PACAMLAINIK = new Vector3(541f, 1936f, 554f);
		OIKIEPLEAEL.MFAPGCJPFFH = 74f;
		OIKIEPLEAEL.NMPKCAOOHIJ = 849f;
		OIKIEPLEAEL.EEDMLOPHDJA = EEDMLOPHDJA;
		OIKIEPLEAEL.BHDOLBHLDGC = BHDOLBHLDGC;
		OIKIEPLEAEL.DHMOAEAKEBD = DHMOAEAKEBD;
		OIKIEPLEAEL.CJHNCFAGLIG = CJHNCFAGLIG;
	}

	public void __BB_OBFUSCATOR_34()
	{
		OPEBENDACBH.transform.localPosition = Vector3.Scale(BJGOJGBLDMN, new Vector3(EEDMLOPHDJA, EEDMLOPHDJA, EEDMLOPHDJA));
		OIKIEPLEAEL.IOFNOJHNJAJ = IOFNOJHNJAJ;
		OIKIEPLEAEL.LCLHCEHHBNM = LCLHCEHHBNM;
		OIKIEPLEAEL.HEKGFKJHMFJ = LCLHCEHHBNM * 389f;
		OIKIEPLEAEL.FGMDPKFFANG = 1728f;
		OIKIEPLEAEL.NCGMMIBMBEL = 1244f;
		OIKIEPLEAEL.HPKOOPBINIH = 1139f;
		OIKIEPLEAEL.EKKCIFKDCNC = 1770f;
		OIKIEPLEAEL.PACAMLAINIK = new Vector3(562f, 1449f, 1088f);
		OIKIEPLEAEL.MFAPGCJPFFH = 1663f;
		OIKIEPLEAEL.NMPKCAOOHIJ = 1052f;
		OIKIEPLEAEL.EEDMLOPHDJA = EEDMLOPHDJA;
		OIKIEPLEAEL.BHDOLBHLDGC = BHDOLBHLDGC;
		OIKIEPLEAEL.DHMOAEAKEBD = DHMOAEAKEBD;
		OIKIEPLEAEL.CJHNCFAGLIG = CJHNCFAGLIG;
	}

	public virtual void __BB_OBFUSCATOR_97()
	{
		__BB_OBFUSCATOR_50(false);
		__BB_OBFUSCATOR_102();
	}

	public void __BB_OBFUSCATOR_0(bool PHDOMKDEDMO)
	{
		if (!LPBFFNKMPBF || PHDOMKDEDMO)
		{
			LPBFFNKMPBF = MyDetonator().LPBFFNKMPBF;
		}
	}

	public virtual void __BB_OBFUSCATOR_101()
	{
		__BB_OBFUSCATOR_15(true);
		__BB_OBFUSCATOR_102();
	}

	public virtual void __BB_OBFUSCATOR_99()
	{
		__BB_OBFUSCATOR_94(true);
		__BB_OBFUSCATOR_114();
	}

	public virtual void __BB_OBFUSCATOR_64()
	{
		__BB_OBFUSCATOR_62(false);
		__BB_OBFUSCATOR_10();
	}

	public void BuildShockwave()
	{
		OPEBENDACBH = new GameObject("Shockwave");
		OIKIEPLEAEL = OPEBENDACBH.AddComponent<DetonatorBurstEmitter>();
		OPEBENDACBH.transform.parent = base.transform;
		OPEBENDACBH.transform.localRotation = Quaternion.identity;
		OPEBENDACBH.transform.localPosition = BJGOJGBLDMN;
		OIKIEPLEAEL.MFOLDHOAMNN = LPBFFNKMPBF;
		OIKIEPLEAEL.HBNEHNACADK = false;
		OIKIEPLEAEL.MJHAPHHGGHI = MyDetonator().MJHAPHHGGHI;
	}

	public virtual void __BB_OBFUSCATOR_118()
	{
		__BB_OBFUSCATOR_71(true);
		__BB_OBFUSCATOR_42();
	}

	public virtual void __BB_OBFUSCATOR_84()
	{
		if (GMAIEMJKMJD)
		{
			__BB_OBFUSCATOR_89();
			OIKIEPLEAEL.Explode();
		}
	}

	public void __BB_OBFUSCATOR_27()
	{
		OPEBENDACBH = new GameObject("_ScreenResolution");
		OIKIEPLEAEL = OPEBENDACBH.AddComponent<DetonatorBurstEmitter>();
		OPEBENDACBH.transform.parent = base.transform;
		OPEBENDACBH.transform.localRotation = Quaternion.identity;
		OPEBENDACBH.transform.localPosition = BJGOJGBLDMN;
		OIKIEPLEAEL.MFOLDHOAMNN = LPBFFNKMPBF;
		OIKIEPLEAEL.HBNEHNACADK = true;
		OIKIEPLEAEL.MJHAPHHGGHI = MyDetonator().MJHAPHHGGHI;
	}

	public void __BB_OBFUSCATOR_58()
	{
		OPEBENDACBH.transform.localPosition = Vector3.Scale(BJGOJGBLDMN, new Vector3(EEDMLOPHDJA, EEDMLOPHDJA, EEDMLOPHDJA));
		OIKIEPLEAEL.IOFNOJHNJAJ = IOFNOJHNJAJ;
		OIKIEPLEAEL.LCLHCEHHBNM = LCLHCEHHBNM;
		OIKIEPLEAEL.HEKGFKJHMFJ = LCLHCEHHBNM * 959f;
		OIKIEPLEAEL.FGMDPKFFANG = 1116f;
		OIKIEPLEAEL.NCGMMIBMBEL = 1848f;
		OIKIEPLEAEL.HPKOOPBINIH = 13f;
		OIKIEPLEAEL.EKKCIFKDCNC = 673f;
		OIKIEPLEAEL.PACAMLAINIK = new Vector3(915f, 1355f, 1609f);
		OIKIEPLEAEL.MFAPGCJPFFH = 1678f;
		OIKIEPLEAEL.NMPKCAOOHIJ = 710f;
		OIKIEPLEAEL.EEDMLOPHDJA = EEDMLOPHDJA;
		OIKIEPLEAEL.BHDOLBHLDGC = BHDOLBHLDGC;
		OIKIEPLEAEL.DHMOAEAKEBD = DHMOAEAKEBD;
		OIKIEPLEAEL.CJHNCFAGLIG = CJHNCFAGLIG;
	}

	public virtual void __BB_OBFUSCATOR_117()
	{
		__BB_OBFUSCATOR_62(true);
		__BB_OBFUSCATOR_114();
	}

	public void __BB_OBFUSCATOR_54()
	{
		OPEBENDACBH = new GameObject("5");
		OIKIEPLEAEL = OPEBENDACBH.AddComponent<DetonatorBurstEmitter>();
		OPEBENDACBH.transform.parent = base.transform;
		OPEBENDACBH.transform.localRotation = Quaternion.identity;
		OPEBENDACBH.transform.localPosition = BJGOJGBLDMN;
		OIKIEPLEAEL.MFOLDHOAMNN = LPBFFNKMPBF;
		OIKIEPLEAEL.HBNEHNACADK = true;
		OIKIEPLEAEL.MJHAPHHGGHI = MyDetonator().MJHAPHHGGHI;
	}

	public void __BB_OBFUSCATOR_70()
	{
		OPEBENDACBH = new GameObject("{0:n6},{1:n6},{2:n6},{3:n6}");
		OIKIEPLEAEL = OPEBENDACBH.AddComponent<DetonatorBurstEmitter>();
		OPEBENDACBH.transform.parent = base.transform;
		OPEBENDACBH.transform.localRotation = Quaternion.identity;
		OPEBENDACBH.transform.localPosition = BJGOJGBLDMN;
		OIKIEPLEAEL.MFOLDHOAMNN = LPBFFNKMPBF;
		OIKIEPLEAEL.HBNEHNACADK = true;
		OIKIEPLEAEL.MJHAPHHGGHI = MyDetonator().MJHAPHHGGHI;
	}

	public virtual void __BB_OBFUSCATOR_100()
	{
		if (GMAIEMJKMJD)
		{
			__BB_OBFUSCATOR_89();
			OIKIEPLEAEL.Explode();
		}
	}

	public virtual void __BB_OBFUSCATOR_104()
	{
		__BB_OBFUSCATOR_36(false);
		__BB_OBFUSCATOR_96();
	}

	public virtual void __BB_OBFUSCATOR_69()
	{
		if (GMAIEMJKMJD)
		{
			__BB_OBFUSCATOR_58();
			OIKIEPLEAEL.Explode();
		}
	}

	public void __BB_OBFUSCATOR_59()
	{
		OPEBENDACBH.transform.localPosition = Vector3.Scale(BJGOJGBLDMN, new Vector3(EEDMLOPHDJA, EEDMLOPHDJA, EEDMLOPHDJA));
		OIKIEPLEAEL.IOFNOJHNJAJ = IOFNOJHNJAJ;
		OIKIEPLEAEL.LCLHCEHHBNM = LCLHCEHHBNM;
		OIKIEPLEAEL.HEKGFKJHMFJ = LCLHCEHHBNM * 36f;
		OIKIEPLEAEL.FGMDPKFFANG = 269f;
		OIKIEPLEAEL.NCGMMIBMBEL = 1248f;
		OIKIEPLEAEL.HPKOOPBINIH = 391f;
		OIKIEPLEAEL.EKKCIFKDCNC = 619f;
		OIKIEPLEAEL.PACAMLAINIK = new Vector3(1642f, 1609f, 1070f);
		OIKIEPLEAEL.MFAPGCJPFFH = 101f;
		OIKIEPLEAEL.NMPKCAOOHIJ = 936f;
		OIKIEPLEAEL.EEDMLOPHDJA = EEDMLOPHDJA;
		OIKIEPLEAEL.BHDOLBHLDGC = BHDOLBHLDGC;
		OIKIEPLEAEL.DHMOAEAKEBD = DHMOAEAKEBD;
		OIKIEPLEAEL.CJHNCFAGLIG = CJHNCFAGLIG;
	}

	public virtual void __BB_OBFUSCATOR_83()
	{
		__BB_OBFUSCATOR_116(false);
		__BB_OBFUSCATOR_27();
	}

	public void __BB_OBFUSCATOR_38()
	{
		OPEBENDACBH.transform.localPosition = Vector3.Scale(BJGOJGBLDMN, new Vector3(EEDMLOPHDJA, EEDMLOPHDJA, EEDMLOPHDJA));
		OIKIEPLEAEL.IOFNOJHNJAJ = IOFNOJHNJAJ;
		OIKIEPLEAEL.LCLHCEHHBNM = LCLHCEHHBNM;
		OIKIEPLEAEL.HEKGFKJHMFJ = LCLHCEHHBNM * 505f;
		OIKIEPLEAEL.FGMDPKFFANG = 1870f;
		OIKIEPLEAEL.NCGMMIBMBEL = 1222f;
		OIKIEPLEAEL.HPKOOPBINIH = 916f;
		OIKIEPLEAEL.EKKCIFKDCNC = 859f;
		OIKIEPLEAEL.PACAMLAINIK = new Vector3(1513f, 916f, 759f);
		OIKIEPLEAEL.MFAPGCJPFFH = 1258f;
		OIKIEPLEAEL.NMPKCAOOHIJ = 1878f;
		OIKIEPLEAEL.EEDMLOPHDJA = EEDMLOPHDJA;
		OIKIEPLEAEL.BHDOLBHLDGC = BHDOLBHLDGC;
		OIKIEPLEAEL.DHMOAEAKEBD = DHMOAEAKEBD;
		OIKIEPLEAEL.CJHNCFAGLIG = CJHNCFAGLIG;
	}

	public void __BB_OBFUSCATOR_74()
	{
		__BB_OBFUSCATOR_5(true);
		GMAIEMJKMJD = false;
		EEDMLOPHDJA = KBGFHOJODBF;
		LCLHCEHHBNM = BNCCIDBIPBF;
		BHDOLBHLDGC = 1471f;
		DHMOAEAKEBD = 277f;
		IOFNOJHNJAJ = LNKOBAPEIIM;
		PACAMLAINIK = KNEAEEDKCGD;
	}

	public virtual void __BB_OBFUSCATOR_109()
	{
		if (GMAIEMJKMJD)
		{
			__BB_OBFUSCATOR_59();
			OIKIEPLEAEL.Explode();
		}
	}

	public virtual void __BB_OBFUSCATOR_4()
	{
		if (GMAIEMJKMJD)
		{
			__BB_OBFUSCATOR_91();
			OIKIEPLEAEL.Explode();
		}
	}

	public void __BB_OBFUSCATOR_71(bool PHDOMKDEDMO)
	{
		if (!LPBFFNKMPBF || PHDOMKDEDMO)
		{
			LPBFFNKMPBF = MyDetonator().LPBFFNKMPBF;
		}
	}

	public virtual void __BB_OBFUSCATOR_75()
	{
		if (GMAIEMJKMJD)
		{
			__BB_OBFUSCATOR_65();
			OIKIEPLEAEL.Explode();
		}
	}

	public void __BB_OBFUSCATOR_7()
	{
		__BB_OBFUSCATOR_71(false);
		GMAIEMJKMJD = false;
		EEDMLOPHDJA = KBGFHOJODBF;
		LCLHCEHHBNM = BNCCIDBIPBF;
		BHDOLBHLDGC = 1103f;
		DHMOAEAKEBD = 1020f;
		IOFNOJHNJAJ = LNKOBAPEIIM;
		PACAMLAINIK = KNEAEEDKCGD;
	}

	public void __BB_OBFUSCATOR_57()
	{
		__BB_OBFUSCATOR_61(true);
		GMAIEMJKMJD = false;
		EEDMLOPHDJA = KBGFHOJODBF;
		LCLHCEHHBNM = BNCCIDBIPBF;
		BHDOLBHLDGC = 44f;
		DHMOAEAKEBD = 360f;
		IOFNOJHNJAJ = LNKOBAPEIIM;
		PACAMLAINIK = KNEAEEDKCGD;
	}

	public void __BB_OBFUSCATOR_96()
	{
		OPEBENDACBH = new GameObject("EnableHelper");
		OIKIEPLEAEL = OPEBENDACBH.AddComponent<DetonatorBurstEmitter>();
		OPEBENDACBH.transform.parent = base.transform;
		OPEBENDACBH.transform.localRotation = Quaternion.identity;
		OPEBENDACBH.transform.localPosition = BJGOJGBLDMN;
		OIKIEPLEAEL.MFOLDHOAMNN = LPBFFNKMPBF;
		OIKIEPLEAEL.HBNEHNACADK = false;
		OIKIEPLEAEL.MJHAPHHGGHI = MyDetonator().MJHAPHHGGHI;
	}

	public void __BB_OBFUSCATOR_113()
	{
		OPEBENDACBH = new GameObject("_Color_B");
		OIKIEPLEAEL = OPEBENDACBH.AddComponent<DetonatorBurstEmitter>();
		OPEBENDACBH.transform.parent = base.transform;
		OPEBENDACBH.transform.localRotation = Quaternion.identity;
		OPEBENDACBH.transform.localPosition = BJGOJGBLDMN;
		OIKIEPLEAEL.MFOLDHOAMNN = LPBFFNKMPBF;
		OIKIEPLEAEL.HBNEHNACADK = false;
		OIKIEPLEAEL.MJHAPHHGGHI = MyDetonator().MJHAPHHGGHI;
	}

	public void __BB_OBFUSCATOR_116(bool PHDOMKDEDMO)
	{
		if (!LPBFFNKMPBF || PHDOMKDEDMO)
		{
			LPBFFNKMPBF = MyDetonator().LPBFFNKMPBF;
		}
	}

	public virtual void __BB_OBFUSCATOR_25()
	{
		__BB_OBFUSCATOR_17(false);
		__BB_OBFUSCATOR_9();
	}

	public void __BB_OBFUSCATOR_78()
	{
		OPEBENDACBH = new GameObject("_Blue_C");
		OIKIEPLEAEL = OPEBENDACBH.AddComponent<DetonatorBurstEmitter>();
		OPEBENDACBH.transform.parent = base.transform;
		OPEBENDACBH.transform.localRotation = Quaternion.identity;
		OPEBENDACBH.transform.localPosition = BJGOJGBLDMN;
		OIKIEPLEAEL.MFOLDHOAMNN = LPBFFNKMPBF;
		OIKIEPLEAEL.HBNEHNACADK = true;
		OIKIEPLEAEL.MJHAPHHGGHI = MyDetonator().MJHAPHHGGHI;
	}

	public virtual void __BB_OBFUSCATOR_66()
	{
		if (GMAIEMJKMJD)
		{
			__BB_OBFUSCATOR_38();
			OIKIEPLEAEL.Explode();
		}
	}

	public void __BB_OBFUSCATOR_10()
	{
		OPEBENDACBH = new GameObject("Team A");
		OIKIEPLEAEL = OPEBENDACBH.AddComponent<DetonatorBurstEmitter>();
		OPEBENDACBH.transform.parent = base.transform;
		OPEBENDACBH.transform.localRotation = Quaternion.identity;
		OPEBENDACBH.transform.localPosition = BJGOJGBLDMN;
		OIKIEPLEAEL.MFOLDHOAMNN = LPBFFNKMPBF;
		OIKIEPLEAEL.HBNEHNACADK = true;
		OIKIEPLEAEL.MJHAPHHGGHI = MyDetonator().MJHAPHHGGHI;
	}

	public void __BB_OBFUSCATOR_111(bool PHDOMKDEDMO)
	{
		if (!LPBFFNKMPBF || PHDOMKDEDMO)
		{
			LPBFFNKMPBF = MyDetonator().LPBFFNKMPBF;
		}
	}

	public void __BB_OBFUSCATOR_48()
	{
		__BB_OBFUSCATOR_5(true);
		GMAIEMJKMJD = true;
		EEDMLOPHDJA = KBGFHOJODBF;
		LCLHCEHHBNM = BNCCIDBIPBF;
		BHDOLBHLDGC = 377f;
		DHMOAEAKEBD = 416f;
		IOFNOJHNJAJ = LNKOBAPEIIM;
		PACAMLAINIK = KNEAEEDKCGD;
	}

	public void __BB_OBFUSCATOR_91()
	{
		OPEBENDACBH.transform.localPosition = Vector3.Scale(BJGOJGBLDMN, new Vector3(EEDMLOPHDJA, EEDMLOPHDJA, EEDMLOPHDJA));
		OIKIEPLEAEL.IOFNOJHNJAJ = IOFNOJHNJAJ;
		OIKIEPLEAEL.LCLHCEHHBNM = LCLHCEHHBNM;
		OIKIEPLEAEL.HEKGFKJHMFJ = LCLHCEHHBNM * 1793f;
		OIKIEPLEAEL.FGMDPKFFANG = 41f;
		OIKIEPLEAEL.NCGMMIBMBEL = 1036f;
		OIKIEPLEAEL.HPKOOPBINIH = 1435f;
		OIKIEPLEAEL.EKKCIFKDCNC = 65f;
		OIKIEPLEAEL.PACAMLAINIK = new Vector3(623f, 1639f, 38f);
		OIKIEPLEAEL.MFAPGCJPFFH = 735f;
		OIKIEPLEAEL.NMPKCAOOHIJ = 272f;
		OIKIEPLEAEL.EEDMLOPHDJA = EEDMLOPHDJA;
		OIKIEPLEAEL.BHDOLBHLDGC = BHDOLBHLDGC;
		OIKIEPLEAEL.DHMOAEAKEBD = DHMOAEAKEBD;
		OIKIEPLEAEL.CJHNCFAGLIG = CJHNCFAGLIG;
	}

	public virtual void __BB_OBFUSCATOR_28()
	{
		__BB_OBFUSCATOR_61(true);
		__BB_OBFUSCATOR_113();
	}

	public void __BB_OBFUSCATOR_12()
	{
		__BB_OBFUSCATOR_60(false);
		GMAIEMJKMJD = true;
		EEDMLOPHDJA = KBGFHOJODBF;
		LCLHCEHHBNM = BNCCIDBIPBF;
		BHDOLBHLDGC = 1370f;
		DHMOAEAKEBD = 790f;
		IOFNOJHNJAJ = LNKOBAPEIIM;
		PACAMLAINIK = KNEAEEDKCGD;
	}

	public void __BB_OBFUSCATOR_46()
	{
		OPEBENDACBH.transform.localPosition = Vector3.Scale(BJGOJGBLDMN, new Vector3(EEDMLOPHDJA, EEDMLOPHDJA, EEDMLOPHDJA));
		OIKIEPLEAEL.IOFNOJHNJAJ = IOFNOJHNJAJ;
		OIKIEPLEAEL.LCLHCEHHBNM = LCLHCEHHBNM;
		OIKIEPLEAEL.HEKGFKJHMFJ = LCLHCEHHBNM * 646f;
		OIKIEPLEAEL.FGMDPKFFANG = 894f;
		OIKIEPLEAEL.NCGMMIBMBEL = 1599f;
		OIKIEPLEAEL.HPKOOPBINIH = 466f;
		OIKIEPLEAEL.EKKCIFKDCNC = 56f;
		OIKIEPLEAEL.PACAMLAINIK = new Vector3(629f, 76f, 366f);
		OIKIEPLEAEL.MFAPGCJPFFH = 1847f;
		OIKIEPLEAEL.NMPKCAOOHIJ = 921f;
		OIKIEPLEAEL.EEDMLOPHDJA = EEDMLOPHDJA;
		OIKIEPLEAEL.BHDOLBHLDGC = BHDOLBHLDGC;
		OIKIEPLEAEL.DHMOAEAKEBD = DHMOAEAKEBD;
		OIKIEPLEAEL.CJHNCFAGLIG = CJHNCFAGLIG;
	}

	public virtual void __BB_OBFUSCATOR_21()
	{
		if (GMAIEMJKMJD)
		{
			__BB_OBFUSCATOR_18();
			OIKIEPLEAEL.Explode();
		}
	}

	public void __BB_OBFUSCATOR_108(bool PHDOMKDEDMO)
	{
		if (!LPBFFNKMPBF || PHDOMKDEDMO)
		{
			LPBFFNKMPBF = MyDetonator().LPBFFNKMPBF;
		}
	}

	public void __BB_OBFUSCATOR_19()
	{
		__BB_OBFUSCATOR_0(false);
		GMAIEMJKMJD = true;
		EEDMLOPHDJA = KBGFHOJODBF;
		LCLHCEHHBNM = BNCCIDBIPBF;
		BHDOLBHLDGC = 1892f;
		DHMOAEAKEBD = 832f;
		IOFNOJHNJAJ = LNKOBAPEIIM;
		PACAMLAINIK = KNEAEEDKCGD;
	}

	public virtual void __BB_OBFUSCATOR_112()
	{
		__BB_OBFUSCATOR_94(true);
		BuildShockwave();
	}

	public void __BB_OBFUSCATOR_20()
	{
		OPEBENDACBH.transform.localPosition = Vector3.Scale(BJGOJGBLDMN, new Vector3(EEDMLOPHDJA, EEDMLOPHDJA, EEDMLOPHDJA));
		OIKIEPLEAEL.IOFNOJHNJAJ = IOFNOJHNJAJ;
		OIKIEPLEAEL.LCLHCEHHBNM = LCLHCEHHBNM;
		OIKIEPLEAEL.HEKGFKJHMFJ = LCLHCEHHBNM * 206f;
		OIKIEPLEAEL.FGMDPKFFANG = 169f;
		OIKIEPLEAEL.NCGMMIBMBEL = 423f;
		OIKIEPLEAEL.HPKOOPBINIH = 1351f;
		OIKIEPLEAEL.EKKCIFKDCNC = 1427f;
		OIKIEPLEAEL.PACAMLAINIK = new Vector3(664f, 862f, 1501f);
		OIKIEPLEAEL.MFAPGCJPFFH = 1471f;
		OIKIEPLEAEL.NMPKCAOOHIJ = 355f;
		OIKIEPLEAEL.EEDMLOPHDJA = EEDMLOPHDJA;
		OIKIEPLEAEL.BHDOLBHLDGC = BHDOLBHLDGC;
		OIKIEPLEAEL.DHMOAEAKEBD = DHMOAEAKEBD;
		OIKIEPLEAEL.CJHNCFAGLIG = CJHNCFAGLIG;
	}

	public void __BB_OBFUSCATOR_6()
	{
		OPEBENDACBH.transform.localPosition = Vector3.Scale(BJGOJGBLDMN, new Vector3(EEDMLOPHDJA, EEDMLOPHDJA, EEDMLOPHDJA));
		OIKIEPLEAEL.IOFNOJHNJAJ = IOFNOJHNJAJ;
		OIKIEPLEAEL.LCLHCEHHBNM = LCLHCEHHBNM;
		OIKIEPLEAEL.HEKGFKJHMFJ = LCLHCEHHBNM * 45f;
		OIKIEPLEAEL.FGMDPKFFANG = 589f;
		OIKIEPLEAEL.NCGMMIBMBEL = 285f;
		OIKIEPLEAEL.HPKOOPBINIH = 1363f;
		OIKIEPLEAEL.EKKCIFKDCNC = 56f;
		OIKIEPLEAEL.PACAMLAINIK = new Vector3(1873f, 857f, 578f);
		OIKIEPLEAEL.MFAPGCJPFFH = 487f;
		OIKIEPLEAEL.NMPKCAOOHIJ = 414f;
		OIKIEPLEAEL.EEDMLOPHDJA = EEDMLOPHDJA;
		OIKIEPLEAEL.BHDOLBHLDGC = BHDOLBHLDGC;
		OIKIEPLEAEL.DHMOAEAKEBD = DHMOAEAKEBD;
		OIKIEPLEAEL.CJHNCFAGLIG = CJHNCFAGLIG;
	}

	public void __BB_OBFUSCATOR_17(bool PHDOMKDEDMO)
	{
		if (!LPBFFNKMPBF || PHDOMKDEDMO)
		{
			LPBFFNKMPBF = MyDetonator().LPBFFNKMPBF;
		}
	}

	public void UpdateShockwave()
	{
		OPEBENDACBH.transform.localPosition = Vector3.Scale(BJGOJGBLDMN, new Vector3(EEDMLOPHDJA, EEDMLOPHDJA, EEDMLOPHDJA));
		OIKIEPLEAEL.IOFNOJHNJAJ = IOFNOJHNJAJ;
		OIKIEPLEAEL.LCLHCEHHBNM = LCLHCEHHBNM;
		OIKIEPLEAEL.HEKGFKJHMFJ = LCLHCEHHBNM * 0.1f;
		OIKIEPLEAEL.FGMDPKFFANG = 1f;
		OIKIEPLEAEL.NCGMMIBMBEL = 1f;
		OIKIEPLEAEL.HPKOOPBINIH = 25f;
		OIKIEPLEAEL.EKKCIFKDCNC = 0f;
		OIKIEPLEAEL.PACAMLAINIK = new Vector3(0f, 0f, 0f);
		OIKIEPLEAEL.MFAPGCJPFFH = 0f;
		OIKIEPLEAEL.NMPKCAOOHIJ = 202f;
		OIKIEPLEAEL.EEDMLOPHDJA = EEDMLOPHDJA;
		OIKIEPLEAEL.BHDOLBHLDGC = BHDOLBHLDGC;
		OIKIEPLEAEL.DHMOAEAKEBD = DHMOAEAKEBD;
		OIKIEPLEAEL.CJHNCFAGLIG = CJHNCFAGLIG;
	}

	public void FillMaterials(bool PHDOMKDEDMO)
	{
		if (!LPBFFNKMPBF || PHDOMKDEDMO)
		{
			LPBFFNKMPBF = MyDetonator().LPBFFNKMPBF;
		}
	}

	public void __BB_OBFUSCATOR_119()
	{
		__BB_OBFUSCATOR_36(true);
		GMAIEMJKMJD = false;
		EEDMLOPHDJA = KBGFHOJODBF;
		LCLHCEHHBNM = BNCCIDBIPBF;
		BHDOLBHLDGC = 946f;
		DHMOAEAKEBD = 318f;
		IOFNOJHNJAJ = LNKOBAPEIIM;
		PACAMLAINIK = KNEAEEDKCGD;
	}

	public void __BB_OBFUSCATOR_36(bool PHDOMKDEDMO)
	{
		if (!LPBFFNKMPBF || PHDOMKDEDMO)
		{
			LPBFFNKMPBF = MyDetonator().LPBFFNKMPBF;
		}
	}

	public virtual void __BB_OBFUSCATOR_24()
	{
		if (GMAIEMJKMJD)
		{
			__BB_OBFUSCATOR_92();
			OIKIEPLEAEL.Explode();
		}
	}

	public void __BB_OBFUSCATOR_39()
	{
		__BB_OBFUSCATOR_111(true);
		GMAIEMJKMJD = false;
		EEDMLOPHDJA = KBGFHOJODBF;
		LCLHCEHHBNM = BNCCIDBIPBF;
		BHDOLBHLDGC = 489f;
		DHMOAEAKEBD = 800f;
		IOFNOJHNJAJ = LNKOBAPEIIM;
		PACAMLAINIK = KNEAEEDKCGD;
	}

	public virtual void __BB_OBFUSCATOR_81()
	{
		__BB_OBFUSCATOR_0(false);
		__BB_OBFUSCATOR_113();
	}

	public void __BB_OBFUSCATOR_89()
	{
		OPEBENDACBH.transform.localPosition = Vector3.Scale(BJGOJGBLDMN, new Vector3(EEDMLOPHDJA, EEDMLOPHDJA, EEDMLOPHDJA));
		OIKIEPLEAEL.IOFNOJHNJAJ = IOFNOJHNJAJ;
		OIKIEPLEAEL.LCLHCEHHBNM = LCLHCEHHBNM;
		OIKIEPLEAEL.HEKGFKJHMFJ = LCLHCEHHBNM * 1068f;
		OIKIEPLEAEL.FGMDPKFFANG = 1065f;
		OIKIEPLEAEL.NCGMMIBMBEL = 1911f;
		OIKIEPLEAEL.HPKOOPBINIH = 327f;
		OIKIEPLEAEL.EKKCIFKDCNC = 1973f;
		OIKIEPLEAEL.PACAMLAINIK = new Vector3(328f, 367f, 450f);
		OIKIEPLEAEL.MFAPGCJPFFH = 362f;
		OIKIEPLEAEL.NMPKCAOOHIJ = 321f;
		OIKIEPLEAEL.EEDMLOPHDJA = EEDMLOPHDJA;
		OIKIEPLEAEL.BHDOLBHLDGC = BHDOLBHLDGC;
		OIKIEPLEAEL.DHMOAEAKEBD = DHMOAEAKEBD;
		OIKIEPLEAEL.CJHNCFAGLIG = CJHNCFAGLIG;
	}

	public virtual void __BB_OBFUSCATOR_33()
	{
		__BB_OBFUSCATOR_61(true);
		__BB_OBFUSCATOR_114();
	}

	public void __BB_OBFUSCATOR_120()
	{
		OPEBENDACBH.transform.localPosition = Vector3.Scale(BJGOJGBLDMN, new Vector3(EEDMLOPHDJA, EEDMLOPHDJA, EEDMLOPHDJA));
		OIKIEPLEAEL.IOFNOJHNJAJ = IOFNOJHNJAJ;
		OIKIEPLEAEL.LCLHCEHHBNM = LCLHCEHHBNM;
		OIKIEPLEAEL.HEKGFKJHMFJ = LCLHCEHHBNM * 1500f;
		OIKIEPLEAEL.FGMDPKFFANG = 1264f;
		OIKIEPLEAEL.NCGMMIBMBEL = 1992f;
		OIKIEPLEAEL.HPKOOPBINIH = 932f;
		OIKIEPLEAEL.EKKCIFKDCNC = 1221f;
		OIKIEPLEAEL.PACAMLAINIK = new Vector3(218f, 80f, 1711f);
		OIKIEPLEAEL.MFAPGCJPFFH = 1819f;
		OIKIEPLEAEL.NMPKCAOOHIJ = 1901f;
		OIKIEPLEAEL.EEDMLOPHDJA = EEDMLOPHDJA;
		OIKIEPLEAEL.BHDOLBHLDGC = BHDOLBHLDGC;
		OIKIEPLEAEL.DHMOAEAKEBD = DHMOAEAKEBD;
		OIKIEPLEAEL.CJHNCFAGLIG = CJHNCFAGLIG;
	}

	public override void Explode()
	{
		if (GMAIEMJKMJD)
		{
			UpdateShockwave();
			OIKIEPLEAEL.Explode();
		}
	}

	public virtual void __BB_OBFUSCATOR_51()
	{
		__BB_OBFUSCATOR_108(true);
		__BB_OBFUSCATOR_78();
	}

	public void __BB_OBFUSCATOR_87(bool PHDOMKDEDMO)
	{
		if (!LPBFFNKMPBF || PHDOMKDEDMO)
		{
			LPBFFNKMPBF = MyDetonator().LPBFFNKMPBF;
		}
	}

	public virtual void __BB_OBFUSCATOR_86()
	{
		if (GMAIEMJKMJD)
		{
			__BB_OBFUSCATOR_6();
			OIKIEPLEAEL.Explode();
		}
	}

	public void __BB_OBFUSCATOR_93()
	{
		__BB_OBFUSCATOR_61(true);
		GMAIEMJKMJD = false;
		EEDMLOPHDJA = KBGFHOJODBF;
		LCLHCEHHBNM = BNCCIDBIPBF;
		BHDOLBHLDGC = 1554f;
		DHMOAEAKEBD = 1147f;
		IOFNOJHNJAJ = LNKOBAPEIIM;
		PACAMLAINIK = KNEAEEDKCGD;
	}

	public void __BB_OBFUSCATOR_23(bool PHDOMKDEDMO)
	{
		if (!LPBFFNKMPBF || PHDOMKDEDMO)
		{
			LPBFFNKMPBF = MyDetonator().LPBFFNKMPBF;
		}
	}

	public virtual void __BB_OBFUSCATOR_30()
	{
		if (GMAIEMJKMJD)
		{
			__BB_OBFUSCATOR_90();
			OIKIEPLEAEL.Explode();
		}
	}

	public void __BB_OBFUSCATOR_45()
	{
		OPEBENDACBH = new GameObject("_TimeX");
		OIKIEPLEAEL = OPEBENDACBH.AddComponent<DetonatorBurstEmitter>();
		OPEBENDACBH.transform.parent = base.transform;
		OPEBENDACBH.transform.localRotation = Quaternion.identity;
		OPEBENDACBH.transform.localPosition = BJGOJGBLDMN;
		OIKIEPLEAEL.MFOLDHOAMNN = LPBFFNKMPBF;
		OIKIEPLEAEL.HBNEHNACADK = false;
		OIKIEPLEAEL.MJHAPHHGGHI = MyDetonator().MJHAPHHGGHI;
	}

	public void __BB_OBFUSCATOR_5(bool PHDOMKDEDMO)
	{
		if (!LPBFFNKMPBF || PHDOMKDEDMO)
		{
			LPBFFNKMPBF = MyDetonator().LPBFFNKMPBF;
		}
	}

	public virtual void __BB_OBFUSCATOR_56()
	{
		if (GMAIEMJKMJD)
		{
			__BB_OBFUSCATOR_65();
			OIKIEPLEAEL.Explode();
		}
	}

	public void __BB_OBFUSCATOR_90()
	{
		OPEBENDACBH.transform.localPosition = Vector3.Scale(BJGOJGBLDMN, new Vector3(EEDMLOPHDJA, EEDMLOPHDJA, EEDMLOPHDJA));
		OIKIEPLEAEL.IOFNOJHNJAJ = IOFNOJHNJAJ;
		OIKIEPLEAEL.LCLHCEHHBNM = LCLHCEHHBNM;
		OIKIEPLEAEL.HEKGFKJHMFJ = LCLHCEHHBNM * 24f;
		OIKIEPLEAEL.FGMDPKFFANG = 232f;
		OIKIEPLEAEL.NCGMMIBMBEL = 230f;
		OIKIEPLEAEL.HPKOOPBINIH = 1107f;
		OIKIEPLEAEL.EKKCIFKDCNC = 1710f;
		OIKIEPLEAEL.PACAMLAINIK = new Vector3(1946f, 1116f, 1069f);
		OIKIEPLEAEL.MFAPGCJPFFH = 646f;
		OIKIEPLEAEL.NMPKCAOOHIJ = 1766f;
		OIKIEPLEAEL.EEDMLOPHDJA = EEDMLOPHDJA;
		OIKIEPLEAEL.BHDOLBHLDGC = BHDOLBHLDGC;
		OIKIEPLEAEL.DHMOAEAKEBD = DHMOAEAKEBD;
		OIKIEPLEAEL.CJHNCFAGLIG = CJHNCFAGLIG;
	}

	public virtual void __BB_OBFUSCATOR_85()
	{
		if (GMAIEMJKMJD)
		{
			__BB_OBFUSCATOR_18();
			OIKIEPLEAEL.Explode();
		}
	}

	public void __BB_OBFUSCATOR_110(bool PHDOMKDEDMO)
	{
		if (!LPBFFNKMPBF || PHDOMKDEDMO)
		{
			LPBFFNKMPBF = MyDetonator().LPBFFNKMPBF;
		}
	}

	public virtual void __BB_OBFUSCATOR_77()
	{
		__BB_OBFUSCATOR_110(false);
		__BB_OBFUSCATOR_40();
	}

	public virtual void __BB_OBFUSCATOR_79()
	{
		__BB_OBFUSCATOR_110(false);
		__BB_OBFUSCATOR_22();
	}

	public virtual void __BB_OBFUSCATOR_52()
	{
		__BB_OBFUSCATOR_94(true);
		__BB_OBFUSCATOR_78();
	}

	public virtual void __BB_OBFUSCATOR_2()
	{
		if (GMAIEMJKMJD)
		{
			__BB_OBFUSCATOR_18();
			OIKIEPLEAEL.Explode();
		}
	}

	public void __BB_OBFUSCATOR_114()
	{
		OPEBENDACBH = new GameObject("ArmsURL");
		OIKIEPLEAEL = OPEBENDACBH.AddComponent<DetonatorBurstEmitter>();
		OPEBENDACBH.transform.parent = base.transform;
		OPEBENDACBH.transform.localRotation = Quaternion.identity;
		OPEBENDACBH.transform.localPosition = BJGOJGBLDMN;
		OIKIEPLEAEL.MFOLDHOAMNN = LPBFFNKMPBF;
		OIKIEPLEAEL.HBNEHNACADK = false;
		OIKIEPLEAEL.MJHAPHHGGHI = MyDetonator().MJHAPHHGGHI;
	}
}
