using UnityEngine;

[RequireComponent(typeof(Detonator))]
public class DetonatorCloudRing : DetonatorComponent
{
	private float KBGFHOJODBF = 1f;

	private float BNCCIDBIPBF = 5f;

	private Vector3 KNEAEEDKCGD = new Vector3(155f, 5f, 155f);

	private Color LNKOBAPEIIM = Color.white;

	private Vector3 KPHKKDEGEPE = new Vector3(0.162f, 2.56f, 0f);

	private GameObject GHPMJMMPALM;

	private DetonatorBurstEmitter NDOBFGBHEKD;

	public Material BGPJFHJBAAF;

	public void __BB_OBFUSCATOR_72()
	{
		GHPMJMMPALM.transform.localPosition = Vector3.Scale(BJGOJGBLDMN, new Vector3(EEDMLOPHDJA, EEDMLOPHDJA, EEDMLOPHDJA));
		NDOBFGBHEKD.IOFNOJHNJAJ = IOFNOJHNJAJ;
		NDOBFGBHEKD.LCLHCEHHBNM = LCLHCEHHBNM;
		NDOBFGBHEKD.HEKGFKJHMFJ = LCLHCEHHBNM / 789f;
		NDOBFGBHEKD.FGMDPKFFANG = (int)(NCGMMIBMBEL * 1947f);
		NDOBFGBHEKD.HPKOOPBINIH = 338f;
		NDOBFGBHEKD.EKKCIFKDCNC = 1387f;
		NDOBFGBHEKD.PACAMLAINIK = PACAMLAINIK;
		NDOBFGBHEKD.MFAPGCJPFFH = 14f;
		NDOBFGBHEKD.EEDMLOPHDJA = EEDMLOPHDJA;
		NDOBFGBHEKD.ICPDBNNPACO = ICPDBNNPACO;
		NDOBFGBHEKD.BHDOLBHLDGC = BHDOLBHLDGC;
		NDOBFGBHEKD.DHMOAEAKEBD = DHMOAEAKEBD;
		Color color = Color.Lerp(IOFNOJHNJAJ, new Color(1107f, 1802f, 1702f, 34f), 1099f);
		Color color2 = new Color(1311f, 1567f, 1771f, 171f);
		Color color3 = new Color(1601f, 1775f, 1305f, 349f);
		Color color4 = new Color(845f, 1133f, 1628f, 8f);
		NDOBFGBHEKD.CJFAMIBMHGK[0] = color;
		NDOBFGBHEKD.CJFAMIBMHGK[0] = color2;
		NDOBFGBHEKD.CJFAMIBMHGK[8] = color2;
		NDOBFGBHEKD.CJFAMIBMHGK[3] = color3;
		NDOBFGBHEKD.CJFAMIBMHGK[7] = color4;
	}

	public void __BB_OBFUSCATOR_116()
	{
		__BB_OBFUSCATOR_51(true);
		GMAIEMJKMJD = true;
		EEDMLOPHDJA = KBGFHOJODBF;
		LCLHCEHHBNM = BNCCIDBIPBF;
		BHDOLBHLDGC = 1648f;
		DHMOAEAKEBD = 1069f;
		IOFNOJHNJAJ = LNKOBAPEIIM;
		PACAMLAINIK = KNEAEEDKCGD;
		ICPDBNNPACO = KPHKKDEGEPE;
	}

	public void __BB_OBFUSCATOR_58()
	{
		GHPMJMMPALM.transform.localPosition = Vector3.Scale(BJGOJGBLDMN, new Vector3(EEDMLOPHDJA, EEDMLOPHDJA, EEDMLOPHDJA));
		NDOBFGBHEKD.IOFNOJHNJAJ = IOFNOJHNJAJ;
		NDOBFGBHEKD.LCLHCEHHBNM = LCLHCEHHBNM;
		NDOBFGBHEKD.HEKGFKJHMFJ = LCLHCEHHBNM / 791f;
		NDOBFGBHEKD.FGMDPKFFANG = (int)(NCGMMIBMBEL * 1408f);
		NDOBFGBHEKD.HPKOOPBINIH = 1559f;
		NDOBFGBHEKD.EKKCIFKDCNC = 565f;
		NDOBFGBHEKD.PACAMLAINIK = PACAMLAINIK;
		NDOBFGBHEKD.MFAPGCJPFFH = 1659f;
		NDOBFGBHEKD.EEDMLOPHDJA = EEDMLOPHDJA;
		NDOBFGBHEKD.ICPDBNNPACO = ICPDBNNPACO;
		NDOBFGBHEKD.BHDOLBHLDGC = BHDOLBHLDGC;
		NDOBFGBHEKD.DHMOAEAKEBD = DHMOAEAKEBD;
		Color color = Color.Lerp(IOFNOJHNJAJ, new Color(1589f, 99f, 828f, 718f), 46f);
		Color color2 = new Color(1191f, 1363f, 275f, 1589f);
		Color color3 = new Color(528f, 0f, 1219f, 1343f);
		Color color4 = new Color(954f, 1093f, 506f, 1821f);
		NDOBFGBHEKD.CJFAMIBMHGK[0] = color;
		NDOBFGBHEKD.CJFAMIBMHGK[0] = color2;
		NDOBFGBHEKD.CJFAMIBMHGK[3] = color2;
		NDOBFGBHEKD.CJFAMIBMHGK[7] = color3;
		NDOBFGBHEKD.CJFAMIBMHGK[7] = color4;
	}

	public void __BB_OBFUSCATOR_87()
	{
		GHPMJMMPALM = new GameObject("_Distance");
		NDOBFGBHEKD = GHPMJMMPALM.AddComponent<DetonatorBurstEmitter>();
		GHPMJMMPALM.transform.parent = base.transform;
		GHPMJMMPALM.transform.localPosition = BJGOJGBLDMN;
		NDOBFGBHEKD.MFOLDHOAMNN = BGPJFHJBAAF;
		NDOBFGBHEKD.AIELAFCIBBM = true;
	}

	public void FillMaterials(bool PHDOMKDEDMO)
	{
		if (!BGPJFHJBAAF || PHDOMKDEDMO)
		{
			BGPJFHJBAAF = MyDetonator().KDNNLMHFKOJ;
		}
	}

	public void __BB_OBFUSCATOR_105()
	{
		__BB_OBFUSCATOR_101(false);
		GMAIEMJKMJD = false;
		EEDMLOPHDJA = KBGFHOJODBF;
		LCLHCEHHBNM = BNCCIDBIPBF;
		BHDOLBHLDGC = 785f;
		DHMOAEAKEBD = 1656f;
		IOFNOJHNJAJ = LNKOBAPEIIM;
		PACAMLAINIK = KNEAEEDKCGD;
		ICPDBNNPACO = KPHKKDEGEPE;
	}

	public virtual void __BB_OBFUSCATOR_22()
	{
		__BB_OBFUSCATOR_59(true);
		__BB_OBFUSCATOR_120();
	}

	public void __BB_OBFUSCATOR_42()
	{
		GHPMJMMPALM.transform.localPosition = Vector3.Scale(BJGOJGBLDMN, new Vector3(EEDMLOPHDJA, EEDMLOPHDJA, EEDMLOPHDJA));
		NDOBFGBHEKD.IOFNOJHNJAJ = IOFNOJHNJAJ;
		NDOBFGBHEKD.LCLHCEHHBNM = LCLHCEHHBNM;
		NDOBFGBHEKD.HEKGFKJHMFJ = LCLHCEHHBNM / 252f;
		NDOBFGBHEKD.FGMDPKFFANG = (int)(NCGMMIBMBEL * 1298f);
		NDOBFGBHEKD.HPKOOPBINIH = 268f;
		NDOBFGBHEKD.EKKCIFKDCNC = 1738f;
		NDOBFGBHEKD.PACAMLAINIK = PACAMLAINIK;
		NDOBFGBHEKD.MFAPGCJPFFH = 1293f;
		NDOBFGBHEKD.EEDMLOPHDJA = EEDMLOPHDJA;
		NDOBFGBHEKD.ICPDBNNPACO = ICPDBNNPACO;
		NDOBFGBHEKD.BHDOLBHLDGC = BHDOLBHLDGC;
		NDOBFGBHEKD.DHMOAEAKEBD = DHMOAEAKEBD;
		Color color = Color.Lerp(IOFNOJHNJAJ, new Color(1389f, 1988f, 1050f, 484f), 1958f);
		Color color2 = new Color(1354f, 420f, 1209f, 1176f);
		Color color3 = new Color(1357f, 495f, 1492f, 591f);
		Color color4 = new Color(1511f, 714f, 1166f, 1688f);
		NDOBFGBHEKD.CJFAMIBMHGK[1] = color;
		NDOBFGBHEKD.CJFAMIBMHGK[0] = color2;
		NDOBFGBHEKD.CJFAMIBMHGK[0] = color2;
		NDOBFGBHEKD.CJFAMIBMHGK[1] = color3;
		NDOBFGBHEKD.CJFAMIBMHGK[5] = color4;
	}

	public void BuildCloudRing()
	{
		GHPMJMMPALM = new GameObject("CloudRing");
		NDOBFGBHEKD = GHPMJMMPALM.AddComponent<DetonatorBurstEmitter>();
		GHPMJMMPALM.transform.parent = base.transform;
		GHPMJMMPALM.transform.localPosition = BJGOJGBLDMN;
		NDOBFGBHEKD.MFOLDHOAMNN = BGPJFHJBAAF;
		NDOBFGBHEKD.AIELAFCIBBM = true;
	}

	public void __BB_OBFUSCATOR_61()
	{
		GHPMJMMPALM = new GameObject("Blue");
		NDOBFGBHEKD = GHPMJMMPALM.AddComponent<DetonatorBurstEmitter>();
		GHPMJMMPALM.transform.parent = base.transform;
		GHPMJMMPALM.transform.localPosition = BJGOJGBLDMN;
		NDOBFGBHEKD.MFOLDHOAMNN = BGPJFHJBAAF;
		NDOBFGBHEKD.AIELAFCIBBM = true;
	}

	public void __BB_OBFUSCATOR_18()
	{
		__BB_OBFUSCATOR_51(true);
		GMAIEMJKMJD = false;
		EEDMLOPHDJA = KBGFHOJODBF;
		LCLHCEHHBNM = BNCCIDBIPBF;
		BHDOLBHLDGC = 1055f;
		DHMOAEAKEBD = 418f;
		IOFNOJHNJAJ = LNKOBAPEIIM;
		PACAMLAINIK = KNEAEEDKCGD;
		ICPDBNNPACO = KPHKKDEGEPE;
	}

	public virtual void __BB_OBFUSCATOR_94()
	{
		if (GMAIEMJKMJD)
		{
			__BB_OBFUSCATOR_91();
			NDOBFGBHEKD.Explode();
		}
	}

	public void __BB_OBFUSCATOR_92()
	{
		__BB_OBFUSCATOR_96(true);
		GMAIEMJKMJD = false;
		EEDMLOPHDJA = KBGFHOJODBF;
		LCLHCEHHBNM = BNCCIDBIPBF;
		BHDOLBHLDGC = 1439f;
		DHMOAEAKEBD = 569f;
		IOFNOJHNJAJ = LNKOBAPEIIM;
		PACAMLAINIK = KNEAEEDKCGD;
		ICPDBNNPACO = KPHKKDEGEPE;
	}

	public virtual void __BB_OBFUSCATOR_108()
	{
		if (GMAIEMJKMJD)
		{
			__BB_OBFUSCATOR_26();
			NDOBFGBHEKD.Explode();
		}
	}

	public void __BB_OBFUSCATOR_52()
	{
		GHPMJMMPALM = new GameObject("_ScreenResolution");
		NDOBFGBHEKD = GHPMJMMPALM.AddComponent<DetonatorBurstEmitter>();
		GHPMJMMPALM.transform.parent = base.transform;
		GHPMJMMPALM.transform.localPosition = BJGOJGBLDMN;
		NDOBFGBHEKD.MFOLDHOAMNN = BGPJFHJBAAF;
		NDOBFGBHEKD.AIELAFCIBBM = false;
	}

	public void __BB_OBFUSCATOR_12()
	{
		GHPMJMMPALM.transform.localPosition = Vector3.Scale(BJGOJGBLDMN, new Vector3(EEDMLOPHDJA, EEDMLOPHDJA, EEDMLOPHDJA));
		NDOBFGBHEKD.IOFNOJHNJAJ = IOFNOJHNJAJ;
		NDOBFGBHEKD.LCLHCEHHBNM = LCLHCEHHBNM;
		NDOBFGBHEKD.HEKGFKJHMFJ = LCLHCEHHBNM / 279f;
		NDOBFGBHEKD.FGMDPKFFANG = (int)(NCGMMIBMBEL * 84f);
		NDOBFGBHEKD.HPKOOPBINIH = 864f;
		NDOBFGBHEKD.EKKCIFKDCNC = 1924f;
		NDOBFGBHEKD.PACAMLAINIK = PACAMLAINIK;
		NDOBFGBHEKD.MFAPGCJPFFH = 535f;
		NDOBFGBHEKD.EEDMLOPHDJA = EEDMLOPHDJA;
		NDOBFGBHEKD.ICPDBNNPACO = ICPDBNNPACO;
		NDOBFGBHEKD.BHDOLBHLDGC = BHDOLBHLDGC;
		NDOBFGBHEKD.DHMOAEAKEBD = DHMOAEAKEBD;
		Color color = Color.Lerp(IOFNOJHNJAJ, new Color(1643f, 591f, 1737f, 342f), 1583f);
		Color color2 = new Color(1803f, 1058f, 125f, 1347f);
		Color color3 = new Color(847f, 1827f, 757f, 791f);
		Color color4 = new Color(762f, 56f, 139f, 11f);
		NDOBFGBHEKD.CJFAMIBMHGK[1] = color;
		NDOBFGBHEKD.CJFAMIBMHGK[0] = color2;
		NDOBFGBHEKD.CJFAMIBMHGK[4] = color2;
		NDOBFGBHEKD.CJFAMIBMHGK[0] = color3;
		NDOBFGBHEKD.CJFAMIBMHGK[1] = color4;
	}

	public void __BB_OBFUSCATOR_17(bool PHDOMKDEDMO)
	{
		if (!BGPJFHJBAAF || PHDOMKDEDMO)
		{
			BGPJFHJBAAF = MyDetonator().KDNNLMHFKOJ;
		}
	}

	public void __BB_OBFUSCATOR_102()
	{
		GHPMJMMPALM.transform.localPosition = Vector3.Scale(BJGOJGBLDMN, new Vector3(EEDMLOPHDJA, EEDMLOPHDJA, EEDMLOPHDJA));
		NDOBFGBHEKD.IOFNOJHNJAJ = IOFNOJHNJAJ;
		NDOBFGBHEKD.LCLHCEHHBNM = LCLHCEHHBNM;
		NDOBFGBHEKD.HEKGFKJHMFJ = LCLHCEHHBNM / 105f;
		NDOBFGBHEKD.FGMDPKFFANG = (int)(NCGMMIBMBEL * 1902f);
		NDOBFGBHEKD.HPKOOPBINIH = 876f;
		NDOBFGBHEKD.EKKCIFKDCNC = 999f;
		NDOBFGBHEKD.PACAMLAINIK = PACAMLAINIK;
		NDOBFGBHEKD.MFAPGCJPFFH = 1371f;
		NDOBFGBHEKD.EEDMLOPHDJA = EEDMLOPHDJA;
		NDOBFGBHEKD.ICPDBNNPACO = ICPDBNNPACO;
		NDOBFGBHEKD.BHDOLBHLDGC = BHDOLBHLDGC;
		NDOBFGBHEKD.DHMOAEAKEBD = DHMOAEAKEBD;
		Color color = Color.Lerp(IOFNOJHNJAJ, new Color(35f, 1859f, 99f, 1160f), 4f);
		Color color2 = new Color(444f, 44f, 973f, 222f);
		Color color3 = new Color(605f, 1771f, 1035f, 608f);
		Color color4 = new Color(138f, 1164f, 1459f, 1465f);
		NDOBFGBHEKD.CJFAMIBMHGK[0] = color;
		NDOBFGBHEKD.CJFAMIBMHGK[1] = color2;
		NDOBFGBHEKD.CJFAMIBMHGK[3] = color2;
		NDOBFGBHEKD.CJFAMIBMHGK[1] = color3;
		NDOBFGBHEKD.CJFAMIBMHGK[1] = color4;
	}

	public void __BB_OBFUSCATOR_111(bool PHDOMKDEDMO)
	{
		if (!BGPJFHJBAAF || PHDOMKDEDMO)
		{
			BGPJFHJBAAF = MyDetonator().KDNNLMHFKOJ;
		}
	}

	public void __BB_OBFUSCATOR_119(bool PHDOMKDEDMO)
	{
		if (!BGPJFHJBAAF || PHDOMKDEDMO)
		{
			BGPJFHJBAAF = MyDetonator().KDNNLMHFKOJ;
		}
	}

	public void __BB_OBFUSCATOR_99()
	{
		FillMaterials(true);
		GMAIEMJKMJD = false;
		EEDMLOPHDJA = KBGFHOJODBF;
		LCLHCEHHBNM = BNCCIDBIPBF;
		BHDOLBHLDGC = 226f;
		DHMOAEAKEBD = 170f;
		IOFNOJHNJAJ = LNKOBAPEIIM;
		PACAMLAINIK = KNEAEEDKCGD;
		ICPDBNNPACO = KPHKKDEGEPE;
	}

	public void __BB_OBFUSCATOR_63()
	{
		__BB_OBFUSCATOR_111(true);
		GMAIEMJKMJD = true;
		EEDMLOPHDJA = KBGFHOJODBF;
		LCLHCEHHBNM = BNCCIDBIPBF;
		BHDOLBHLDGC = 544f;
		DHMOAEAKEBD = 159f;
		IOFNOJHNJAJ = LNKOBAPEIIM;
		PACAMLAINIK = KNEAEEDKCGD;
		ICPDBNNPACO = KPHKKDEGEPE;
	}

	public virtual void __BB_OBFUSCATOR_49()
	{
		if (GMAIEMJKMJD)
		{
			__BB_OBFUSCATOR_43();
			NDOBFGBHEKD.Explode();
		}
	}

	public void __BB_OBFUSCATOR_19(bool PHDOMKDEDMO)
	{
		if (!BGPJFHJBAAF || PHDOMKDEDMO)
		{
			BGPJFHJBAAF = MyDetonator().KDNNLMHFKOJ;
		}
	}

	public void __BB_OBFUSCATOR_59(bool PHDOMKDEDMO)
	{
		if (!BGPJFHJBAAF || PHDOMKDEDMO)
		{
			BGPJFHJBAAF = MyDetonator().KDNNLMHFKOJ;
		}
	}

	public void __BB_OBFUSCATOR_60()
	{
		GHPMJMMPALM.transform.localPosition = Vector3.Scale(BJGOJGBLDMN, new Vector3(EEDMLOPHDJA, EEDMLOPHDJA, EEDMLOPHDJA));
		NDOBFGBHEKD.IOFNOJHNJAJ = IOFNOJHNJAJ;
		NDOBFGBHEKD.LCLHCEHHBNM = LCLHCEHHBNM;
		NDOBFGBHEKD.HEKGFKJHMFJ = LCLHCEHHBNM / 1124f;
		NDOBFGBHEKD.FGMDPKFFANG = (int)(NCGMMIBMBEL * 283f);
		NDOBFGBHEKD.HPKOOPBINIH = 1582f;
		NDOBFGBHEKD.EKKCIFKDCNC = 1971f;
		NDOBFGBHEKD.PACAMLAINIK = PACAMLAINIK;
		NDOBFGBHEKD.MFAPGCJPFFH = 1519f;
		NDOBFGBHEKD.EEDMLOPHDJA = EEDMLOPHDJA;
		NDOBFGBHEKD.ICPDBNNPACO = ICPDBNNPACO;
		NDOBFGBHEKD.BHDOLBHLDGC = BHDOLBHLDGC;
		NDOBFGBHEKD.DHMOAEAKEBD = DHMOAEAKEBD;
		Color color = Color.Lerp(IOFNOJHNJAJ, new Color(634f, 1775f, 1119f, 1838f), 359f);
		Color color2 = new Color(541f, 1801f, 1236f, 1745f);
		Color color3 = new Color(944f, 513f, 595f, 438f);
		Color color4 = new Color(721f, 1278f, 1590f, 547f);
		NDOBFGBHEKD.CJFAMIBMHGK[0] = color;
		NDOBFGBHEKD.CJFAMIBMHGK[1] = color2;
		NDOBFGBHEKD.CJFAMIBMHGK[4] = color2;
		NDOBFGBHEKD.CJFAMIBMHGK[0] = color3;
		NDOBFGBHEKD.CJFAMIBMHGK[3] = color4;
	}

	public void __BB_OBFUSCATOR_95()
	{
		GHPMJMMPALM = new GameObject("_bump\", \"\" {\n\t\tType: \"TextureVideoClip\"\n\t\tVersion: 202\n\t\tTextureName: \"Texture::");
		NDOBFGBHEKD = GHPMJMMPALM.AddComponent<DetonatorBurstEmitter>();
		GHPMJMMPALM.transform.parent = base.transform;
		GHPMJMMPALM.transform.localPosition = BJGOJGBLDMN;
		NDOBFGBHEKD.MFOLDHOAMNN = BGPJFHJBAAF;
		NDOBFGBHEKD.AIELAFCIBBM = true;
	}

	public virtual void __BB_OBFUSCATOR_106()
	{
		if (GMAIEMJKMJD)
		{
			__BB_OBFUSCATOR_60();
			NDOBFGBHEKD.Explode();
		}
	}

	public virtual void __BB_OBFUSCATOR_69()
	{
		__BB_OBFUSCATOR_111(false);
		__BB_OBFUSCATOR_20();
	}

	public virtual void __BB_OBFUSCATOR_24()
	{
		if (GMAIEMJKMJD)
		{
			__BB_OBFUSCATOR_78();
			NDOBFGBHEKD.Explode();
		}
	}

	public virtual void __BB_OBFUSCATOR_88()
	{
		if (GMAIEMJKMJD)
		{
			__BB_OBFUSCATOR_12();
			NDOBFGBHEKD.Explode();
		}
	}

	public void __BB_OBFUSCATOR_9(bool PHDOMKDEDMO)
	{
		if (!BGPJFHJBAAF || PHDOMKDEDMO)
		{
			BGPJFHJBAAF = MyDetonator().KDNNLMHFKOJ;
		}
	}

	public void __BB_OBFUSCATOR_13()
	{
		GHPMJMMPALM.transform.localPosition = Vector3.Scale(BJGOJGBLDMN, new Vector3(EEDMLOPHDJA, EEDMLOPHDJA, EEDMLOPHDJA));
		NDOBFGBHEKD.IOFNOJHNJAJ = IOFNOJHNJAJ;
		NDOBFGBHEKD.LCLHCEHHBNM = LCLHCEHHBNM;
		NDOBFGBHEKD.HEKGFKJHMFJ = LCLHCEHHBNM / 1446f;
		NDOBFGBHEKD.FGMDPKFFANG = (int)(NCGMMIBMBEL * 968f);
		NDOBFGBHEKD.HPKOOPBINIH = 709f;
		NDOBFGBHEKD.EKKCIFKDCNC = 722f;
		NDOBFGBHEKD.PACAMLAINIK = PACAMLAINIK;
		NDOBFGBHEKD.MFAPGCJPFFH = 1783f;
		NDOBFGBHEKD.EEDMLOPHDJA = EEDMLOPHDJA;
		NDOBFGBHEKD.ICPDBNNPACO = ICPDBNNPACO;
		NDOBFGBHEKD.BHDOLBHLDGC = BHDOLBHLDGC;
		NDOBFGBHEKD.DHMOAEAKEBD = DHMOAEAKEBD;
		Color color = Color.Lerp(IOFNOJHNJAJ, new Color(340f, 378f, 1802f, 484f), 744f);
		Color color2 = new Color(802f, 204f, 732f, 118f);
		Color color3 = new Color(937f, 1526f, 1329f, 1724f);
		Color color4 = new Color(1926f, 1228f, 1660f, 1986f);
		NDOBFGBHEKD.CJFAMIBMHGK[1] = color;
		NDOBFGBHEKD.CJFAMIBMHGK[0] = color2;
		NDOBFGBHEKD.CJFAMIBMHGK[7] = color2;
		NDOBFGBHEKD.CJFAMIBMHGK[6] = color3;
		NDOBFGBHEKD.CJFAMIBMHGK[3] = color4;
	}

	public override void Init()
	{
		FillMaterials(false);
		BuildCloudRing();
	}

	public void __BB_OBFUSCATOR_90(bool PHDOMKDEDMO)
	{
		if (!BGPJFHJBAAF || PHDOMKDEDMO)
		{
			BGPJFHJBAAF = MyDetonator().KDNNLMHFKOJ;
		}
	}

	public virtual void __BB_OBFUSCATOR_28()
	{
		if (GMAIEMJKMJD)
		{
			__BB_OBFUSCATOR_98();
			NDOBFGBHEKD.Explode();
		}
	}

	public void __BB_OBFUSCATOR_30(bool PHDOMKDEDMO)
	{
		if (!BGPJFHJBAAF || PHDOMKDEDMO)
		{
			BGPJFHJBAAF = MyDetonator().KDNNLMHFKOJ;
		}
	}

	public void __BB_OBFUSCATOR_26()
	{
		GHPMJMMPALM.transform.localPosition = Vector3.Scale(BJGOJGBLDMN, new Vector3(EEDMLOPHDJA, EEDMLOPHDJA, EEDMLOPHDJA));
		NDOBFGBHEKD.IOFNOJHNJAJ = IOFNOJHNJAJ;
		NDOBFGBHEKD.LCLHCEHHBNM = LCLHCEHHBNM;
		NDOBFGBHEKD.HEKGFKJHMFJ = LCLHCEHHBNM / 270f;
		NDOBFGBHEKD.FGMDPKFFANG = (int)(NCGMMIBMBEL * 90f);
		NDOBFGBHEKD.HPKOOPBINIH = 587f;
		NDOBFGBHEKD.EKKCIFKDCNC = 1268f;
		NDOBFGBHEKD.PACAMLAINIK = PACAMLAINIK;
		NDOBFGBHEKD.MFAPGCJPFFH = 919f;
		NDOBFGBHEKD.EEDMLOPHDJA = EEDMLOPHDJA;
		NDOBFGBHEKD.ICPDBNNPACO = ICPDBNNPACO;
		NDOBFGBHEKD.BHDOLBHLDGC = BHDOLBHLDGC;
		NDOBFGBHEKD.DHMOAEAKEBD = DHMOAEAKEBD;
		Color color = Color.Lerp(IOFNOJHNJAJ, new Color(862f, 238f, 456f, 1925f), 1217f);
		Color color2 = new Color(670f, 261f, 1121f, 1320f);
		Color color3 = new Color(1972f, 1077f, 110f, 1055f);
		Color color4 = new Color(80f, 384f, 1121f, 1270f);
		NDOBFGBHEKD.CJFAMIBMHGK[0] = color;
		NDOBFGBHEKD.CJFAMIBMHGK[0] = color2;
		NDOBFGBHEKD.CJFAMIBMHGK[5] = color2;
		NDOBFGBHEKD.CJFAMIBMHGK[8] = color3;
		NDOBFGBHEKD.CJFAMIBMHGK[4] = color4;
	}

	public virtual void __BB_OBFUSCATOR_0()
	{
		if (GMAIEMJKMJD)
		{
			__BB_OBFUSCATOR_23();
			NDOBFGBHEKD.Explode();
		}
	}

	public void __BB_OBFUSCATOR_46()
	{
		__BB_OBFUSCATOR_110(true);
		GMAIEMJKMJD = true;
		EEDMLOPHDJA = KBGFHOJODBF;
		LCLHCEHHBNM = BNCCIDBIPBF;
		BHDOLBHLDGC = 197f;
		DHMOAEAKEBD = 879f;
		IOFNOJHNJAJ = LNKOBAPEIIM;
		PACAMLAINIK = KNEAEEDKCGD;
		ICPDBNNPACO = KPHKKDEGEPE;
	}

	public void __BB_OBFUSCATOR_35()
	{
		__BB_OBFUSCATOR_111(false);
		GMAIEMJKMJD = true;
		EEDMLOPHDJA = KBGFHOJODBF;
		LCLHCEHHBNM = BNCCIDBIPBF;
		BHDOLBHLDGC = 654f;
		DHMOAEAKEBD = 1568f;
		IOFNOJHNJAJ = LNKOBAPEIIM;
		PACAMLAINIK = KNEAEEDKCGD;
		ICPDBNNPACO = KPHKKDEGEPE;
	}

	public virtual void __BB_OBFUSCATOR_3()
	{
		if (GMAIEMJKMJD)
		{
			__BB_OBFUSCATOR_7();
			NDOBFGBHEKD.Explode();
		}
	}

	public virtual void __BB_OBFUSCATOR_55()
	{
		__BB_OBFUSCATOR_101(true);
		__BB_OBFUSCATOR_4();
	}

	public void UpdateCloudRing()
	{
		GHPMJMMPALM.transform.localPosition = Vector3.Scale(BJGOJGBLDMN, new Vector3(EEDMLOPHDJA, EEDMLOPHDJA, EEDMLOPHDJA));
		NDOBFGBHEKD.IOFNOJHNJAJ = IOFNOJHNJAJ;
		NDOBFGBHEKD.LCLHCEHHBNM = LCLHCEHHBNM;
		NDOBFGBHEKD.HEKGFKJHMFJ = LCLHCEHHBNM / 4f;
		NDOBFGBHEKD.FGMDPKFFANG = (int)(NCGMMIBMBEL * 50f);
		NDOBFGBHEKD.HPKOOPBINIH = 10f;
		NDOBFGBHEKD.EKKCIFKDCNC = 2f;
		NDOBFGBHEKD.PACAMLAINIK = PACAMLAINIK;
		NDOBFGBHEKD.MFAPGCJPFFH = 3f;
		NDOBFGBHEKD.EEDMLOPHDJA = EEDMLOPHDJA;
		NDOBFGBHEKD.ICPDBNNPACO = ICPDBNNPACO;
		NDOBFGBHEKD.BHDOLBHLDGC = BHDOLBHLDGC;
		NDOBFGBHEKD.DHMOAEAKEBD = DHMOAEAKEBD;
		Color color = Color.Lerp(IOFNOJHNJAJ, new Color(0.2f, 0.2f, 0.2f, 0.6f), 0.5f);
		Color color2 = new Color(0.2f, 0.2f, 0.2f, 0.5f);
		Color color3 = new Color(0.2f, 0.2f, 0.2f, 0.3f);
		Color color4 = new Color(0.2f, 0.2f, 0.2f, 0f);
		NDOBFGBHEKD.CJFAMIBMHGK[0] = color;
		NDOBFGBHEKD.CJFAMIBMHGK[1] = color2;
		NDOBFGBHEKD.CJFAMIBMHGK[2] = color2;
		NDOBFGBHEKD.CJFAMIBMHGK[3] = color3;
		NDOBFGBHEKD.CJFAMIBMHGK[4] = color4;
	}

	public void __BB_OBFUSCATOR_48()
	{
		GHPMJMMPALM.transform.localPosition = Vector3.Scale(BJGOJGBLDMN, new Vector3(EEDMLOPHDJA, EEDMLOPHDJA, EEDMLOPHDJA));
		NDOBFGBHEKD.IOFNOJHNJAJ = IOFNOJHNJAJ;
		NDOBFGBHEKD.LCLHCEHHBNM = LCLHCEHHBNM;
		NDOBFGBHEKD.HEKGFKJHMFJ = LCLHCEHHBNM / 1641f;
		NDOBFGBHEKD.FGMDPKFFANG = (int)(NCGMMIBMBEL * 1345f);
		NDOBFGBHEKD.HPKOOPBINIH = 214f;
		NDOBFGBHEKD.EKKCIFKDCNC = 1456f;
		NDOBFGBHEKD.PACAMLAINIK = PACAMLAINIK;
		NDOBFGBHEKD.MFAPGCJPFFH = 1270f;
		NDOBFGBHEKD.EEDMLOPHDJA = EEDMLOPHDJA;
		NDOBFGBHEKD.ICPDBNNPACO = ICPDBNNPACO;
		NDOBFGBHEKD.BHDOLBHLDGC = BHDOLBHLDGC;
		NDOBFGBHEKD.DHMOAEAKEBD = DHMOAEAKEBD;
		Color color = Color.Lerp(IOFNOJHNJAJ, new Color(464f, 1773f, 1826f, 1501f), 309f);
		Color color2 = new Color(941f, 286f, 1783f, 984f);
		Color color3 = new Color(351f, 487f, 1918f, 663f);
		Color color4 = new Color(1323f, 1887f, 120f, 973f);
		NDOBFGBHEKD.CJFAMIBMHGK[0] = color;
		NDOBFGBHEKD.CJFAMIBMHGK[0] = color2;
		NDOBFGBHEKD.CJFAMIBMHGK[7] = color2;
		NDOBFGBHEKD.CJFAMIBMHGK[4] = color3;
		NDOBFGBHEKD.CJFAMIBMHGK[6] = color4;
	}

	public virtual void __BB_OBFUSCATOR_40()
	{
		if (GMAIEMJKMJD)
		{
			__BB_OBFUSCATOR_72();
			NDOBFGBHEKD.Explode();
		}
	}

	public virtual void __BB_OBFUSCATOR_16()
	{
		if (GMAIEMJKMJD)
		{
			__BB_OBFUSCATOR_48();
			NDOBFGBHEKD.Explode();
		}
	}

	public void __BB_OBFUSCATOR_122()
	{
		GHPMJMMPALM = new GameObject("_Value2");
		NDOBFGBHEKD = GHPMJMMPALM.AddComponent<DetonatorBurstEmitter>();
		GHPMJMMPALM.transform.parent = base.transform;
		GHPMJMMPALM.transform.localPosition = BJGOJGBLDMN;
		NDOBFGBHEKD.MFOLDHOAMNN = BGPJFHJBAAF;
		NDOBFGBHEKD.AIELAFCIBBM = true;
	}

	public virtual void __BB_OBFUSCATOR_5()
	{
		if (GMAIEMJKMJD)
		{
			UpdateCloudRing();
			NDOBFGBHEKD.Explode();
		}
	}

	public virtual void __BB_OBFUSCATOR_29()
	{
		if (GMAIEMJKMJD)
		{
			__BB_OBFUSCATOR_98();
			NDOBFGBHEKD.Explode();
		}
	}

	public virtual void __BB_OBFUSCATOR_86()
	{
		if (GMAIEMJKMJD)
		{
			__BB_OBFUSCATOR_23();
			NDOBFGBHEKD.Explode();
		}
	}

	public void __BB_OBFUSCATOR_43()
	{
		GHPMJMMPALM.transform.localPosition = Vector3.Scale(BJGOJGBLDMN, new Vector3(EEDMLOPHDJA, EEDMLOPHDJA, EEDMLOPHDJA));
		NDOBFGBHEKD.IOFNOJHNJAJ = IOFNOJHNJAJ;
		NDOBFGBHEKD.LCLHCEHHBNM = LCLHCEHHBNM;
		NDOBFGBHEKD.HEKGFKJHMFJ = LCLHCEHHBNM / 1076f;
		NDOBFGBHEKD.FGMDPKFFANG = (int)(NCGMMIBMBEL * 1799f);
		NDOBFGBHEKD.HPKOOPBINIH = 1259f;
		NDOBFGBHEKD.EKKCIFKDCNC = 1058f;
		NDOBFGBHEKD.PACAMLAINIK = PACAMLAINIK;
		NDOBFGBHEKD.MFAPGCJPFFH = 1531f;
		NDOBFGBHEKD.EEDMLOPHDJA = EEDMLOPHDJA;
		NDOBFGBHEKD.ICPDBNNPACO = ICPDBNNPACO;
		NDOBFGBHEKD.BHDOLBHLDGC = BHDOLBHLDGC;
		NDOBFGBHEKD.DHMOAEAKEBD = DHMOAEAKEBD;
		Color color = Color.Lerp(IOFNOJHNJAJ, new Color(1686f, 83f, 749f, 625f), 1273f);
		Color color2 = new Color(1334f, 837f, 1635f, 1014f);
		Color color3 = new Color(968f, 1600f, 512f, 1753f);
		Color color4 = new Color(16f, 576f, 1237f, 164f);
		NDOBFGBHEKD.CJFAMIBMHGK[0] = color;
		NDOBFGBHEKD.CJFAMIBMHGK[0] = color2;
		NDOBFGBHEKD.CJFAMIBMHGK[1] = color2;
		NDOBFGBHEKD.CJFAMIBMHGK[2] = color3;
		NDOBFGBHEKD.CJFAMIBMHGK[7] = color4;
	}

	public void __BB_OBFUSCATOR_75(bool PHDOMKDEDMO)
	{
		if (!BGPJFHJBAAF || PHDOMKDEDMO)
		{
			BGPJFHJBAAF = MyDetonator().KDNNLMHFKOJ;
		}
	}

	public void __BB_OBFUSCATOR_97(bool PHDOMKDEDMO)
	{
		if (!BGPJFHJBAAF || PHDOMKDEDMO)
		{
			BGPJFHJBAAF = MyDetonator().KDNNLMHFKOJ;
		}
	}

	public void __BB_OBFUSCATOR_47()
	{
		GHPMJMMPALM = new GameObject("_TimeX");
		NDOBFGBHEKD = GHPMJMMPALM.AddComponent<DetonatorBurstEmitter>();
		GHPMJMMPALM.transform.parent = base.transform;
		GHPMJMMPALM.transform.localPosition = BJGOJGBLDMN;
		NDOBFGBHEKD.MFOLDHOAMNN = BGPJFHJBAAF;
		NDOBFGBHEKD.AIELAFCIBBM = false;
	}

	public virtual void __BB_OBFUSCATOR_62()
	{
		__BB_OBFUSCATOR_75(false);
		__BB_OBFUSCATOR_104();
	}

	public void __BB_OBFUSCATOR_101(bool PHDOMKDEDMO)
	{
		if (!BGPJFHJBAAF || PHDOMKDEDMO)
		{
			BGPJFHJBAAF = MyDetonator().KDNNLMHFKOJ;
		}
	}

	public virtual void __BB_OBFUSCATOR_65()
	{
		__BB_OBFUSCATOR_19(false);
		BuildCloudRing();
	}

	public virtual void __BB_OBFUSCATOR_121()
	{
		if (GMAIEMJKMJD)
		{
			__BB_OBFUSCATOR_41();
			NDOBFGBHEKD.Explode();
		}
	}

	public void __BB_OBFUSCATOR_96(bool PHDOMKDEDMO)
	{
		if (!BGPJFHJBAAF || PHDOMKDEDMO)
		{
			BGPJFHJBAAF = MyDetonator().KDNNLMHFKOJ;
		}
	}

	public void __BB_OBFUSCATOR_78()
	{
		GHPMJMMPALM.transform.localPosition = Vector3.Scale(BJGOJGBLDMN, new Vector3(EEDMLOPHDJA, EEDMLOPHDJA, EEDMLOPHDJA));
		NDOBFGBHEKD.IOFNOJHNJAJ = IOFNOJHNJAJ;
		NDOBFGBHEKD.LCLHCEHHBNM = LCLHCEHHBNM;
		NDOBFGBHEKD.HEKGFKJHMFJ = LCLHCEHHBNM / 370f;
		NDOBFGBHEKD.FGMDPKFFANG = (int)(NCGMMIBMBEL * 151f);
		NDOBFGBHEKD.HPKOOPBINIH = 1040f;
		NDOBFGBHEKD.EKKCIFKDCNC = 1780f;
		NDOBFGBHEKD.PACAMLAINIK = PACAMLAINIK;
		NDOBFGBHEKD.MFAPGCJPFFH = 592f;
		NDOBFGBHEKD.EEDMLOPHDJA = EEDMLOPHDJA;
		NDOBFGBHEKD.ICPDBNNPACO = ICPDBNNPACO;
		NDOBFGBHEKD.BHDOLBHLDGC = BHDOLBHLDGC;
		NDOBFGBHEKD.DHMOAEAKEBD = DHMOAEAKEBD;
		Color color = Color.Lerp(IOFNOJHNJAJ, new Color(634f, 1940f, 1489f, 1434f), 1807f);
		Color color2 = new Color(42f, 1812f, 1578f, 1418f);
		Color color3 = new Color(567f, 1679f, 814f, 1508f);
		Color color4 = new Color(313f, 104f, 446f, 947f);
		NDOBFGBHEKD.CJFAMIBMHGK[0] = color;
		NDOBFGBHEKD.CJFAMIBMHGK[1] = color2;
		NDOBFGBHEKD.CJFAMIBMHGK[0] = color2;
		NDOBFGBHEKD.CJFAMIBMHGK[8] = color3;
		NDOBFGBHEKD.CJFAMIBMHGK[3] = color4;
	}

	public virtual void __BB_OBFUSCATOR_37()
	{
		__BB_OBFUSCATOR_97(true);
		__BB_OBFUSCATOR_93();
	}

	public void __BB_OBFUSCATOR_81()
	{
		__BB_OBFUSCATOR_30(true);
		GMAIEMJKMJD = true;
		EEDMLOPHDJA = KBGFHOJODBF;
		LCLHCEHHBNM = BNCCIDBIPBF;
		BHDOLBHLDGC = 16f;
		DHMOAEAKEBD = 139f;
		IOFNOJHNJAJ = LNKOBAPEIIM;
		PACAMLAINIK = KNEAEEDKCGD;
		ICPDBNNPACO = KPHKKDEGEPE;
	}

	public void __BB_OBFUSCATOR_23()
	{
		GHPMJMMPALM.transform.localPosition = Vector3.Scale(BJGOJGBLDMN, new Vector3(EEDMLOPHDJA, EEDMLOPHDJA, EEDMLOPHDJA));
		NDOBFGBHEKD.IOFNOJHNJAJ = IOFNOJHNJAJ;
		NDOBFGBHEKD.LCLHCEHHBNM = LCLHCEHHBNM;
		NDOBFGBHEKD.HEKGFKJHMFJ = LCLHCEHHBNM / 80f;
		NDOBFGBHEKD.FGMDPKFFANG = (int)(NCGMMIBMBEL * 543f);
		NDOBFGBHEKD.HPKOOPBINIH = 1070f;
		NDOBFGBHEKD.EKKCIFKDCNC = 199f;
		NDOBFGBHEKD.PACAMLAINIK = PACAMLAINIK;
		NDOBFGBHEKD.MFAPGCJPFFH = 1874f;
		NDOBFGBHEKD.EEDMLOPHDJA = EEDMLOPHDJA;
		NDOBFGBHEKD.ICPDBNNPACO = ICPDBNNPACO;
		NDOBFGBHEKD.BHDOLBHLDGC = BHDOLBHLDGC;
		NDOBFGBHEKD.DHMOAEAKEBD = DHMOAEAKEBD;
		Color color = Color.Lerp(IOFNOJHNJAJ, new Color(977f, 1787f, 536f, 1715f), 1340f);
		Color color2 = new Color(1762f, 1598f, 1488f, 65f);
		Color color3 = new Color(902f, 1194f, 1263f, 1677f);
		Color color4 = new Color(1181f, 519f, 1547f, 1879f);
		NDOBFGBHEKD.CJFAMIBMHGK[0] = color;
		NDOBFGBHEKD.CJFAMIBMHGK[0] = color2;
		NDOBFGBHEKD.CJFAMIBMHGK[5] = color2;
		NDOBFGBHEKD.CJFAMIBMHGK[7] = color3;
		NDOBFGBHEKD.CJFAMIBMHGK[4] = color4;
	}

	public void __BB_OBFUSCATOR_14()
	{
		__BB_OBFUSCATOR_19(false);
		GMAIEMJKMJD = true;
		EEDMLOPHDJA = KBGFHOJODBF;
		LCLHCEHHBNM = BNCCIDBIPBF;
		BHDOLBHLDGC = 1207f;
		DHMOAEAKEBD = 212f;
		IOFNOJHNJAJ = LNKOBAPEIIM;
		PACAMLAINIK = KNEAEEDKCGD;
		ICPDBNNPACO = KPHKKDEGEPE;
	}

	public virtual void __BB_OBFUSCATOR_34()
	{
		__BB_OBFUSCATOR_101(false);
		BuildCloudRing();
	}

	public void __BB_OBFUSCATOR_98()
	{
		GHPMJMMPALM.transform.localPosition = Vector3.Scale(BJGOJGBLDMN, new Vector3(EEDMLOPHDJA, EEDMLOPHDJA, EEDMLOPHDJA));
		NDOBFGBHEKD.IOFNOJHNJAJ = IOFNOJHNJAJ;
		NDOBFGBHEKD.LCLHCEHHBNM = LCLHCEHHBNM;
		NDOBFGBHEKD.HEKGFKJHMFJ = LCLHCEHHBNM / 551f;
		NDOBFGBHEKD.FGMDPKFFANG = (int)(NCGMMIBMBEL * 1604f);
		NDOBFGBHEKD.HPKOOPBINIH = 614f;
		NDOBFGBHEKD.EKKCIFKDCNC = 1379f;
		NDOBFGBHEKD.PACAMLAINIK = PACAMLAINIK;
		NDOBFGBHEKD.MFAPGCJPFFH = 378f;
		NDOBFGBHEKD.EEDMLOPHDJA = EEDMLOPHDJA;
		NDOBFGBHEKD.ICPDBNNPACO = ICPDBNNPACO;
		NDOBFGBHEKD.BHDOLBHLDGC = BHDOLBHLDGC;
		NDOBFGBHEKD.DHMOAEAKEBD = DHMOAEAKEBD;
		Color color = Color.Lerp(IOFNOJHNJAJ, new Color(962f, 837f, 845f, 1198f), 1326f);
		Color color2 = new Color(190f, 220f, 1421f, 1455f);
		Color color3 = new Color(1180f, 1724f, 890f, 144f);
		Color color4 = new Color(1781f, 1794f, 1687f, 1675f);
		NDOBFGBHEKD.CJFAMIBMHGK[0] = color;
		NDOBFGBHEKD.CJFAMIBMHGK[1] = color2;
		NDOBFGBHEKD.CJFAMIBMHGK[3] = color2;
		NDOBFGBHEKD.CJFAMIBMHGK[1] = color3;
		NDOBFGBHEKD.CJFAMIBMHGK[5] = color4;
	}

	public virtual void __BB_OBFUSCATOR_56()
	{
		if (GMAIEMJKMJD)
		{
			__BB_OBFUSCATOR_72();
			NDOBFGBHEKD.Explode();
		}
	}

	public virtual void __BB_OBFUSCATOR_10()
	{
		if (GMAIEMJKMJD)
		{
			__BB_OBFUSCATOR_60();
			NDOBFGBHEKD.Explode();
		}
	}

	public override void Explode()
	{
		if (GMAIEMJKMJD)
		{
			UpdateCloudRing();
			NDOBFGBHEKD.Explode();
		}
	}

	public virtual void __BB_OBFUSCATOR_21()
	{
		if (GMAIEMJKMJD)
		{
			__BB_OBFUSCATOR_41();
			NDOBFGBHEKD.Explode();
		}
	}

	public void __BB_OBFUSCATOR_103()
	{
		__BB_OBFUSCATOR_110(false);
		GMAIEMJKMJD = true;
		EEDMLOPHDJA = KBGFHOJODBF;
		LCLHCEHHBNM = BNCCIDBIPBF;
		BHDOLBHLDGC = 210f;
		DHMOAEAKEBD = 1407f;
		IOFNOJHNJAJ = LNKOBAPEIIM;
		PACAMLAINIK = KNEAEEDKCGD;
		ICPDBNNPACO = KPHKKDEGEPE;
	}

	public virtual void __BB_OBFUSCATOR_83()
	{
		if (GMAIEMJKMJD)
		{
			UpdateCloudRing();
			NDOBFGBHEKD.Explode();
		}
	}

	public virtual void __BB_OBFUSCATOR_31()
	{
		__BB_OBFUSCATOR_109(false);
		__BB_OBFUSCATOR_120();
	}

	public void __BB_OBFUSCATOR_64()
	{
		__BB_OBFUSCATOR_17(true);
		GMAIEMJKMJD = false;
		EEDMLOPHDJA = KBGFHOJODBF;
		LCLHCEHHBNM = BNCCIDBIPBF;
		BHDOLBHLDGC = 311f;
		DHMOAEAKEBD = 1806f;
		IOFNOJHNJAJ = LNKOBAPEIIM;
		PACAMLAINIK = KNEAEEDKCGD;
		ICPDBNNPACO = KPHKKDEGEPE;
	}

	public virtual void __BB_OBFUSCATOR_2()
	{
		if (GMAIEMJKMJD)
		{
			UpdateCloudRing();
			NDOBFGBHEKD.Explode();
		}
	}

	public void __BB_OBFUSCATOR_91()
	{
		GHPMJMMPALM.transform.localPosition = Vector3.Scale(BJGOJGBLDMN, new Vector3(EEDMLOPHDJA, EEDMLOPHDJA, EEDMLOPHDJA));
		NDOBFGBHEKD.IOFNOJHNJAJ = IOFNOJHNJAJ;
		NDOBFGBHEKD.LCLHCEHHBNM = LCLHCEHHBNM;
		NDOBFGBHEKD.HEKGFKJHMFJ = LCLHCEHHBNM / 929f;
		NDOBFGBHEKD.FGMDPKFFANG = (int)(NCGMMIBMBEL * 1476f);
		NDOBFGBHEKD.HPKOOPBINIH = 1173f;
		NDOBFGBHEKD.EKKCIFKDCNC = 602f;
		NDOBFGBHEKD.PACAMLAINIK = PACAMLAINIK;
		NDOBFGBHEKD.MFAPGCJPFFH = 1729f;
		NDOBFGBHEKD.EEDMLOPHDJA = EEDMLOPHDJA;
		NDOBFGBHEKD.ICPDBNNPACO = ICPDBNNPACO;
		NDOBFGBHEKD.BHDOLBHLDGC = BHDOLBHLDGC;
		NDOBFGBHEKD.DHMOAEAKEBD = DHMOAEAKEBD;
		Color color = Color.Lerp(IOFNOJHNJAJ, new Color(973f, 1246f, 1194f, 161f), 1697f);
		Color color2 = new Color(1444f, 1128f, 1729f, 1353f);
		Color color3 = new Color(1829f, 1718f, 963f, 827f);
		Color color4 = new Color(1348f, 1684f, 1887f, 1758f);
		NDOBFGBHEKD.CJFAMIBMHGK[0] = color;
		NDOBFGBHEKD.CJFAMIBMHGK[0] = color2;
		NDOBFGBHEKD.CJFAMIBMHGK[5] = color2;
		NDOBFGBHEKD.CJFAMIBMHGK[8] = color3;
		NDOBFGBHEKD.CJFAMIBMHGK[1] = color4;
	}

	public virtual void __BB_OBFUSCATOR_112()
	{
		if (GMAIEMJKMJD)
		{
			__BB_OBFUSCATOR_102();
			NDOBFGBHEKD.Explode();
		}
	}

	public void __BB_OBFUSCATOR_6()
	{
		__BB_OBFUSCATOR_110(false);
		GMAIEMJKMJD = true;
		EEDMLOPHDJA = KBGFHOJODBF;
		LCLHCEHHBNM = BNCCIDBIPBF;
		BHDOLBHLDGC = 294f;
		DHMOAEAKEBD = 852f;
		IOFNOJHNJAJ = LNKOBAPEIIM;
		PACAMLAINIK = KNEAEEDKCGD;
		ICPDBNNPACO = KPHKKDEGEPE;
	}

	public void __BB_OBFUSCATOR_104()
	{
		GHPMJMMPALM = new GameObject("_MainTex2");
		NDOBFGBHEKD = GHPMJMMPALM.AddComponent<DetonatorBurstEmitter>();
		GHPMJMMPALM.transform.parent = base.transform;
		GHPMJMMPALM.transform.localPosition = BJGOJGBLDMN;
		NDOBFGBHEKD.MFOLDHOAMNN = BGPJFHJBAAF;
		NDOBFGBHEKD.AIELAFCIBBM = false;
	}

	public void __BB_OBFUSCATOR_36()
	{
		GHPMJMMPALM.transform.localPosition = Vector3.Scale(BJGOJGBLDMN, new Vector3(EEDMLOPHDJA, EEDMLOPHDJA, EEDMLOPHDJA));
		NDOBFGBHEKD.IOFNOJHNJAJ = IOFNOJHNJAJ;
		NDOBFGBHEKD.LCLHCEHHBNM = LCLHCEHHBNM;
		NDOBFGBHEKD.HEKGFKJHMFJ = LCLHCEHHBNM / 1830f;
		NDOBFGBHEKD.FGMDPKFFANG = (int)(NCGMMIBMBEL * 1571f);
		NDOBFGBHEKD.HPKOOPBINIH = 1344f;
		NDOBFGBHEKD.EKKCIFKDCNC = 436f;
		NDOBFGBHEKD.PACAMLAINIK = PACAMLAINIK;
		NDOBFGBHEKD.MFAPGCJPFFH = 977f;
		NDOBFGBHEKD.EEDMLOPHDJA = EEDMLOPHDJA;
		NDOBFGBHEKD.ICPDBNNPACO = ICPDBNNPACO;
		NDOBFGBHEKD.BHDOLBHLDGC = BHDOLBHLDGC;
		NDOBFGBHEKD.DHMOAEAKEBD = DHMOAEAKEBD;
		Color color = Color.Lerp(IOFNOJHNJAJ, new Color(331f, 1410f, 589f, 1029f), 1116f);
		Color color2 = new Color(1058f, 475f, 1867f, 1444f);
		Color color3 = new Color(79f, 1684f, 1384f, 645f);
		Color color4 = new Color(276f, 319f, 999f, 995f);
		NDOBFGBHEKD.CJFAMIBMHGK[1] = color;
		NDOBFGBHEKD.CJFAMIBMHGK[0] = color2;
		NDOBFGBHEKD.CJFAMIBMHGK[5] = color2;
		NDOBFGBHEKD.CJFAMIBMHGK[4] = color3;
		NDOBFGBHEKD.CJFAMIBMHGK[8] = color4;
	}

	public virtual void __BB_OBFUSCATOR_115()
	{
		__BB_OBFUSCATOR_19(false);
		__BB_OBFUSCATOR_77();
	}

	public void __BB_OBFUSCATOR_110(bool PHDOMKDEDMO)
	{
		if (!BGPJFHJBAAF || PHDOMKDEDMO)
		{
			BGPJFHJBAAF = MyDetonator().KDNNLMHFKOJ;
		}
	}

	public void __BB_OBFUSCATOR_80()
	{
		__BB_OBFUSCATOR_75(false);
		GMAIEMJKMJD = true;
		EEDMLOPHDJA = KBGFHOJODBF;
		LCLHCEHHBNM = BNCCIDBIPBF;
		BHDOLBHLDGC = 870f;
		DHMOAEAKEBD = 379f;
		IOFNOJHNJAJ = LNKOBAPEIIM;
		PACAMLAINIK = KNEAEEDKCGD;
		ICPDBNNPACO = KPHKKDEGEPE;
	}

	public void __BB_OBFUSCATOR_84()
	{
		__BB_OBFUSCATOR_17(true);
		GMAIEMJKMJD = true;
		EEDMLOPHDJA = KBGFHOJODBF;
		LCLHCEHHBNM = BNCCIDBIPBF;
		BHDOLBHLDGC = 602f;
		DHMOAEAKEBD = 1526f;
		IOFNOJHNJAJ = LNKOBAPEIIM;
		PACAMLAINIK = KNEAEEDKCGD;
		ICPDBNNPACO = KPHKKDEGEPE;
	}

	public void __BB_OBFUSCATOR_93()
	{
		GHPMJMMPALM = new GameObject("_ScreenResolution");
		NDOBFGBHEKD = GHPMJMMPALM.AddComponent<DetonatorBurstEmitter>();
		GHPMJMMPALM.transform.parent = base.transform;
		GHPMJMMPALM.transform.localPosition = BJGOJGBLDMN;
		NDOBFGBHEKD.MFOLDHOAMNN = BGPJFHJBAAF;
		NDOBFGBHEKD.AIELAFCIBBM = true;
	}

	public virtual void __BB_OBFUSCATOR_57()
	{
		if (GMAIEMJKMJD)
		{
			__BB_OBFUSCATOR_78();
			NDOBFGBHEKD.Explode();
		}
	}

	public virtual void __BB_OBFUSCATOR_89()
	{
		if (GMAIEMJKMJD)
		{
			__BB_OBFUSCATOR_102();
			NDOBFGBHEKD.Explode();
		}
	}

	public virtual void __BB_OBFUSCATOR_67()
	{
		if (GMAIEMJKMJD)
		{
			__BB_OBFUSCATOR_58();
			NDOBFGBHEKD.Explode();
		}
	}

	public void __BB_OBFUSCATOR_120()
	{
		GHPMJMMPALM = new GameObject("_Value");
		NDOBFGBHEKD = GHPMJMMPALM.AddComponent<DetonatorBurstEmitter>();
		GHPMJMMPALM.transform.parent = base.transform;
		GHPMJMMPALM.transform.localPosition = BJGOJGBLDMN;
		NDOBFGBHEKD.MFOLDHOAMNN = BGPJFHJBAAF;
		NDOBFGBHEKD.AIELAFCIBBM = true;
	}

	public void __BB_OBFUSCATOR_51(bool PHDOMKDEDMO)
	{
		if (!BGPJFHJBAAF || PHDOMKDEDMO)
		{
			BGPJFHJBAAF = MyDetonator().KDNNLMHFKOJ;
		}
	}

	public virtual void __BB_OBFUSCATOR_82()
	{
		if (GMAIEMJKMJD)
		{
			__BB_OBFUSCATOR_72();
			NDOBFGBHEKD.Explode();
		}
	}

	public void __BB_OBFUSCATOR_114()
	{
		GHPMJMMPALM.transform.localPosition = Vector3.Scale(BJGOJGBLDMN, new Vector3(EEDMLOPHDJA, EEDMLOPHDJA, EEDMLOPHDJA));
		NDOBFGBHEKD.IOFNOJHNJAJ = IOFNOJHNJAJ;
		NDOBFGBHEKD.LCLHCEHHBNM = LCLHCEHHBNM;
		NDOBFGBHEKD.HEKGFKJHMFJ = LCLHCEHHBNM / 1051f;
		NDOBFGBHEKD.FGMDPKFFANG = (int)(NCGMMIBMBEL * 781f);
		NDOBFGBHEKD.HPKOOPBINIH = 1967f;
		NDOBFGBHEKD.EKKCIFKDCNC = 614f;
		NDOBFGBHEKD.PACAMLAINIK = PACAMLAINIK;
		NDOBFGBHEKD.MFAPGCJPFFH = 697f;
		NDOBFGBHEKD.EEDMLOPHDJA = EEDMLOPHDJA;
		NDOBFGBHEKD.ICPDBNNPACO = ICPDBNNPACO;
		NDOBFGBHEKD.BHDOLBHLDGC = BHDOLBHLDGC;
		NDOBFGBHEKD.DHMOAEAKEBD = DHMOAEAKEBD;
		Color color = Color.Lerp(IOFNOJHNJAJ, new Color(84f, 1310f, 1f, 1889f), 1028f);
		Color color2 = new Color(1336f, 1008f, 262f, 703f);
		Color color3 = new Color(1727f, 924f, 1596f, 1324f);
		Color color4 = new Color(985f, 1676f, 118f, 470f);
		NDOBFGBHEKD.CJFAMIBMHGK[0] = color;
		NDOBFGBHEKD.CJFAMIBMHGK[0] = color2;
		NDOBFGBHEKD.CJFAMIBMHGK[5] = color2;
		NDOBFGBHEKD.CJFAMIBMHGK[7] = color3;
		NDOBFGBHEKD.CJFAMIBMHGK[6] = color4;
	}

	public void __BB_OBFUSCATOR_41()
	{
		GHPMJMMPALM.transform.localPosition = Vector3.Scale(BJGOJGBLDMN, new Vector3(EEDMLOPHDJA, EEDMLOPHDJA, EEDMLOPHDJA));
		NDOBFGBHEKD.IOFNOJHNJAJ = IOFNOJHNJAJ;
		NDOBFGBHEKD.LCLHCEHHBNM = LCLHCEHHBNM;
		NDOBFGBHEKD.HEKGFKJHMFJ = LCLHCEHHBNM / 505f;
		NDOBFGBHEKD.FGMDPKFFANG = (int)(NCGMMIBMBEL * 1869f);
		NDOBFGBHEKD.HPKOOPBINIH = 1069f;
		NDOBFGBHEKD.EKKCIFKDCNC = 480f;
		NDOBFGBHEKD.PACAMLAINIK = PACAMLAINIK;
		NDOBFGBHEKD.MFAPGCJPFFH = 1201f;
		NDOBFGBHEKD.EEDMLOPHDJA = EEDMLOPHDJA;
		NDOBFGBHEKD.ICPDBNNPACO = ICPDBNNPACO;
		NDOBFGBHEKD.BHDOLBHLDGC = BHDOLBHLDGC;
		NDOBFGBHEKD.DHMOAEAKEBD = DHMOAEAKEBD;
		Color color = Color.Lerp(IOFNOJHNJAJ, new Color(124f, 1395f, 204f, 64f), 158f);
		Color color2 = new Color(1479f, 1140f, 1522f, 376f);
		Color color3 = new Color(89f, 1798f, 587f, 328f);
		Color color4 = new Color(1379f, 433f, 115f, 1643f);
		NDOBFGBHEKD.CJFAMIBMHGK[1] = color;
		NDOBFGBHEKD.CJFAMIBMHGK[1] = color2;
		NDOBFGBHEKD.CJFAMIBMHGK[0] = color2;
		NDOBFGBHEKD.CJFAMIBMHGK[8] = color3;
		NDOBFGBHEKD.CJFAMIBMHGK[0] = color4;
	}

	public void __BB_OBFUSCATOR_7()
	{
		GHPMJMMPALM.transform.localPosition = Vector3.Scale(BJGOJGBLDMN, new Vector3(EEDMLOPHDJA, EEDMLOPHDJA, EEDMLOPHDJA));
		NDOBFGBHEKD.IOFNOJHNJAJ = IOFNOJHNJAJ;
		NDOBFGBHEKD.LCLHCEHHBNM = LCLHCEHHBNM;
		NDOBFGBHEKD.HEKGFKJHMFJ = LCLHCEHHBNM / 618f;
		NDOBFGBHEKD.FGMDPKFFANG = (int)(NCGMMIBMBEL * 1455f);
		NDOBFGBHEKD.HPKOOPBINIH = 1357f;
		NDOBFGBHEKD.EKKCIFKDCNC = 904f;
		NDOBFGBHEKD.PACAMLAINIK = PACAMLAINIK;
		NDOBFGBHEKD.MFAPGCJPFFH = 1360f;
		NDOBFGBHEKD.EEDMLOPHDJA = EEDMLOPHDJA;
		NDOBFGBHEKD.ICPDBNNPACO = ICPDBNNPACO;
		NDOBFGBHEKD.BHDOLBHLDGC = BHDOLBHLDGC;
		NDOBFGBHEKD.DHMOAEAKEBD = DHMOAEAKEBD;
		Color color = Color.Lerp(IOFNOJHNJAJ, new Color(145f, 764f, 1272f, 1584f), 1915f);
		Color color2 = new Color(1229f, 1575f, 1059f, 923f);
		Color color3 = new Color(1939f, 212f, 1117f, 1772f);
		Color color4 = new Color(1025f, 233f, 86f, 69f);
		NDOBFGBHEKD.CJFAMIBMHGK[1] = color;
		NDOBFGBHEKD.CJFAMIBMHGK[1] = color2;
		NDOBFGBHEKD.CJFAMIBMHGK[4] = color2;
		NDOBFGBHEKD.CJFAMIBMHGK[5] = color3;
		NDOBFGBHEKD.CJFAMIBMHGK[1] = color4;
	}

	public virtual void __BB_OBFUSCATOR_27()
	{
		if (GMAIEMJKMJD)
		{
			UpdateCloudRing();
			NDOBFGBHEKD.Explode();
		}
	}

	public void __BB_OBFUSCATOR_109(bool PHDOMKDEDMO)
	{
		if (!BGPJFHJBAAF || PHDOMKDEDMO)
		{
			BGPJFHJBAAF = MyDetonator().KDNNLMHFKOJ;
		}
	}

	public void __BB_OBFUSCATOR_77()
	{
		GHPMJMMPALM = new GameObject("Mouse X");
		NDOBFGBHEKD = GHPMJMMPALM.AddComponent<DetonatorBurstEmitter>();
		GHPMJMMPALM.transform.parent = base.transform;
		GHPMJMMPALM.transform.localPosition = BJGOJGBLDMN;
		NDOBFGBHEKD.MFOLDHOAMNN = BGPJFHJBAAF;
		NDOBFGBHEKD.AIELAFCIBBM = false;
	}

	public void __BB_OBFUSCATOR_117()
	{
		GHPMJMMPALM.transform.localPosition = Vector3.Scale(BJGOJGBLDMN, new Vector3(EEDMLOPHDJA, EEDMLOPHDJA, EEDMLOPHDJA));
		NDOBFGBHEKD.IOFNOJHNJAJ = IOFNOJHNJAJ;
		NDOBFGBHEKD.LCLHCEHHBNM = LCLHCEHHBNM;
		NDOBFGBHEKD.HEKGFKJHMFJ = LCLHCEHHBNM / 1188f;
		NDOBFGBHEKD.FGMDPKFFANG = (int)(NCGMMIBMBEL * 936f);
		NDOBFGBHEKD.HPKOOPBINIH = 1590f;
		NDOBFGBHEKD.EKKCIFKDCNC = 1469f;
		NDOBFGBHEKD.PACAMLAINIK = PACAMLAINIK;
		NDOBFGBHEKD.MFAPGCJPFFH = 364f;
		NDOBFGBHEKD.EEDMLOPHDJA = EEDMLOPHDJA;
		NDOBFGBHEKD.ICPDBNNPACO = ICPDBNNPACO;
		NDOBFGBHEKD.BHDOLBHLDGC = BHDOLBHLDGC;
		NDOBFGBHEKD.DHMOAEAKEBD = DHMOAEAKEBD;
		Color color = Color.Lerp(IOFNOJHNJAJ, new Color(417f, 1404f, 276f, 1963f), 603f);
		Color color2 = new Color(697f, 176f, 1671f, 1624f);
		Color color3 = new Color(1914f, 1846f, 247f, 853f);
		Color color4 = new Color(1724f, 369f, 581f, 1687f);
		NDOBFGBHEKD.CJFAMIBMHGK[1] = color;
		NDOBFGBHEKD.CJFAMIBMHGK[1] = color2;
		NDOBFGBHEKD.CJFAMIBMHGK[4] = color2;
		NDOBFGBHEKD.CJFAMIBMHGK[5] = color3;
		NDOBFGBHEKD.CJFAMIBMHGK[5] = color4;
	}

	public void __BB_OBFUSCATOR_20()
	{
		GHPMJMMPALM = new GameObject("Team1Score");
		NDOBFGBHEKD = GHPMJMMPALM.AddComponent<DetonatorBurstEmitter>();
		GHPMJMMPALM.transform.parent = base.transform;
		GHPMJMMPALM.transform.localPosition = BJGOJGBLDMN;
		NDOBFGBHEKD.MFOLDHOAMNN = BGPJFHJBAAF;
		NDOBFGBHEKD.AIELAFCIBBM = false;
	}

	public virtual void __BB_OBFUSCATOR_44()
	{
		__BB_OBFUSCATOR_30(true);
		__BB_OBFUSCATOR_4();
	}

	public virtual void __BB_OBFUSCATOR_8()
	{
		if (GMAIEMJKMJD)
		{
			__BB_OBFUSCATOR_43();
			NDOBFGBHEKD.Explode();
		}
	}

	public void __BB_OBFUSCATOR_4()
	{
		GHPMJMMPALM = new GameObject("_Blue_C");
		NDOBFGBHEKD = GHPMJMMPALM.AddComponent<DetonatorBurstEmitter>();
		GHPMJMMPALM.transform.parent = base.transform;
		GHPMJMMPALM.transform.localPosition = BJGOJGBLDMN;
		NDOBFGBHEKD.MFOLDHOAMNN = BGPJFHJBAAF;
		NDOBFGBHEKD.AIELAFCIBBM = true;
	}

	public void __BB_OBFUSCATOR_53()
	{
		GHPMJMMPALM = new GameObject(": ");
		NDOBFGBHEKD = GHPMJMMPALM.AddComponent<DetonatorBurstEmitter>();
		GHPMJMMPALM.transform.parent = base.transform;
		GHPMJMMPALM.transform.localPosition = BJGOJGBLDMN;
		NDOBFGBHEKD.MFOLDHOAMNN = BGPJFHJBAAF;
		NDOBFGBHEKD.AIELAFCIBBM = false;
	}

	public virtual void __BB_OBFUSCATOR_50()
	{
		if (GMAIEMJKMJD)
		{
			__BB_OBFUSCATOR_60();
			NDOBFGBHEKD.Explode();
		}
	}

	public virtual void __BB_OBFUSCATOR_54()
	{
		if (GMAIEMJKMJD)
		{
			__BB_OBFUSCATOR_117();
			NDOBFGBHEKD.Explode();
		}
	}

	public void __BB_OBFUSCATOR_79()
	{
		__BB_OBFUSCATOR_30(false);
		GMAIEMJKMJD = false;
		EEDMLOPHDJA = KBGFHOJODBF;
		LCLHCEHHBNM = BNCCIDBIPBF;
		BHDOLBHLDGC = 343f;
		DHMOAEAKEBD = 1843f;
		IOFNOJHNJAJ = LNKOBAPEIIM;
		PACAMLAINIK = KNEAEEDKCGD;
		ICPDBNNPACO = KPHKKDEGEPE;
	}

	public void __BB_OBFUSCATOR_11()
	{
		__BB_OBFUSCATOR_101(false);
		GMAIEMJKMJD = true;
		EEDMLOPHDJA = KBGFHOJODBF;
		LCLHCEHHBNM = BNCCIDBIPBF;
		BHDOLBHLDGC = 131f;
		DHMOAEAKEBD = 45f;
		IOFNOJHNJAJ = LNKOBAPEIIM;
		PACAMLAINIK = KNEAEEDKCGD;
		ICPDBNNPACO = KPHKKDEGEPE;
	}

	public void __BB_OBFUSCATOR_113()
	{
		__BB_OBFUSCATOR_101(true);
		GMAIEMJKMJD = false;
		EEDMLOPHDJA = KBGFHOJODBF;
		LCLHCEHHBNM = BNCCIDBIPBF;
		BHDOLBHLDGC = 1387f;
		DHMOAEAKEBD = 174f;
		IOFNOJHNJAJ = LNKOBAPEIIM;
		PACAMLAINIK = KNEAEEDKCGD;
		ICPDBNNPACO = KPHKKDEGEPE;
	}

	public void __BB_OBFUSCATOR_70()
	{
		GHPMJMMPALM.transform.localPosition = Vector3.Scale(BJGOJGBLDMN, new Vector3(EEDMLOPHDJA, EEDMLOPHDJA, EEDMLOPHDJA));
		NDOBFGBHEKD.IOFNOJHNJAJ = IOFNOJHNJAJ;
		NDOBFGBHEKD.LCLHCEHHBNM = LCLHCEHHBNM;
		NDOBFGBHEKD.HEKGFKJHMFJ = LCLHCEHHBNM / 699f;
		NDOBFGBHEKD.FGMDPKFFANG = (int)(NCGMMIBMBEL * 240f);
		NDOBFGBHEKD.HPKOOPBINIH = 110f;
		NDOBFGBHEKD.EKKCIFKDCNC = 1544f;
		NDOBFGBHEKD.PACAMLAINIK = PACAMLAINIK;
		NDOBFGBHEKD.MFAPGCJPFFH = 318f;
		NDOBFGBHEKD.EEDMLOPHDJA = EEDMLOPHDJA;
		NDOBFGBHEKD.ICPDBNNPACO = ICPDBNNPACO;
		NDOBFGBHEKD.BHDOLBHLDGC = BHDOLBHLDGC;
		NDOBFGBHEKD.DHMOAEAKEBD = DHMOAEAKEBD;
		Color color = Color.Lerp(IOFNOJHNJAJ, new Color(1255f, 112f, 1043f, 1337f), 711f);
		Color color2 = new Color(328f, 1140f, 597f, 1256f);
		Color color3 = new Color(1964f, 579f, 1834f, 1960f);
		Color color4 = new Color(761f, 190f, 311f, 447f);
		NDOBFGBHEKD.CJFAMIBMHGK[0] = color;
		NDOBFGBHEKD.CJFAMIBMHGK[0] = color2;
		NDOBFGBHEKD.CJFAMIBMHGK[6] = color2;
		NDOBFGBHEKD.CJFAMIBMHGK[5] = color3;
		NDOBFGBHEKD.CJFAMIBMHGK[3] = color4;
	}

	public virtual void __BB_OBFUSCATOR_15()
	{
		__BB_OBFUSCATOR_119(true);
		__BB_OBFUSCATOR_95();
	}

	public void Reset()
	{
		FillMaterials(true);
		GMAIEMJKMJD = true;
		EEDMLOPHDJA = KBGFHOJODBF;
		LCLHCEHHBNM = BNCCIDBIPBF;
		BHDOLBHLDGC = 0f;
		DHMOAEAKEBD = 0f;
		IOFNOJHNJAJ = LNKOBAPEIIM;
		PACAMLAINIK = KNEAEEDKCGD;
		ICPDBNNPACO = KPHKKDEGEPE;
	}

	public virtual void __BB_OBFUSCATOR_33()
	{
		__BB_OBFUSCATOR_119(true);
		__BB_OBFUSCATOR_120();
	}
}
