using UnityEngine;

[RequireComponent(typeof(Detonator))]
[AddComponentMenu("Detonator/Sparks")]
public class DetonatorSparks : DetonatorComponent
{
	private float KBGFHOJODBF = 1f;

	private float BNCCIDBIPBF = 4f;

	private Vector3 KNEAEEDKCGD = new Vector3(155f, 155f, 155f);

	private Color LNKOBAPEIIM = Color.white;

	private Vector3 KPHKKDEGEPE = Physics.gravity;

	private float CLOHJBJHJIN;

	private GameObject KBLDLECJNGB;

	private DetonatorBurstEmitter GKNLFMAJDFG;

	public Material OOBJJKOBLHO;

	public void __BB_OBFUSCATOR_17()
	{
		__BB_OBFUSCATOR_36(false);
		GMAIEMJKMJD = false;
		EEDMLOPHDJA = KBGFHOJODBF;
		LCLHCEHHBNM = BNCCIDBIPBF;
		BHDOLBHLDGC = 1255f;
		DHMOAEAKEBD = 95f;
		IOFNOJHNJAJ = LNKOBAPEIIM;
		PACAMLAINIK = KNEAEEDKCGD;
		ICPDBNNPACO = KPHKKDEGEPE;
	}

	public void __BB_OBFUSCATOR_50()
	{
		CLOHJBJHJIN = LCLHCEHHBNM * PJKHHCHLFIF;
		GKNLFMAJDFG.IOFNOJHNJAJ = IOFNOJHNJAJ;
		GKNLFMAJDFG.LCLHCEHHBNM = CLOHJBJHJIN / 814f;
		GKNLFMAJDFG.HEKGFKJHMFJ = CLOHJBJHJIN;
		GKNLFMAJDFG.FGMDPKFFANG = (int)(NCGMMIBMBEL * 1077f);
		GKNLFMAJDFG.HPKOOPBINIH = 1051f;
		GKNLFMAJDFG.EKKCIFKDCNC = 1611f;
		if (GKNLFMAJDFG.NJGDFDGPNLN > 842f)
		{
			GKNLFMAJDFG.PACAMLAINIK = new Vector3(PACAMLAINIK.x / Mathf.Log(GKNLFMAJDFG.NJGDFDGPNLN), PACAMLAINIK.y * Mathf.Log(GKNLFMAJDFG.NJGDFDGPNLN), PACAMLAINIK.z / Mathf.Log(GKNLFMAJDFG.NJGDFDGPNLN));
		}
		else
		{
			GKNLFMAJDFG.PACAMLAINIK = PACAMLAINIK;
		}
		GKNLFMAJDFG.MFAPGCJPFFH = 1251f;
		GKNLFMAJDFG.EEDMLOPHDJA = EEDMLOPHDJA;
		GKNLFMAJDFG.BHDOLBHLDGC = BHDOLBHLDGC;
		GKNLFMAJDFG.DHMOAEAKEBD = DHMOAEAKEBD;
	}

	public void __BB_OBFUSCATOR_72(bool PHDOMKDEDMO)
	{
		if (!OOBJJKOBLHO || PHDOMKDEDMO)
		{
			OOBJJKOBLHO = MyDetonator().OOBJJKOBLHO;
		}
	}

	public void __BB_OBFUSCATOR_6(bool PHDOMKDEDMO)
	{
		if (!OOBJJKOBLHO || PHDOMKDEDMO)
		{
			OOBJJKOBLHO = MyDetonator().OOBJJKOBLHO;
		}
	}

	public void __BB_OBFUSCATOR_39()
	{
		CLOHJBJHJIN = LCLHCEHHBNM * PJKHHCHLFIF;
		GKNLFMAJDFG.IOFNOJHNJAJ = IOFNOJHNJAJ;
		GKNLFMAJDFG.LCLHCEHHBNM = CLOHJBJHJIN / 67f;
		GKNLFMAJDFG.HEKGFKJHMFJ = CLOHJBJHJIN;
		GKNLFMAJDFG.FGMDPKFFANG = (int)(NCGMMIBMBEL * 582f);
		GKNLFMAJDFG.HPKOOPBINIH = 1555f;
		GKNLFMAJDFG.EKKCIFKDCNC = 1797f;
		if (GKNLFMAJDFG.NJGDFDGPNLN > 106f)
		{
			GKNLFMAJDFG.PACAMLAINIK = new Vector3(PACAMLAINIK.x / Mathf.Log(GKNLFMAJDFG.NJGDFDGPNLN), PACAMLAINIK.y * Mathf.Log(GKNLFMAJDFG.NJGDFDGPNLN), PACAMLAINIK.z / Mathf.Log(GKNLFMAJDFG.NJGDFDGPNLN));
		}
		else
		{
			GKNLFMAJDFG.PACAMLAINIK = PACAMLAINIK;
		}
		GKNLFMAJDFG.MFAPGCJPFFH = 1954f;
		GKNLFMAJDFG.EEDMLOPHDJA = EEDMLOPHDJA;
		GKNLFMAJDFG.BHDOLBHLDGC = BHDOLBHLDGC;
		GKNLFMAJDFG.DHMOAEAKEBD = DHMOAEAKEBD;
	}

	public void __BB_OBFUSCATOR_30()
	{
		__BB_OBFUSCATOR_42(true);
		GMAIEMJKMJD = true;
		EEDMLOPHDJA = KBGFHOJODBF;
		LCLHCEHHBNM = BNCCIDBIPBF;
		BHDOLBHLDGC = 888f;
		DHMOAEAKEBD = 545f;
		IOFNOJHNJAJ = LNKOBAPEIIM;
		PACAMLAINIK = KNEAEEDKCGD;
		ICPDBNNPACO = KPHKKDEGEPE;
	}

	public virtual void __BB_OBFUSCATOR_8()
	{
		__BB_OBFUSCATOR_74(false);
		BuildSparks();
	}

	public void __BB_OBFUSCATOR_21()
	{
		CLOHJBJHJIN = LCLHCEHHBNM * PJKHHCHLFIF;
		GKNLFMAJDFG.IOFNOJHNJAJ = IOFNOJHNJAJ;
		GKNLFMAJDFG.LCLHCEHHBNM = CLOHJBJHJIN / 1689f;
		GKNLFMAJDFG.HEKGFKJHMFJ = CLOHJBJHJIN;
		GKNLFMAJDFG.FGMDPKFFANG = (int)(NCGMMIBMBEL * 1334f);
		GKNLFMAJDFG.HPKOOPBINIH = 697f;
		GKNLFMAJDFG.EKKCIFKDCNC = 498f;
		if (GKNLFMAJDFG.NJGDFDGPNLN > 1030f)
		{
			GKNLFMAJDFG.PACAMLAINIK = new Vector3(PACAMLAINIK.x / Mathf.Log(GKNLFMAJDFG.NJGDFDGPNLN), PACAMLAINIK.y * Mathf.Log(GKNLFMAJDFG.NJGDFDGPNLN), PACAMLAINIK.z / Mathf.Log(GKNLFMAJDFG.NJGDFDGPNLN));
		}
		else
		{
			GKNLFMAJDFG.PACAMLAINIK = PACAMLAINIK;
		}
		GKNLFMAJDFG.MFAPGCJPFFH = 1143f;
		GKNLFMAJDFG.EEDMLOPHDJA = EEDMLOPHDJA;
		GKNLFMAJDFG.BHDOLBHLDGC = BHDOLBHLDGC;
		GKNLFMAJDFG.DHMOAEAKEBD = DHMOAEAKEBD;
	}

	public virtual void __BB_OBFUSCATOR_65()
	{
		__BB_OBFUSCATOR_74(false);
		__BB_OBFUSCATOR_41();
	}

	public virtual void __BB_OBFUSCATOR_2()
	{
		if (GMAIEMJKMJD)
		{
			__BB_OBFUSCATOR_12();
			GKNLFMAJDFG.Explode();
		}
	}

	public virtual void __BB_OBFUSCATOR_73()
	{
		__BB_OBFUSCATOR_20(true);
		__BB_OBFUSCATOR_29();
	}

	public virtual void __BB_OBFUSCATOR_46()
	{
		__BB_OBFUSCATOR_36(true);
		__BB_OBFUSCATOR_33();
	}

	public void UpdateSparks()
	{
		CLOHJBJHJIN = LCLHCEHHBNM * PJKHHCHLFIF;
		GKNLFMAJDFG.IOFNOJHNJAJ = IOFNOJHNJAJ;
		GKNLFMAJDFG.LCLHCEHHBNM = CLOHJBJHJIN / 4f;
		GKNLFMAJDFG.HEKGFKJHMFJ = CLOHJBJHJIN;
		GKNLFMAJDFG.FGMDPKFFANG = (int)(NCGMMIBMBEL * 50f);
		GKNLFMAJDFG.HPKOOPBINIH = 0.5f;
		GKNLFMAJDFG.EKKCIFKDCNC = 0.25f;
		if (GKNLFMAJDFG.NJGDFDGPNLN > 0f)
		{
			GKNLFMAJDFG.PACAMLAINIK = new Vector3(PACAMLAINIK.x / Mathf.Log(GKNLFMAJDFG.NJGDFDGPNLN), PACAMLAINIK.y * Mathf.Log(GKNLFMAJDFG.NJGDFDGPNLN), PACAMLAINIK.z / Mathf.Log(GKNLFMAJDFG.NJGDFDGPNLN));
		}
		else
		{
			GKNLFMAJDFG.PACAMLAINIK = PACAMLAINIK;
		}
		GKNLFMAJDFG.MFAPGCJPFFH = 0f;
		GKNLFMAJDFG.EEDMLOPHDJA = EEDMLOPHDJA;
		GKNLFMAJDFG.BHDOLBHLDGC = BHDOLBHLDGC;
		GKNLFMAJDFG.DHMOAEAKEBD = DHMOAEAKEBD;
	}

	public virtual void __BB_OBFUSCATOR_10()
	{
		if (GMAIEMJKMJD)
		{
			__BB_OBFUSCATOR_50();
			GKNLFMAJDFG.Explode();
		}
	}

	public virtual void __BB_OBFUSCATOR_60()
	{
		__BB_OBFUSCATOR_36(false);
		__BB_OBFUSCATOR_41();
	}

	public void __BB_OBFUSCATOR_67(bool PHDOMKDEDMO)
	{
		if (!OOBJJKOBLHO || PHDOMKDEDMO)
		{
			OOBJJKOBLHO = MyDetonator().OOBJJKOBLHO;
		}
	}

	public virtual void __BB_OBFUSCATOR_24()
	{
		if (GMAIEMJKMJD)
		{
			__BB_OBFUSCATOR_66();
			GKNLFMAJDFG.Explode();
		}
	}

	public void __BB_OBFUSCATOR_42(bool PHDOMKDEDMO)
	{
		if (!OOBJJKOBLHO || PHDOMKDEDMO)
		{
			OOBJJKOBLHO = MyDetonator().OOBJJKOBLHO;
		}
	}

	public virtual void __BB_OBFUSCATOR_15()
	{
		if (GMAIEMJKMJD)
		{
			UpdateSparks();
			GKNLFMAJDFG.Explode();
		}
	}

	public void __BB_OBFUSCATOR_70(bool PHDOMKDEDMO)
	{
		if (!OOBJJKOBLHO || PHDOMKDEDMO)
		{
			OOBJJKOBLHO = MyDetonator().OOBJJKOBLHO;
		}
	}

	public virtual void __BB_OBFUSCATOR_0()
	{
		if (GMAIEMJKMJD)
		{
			__BB_OBFUSCATOR_50();
			GKNLFMAJDFG.Explode();
		}
	}

	public void __BB_OBFUSCATOR_57()
	{
		KBLDLECJNGB = new GameObject("_TimeX");
		GKNLFMAJDFG = KBLDLECJNGB.AddComponent<DetonatorBurstEmitter>();
		KBLDLECJNGB.transform.parent = base.transform;
		KBLDLECJNGB.transform.localPosition = BJGOJGBLDMN;
		KBLDLECJNGB.transform.localRotation = Quaternion.identity;
		GKNLFMAJDFG.MFOLDHOAMNN = OOBJJKOBLHO;
		GKNLFMAJDFG.ICPDBNNPACO = Physics.gravity / 1989f;
		GKNLFMAJDFG.AIELAFCIBBM = false;
		GKNLFMAJDFG.MJHAPHHGGHI = MyDetonator().MJHAPHHGGHI;
		GKNLFMAJDFG.NJGDFDGPNLN = MyDetonator().NJGDFDGPNLN;
	}

	public void __BB_OBFUSCATOR_37()
	{
		KBLDLECJNGB = new GameObject("_Size");
		GKNLFMAJDFG = KBLDLECJNGB.AddComponent<DetonatorBurstEmitter>();
		KBLDLECJNGB.transform.parent = base.transform;
		KBLDLECJNGB.transform.localPosition = BJGOJGBLDMN;
		KBLDLECJNGB.transform.localRotation = Quaternion.identity;
		GKNLFMAJDFG.MFOLDHOAMNN = OOBJJKOBLHO;
		GKNLFMAJDFG.ICPDBNNPACO = Physics.gravity / 443f;
		GKNLFMAJDFG.AIELAFCIBBM = true;
		GKNLFMAJDFG.MJHAPHHGGHI = MyDetonator().MJHAPHHGGHI;
		GKNLFMAJDFG.NJGDFDGPNLN = MyDetonator().NJGDFDGPNLN;
	}

	public void __BB_OBFUSCATOR_4()
	{
		__BB_OBFUSCATOR_42(false);
		GMAIEMJKMJD = true;
		EEDMLOPHDJA = KBGFHOJODBF;
		LCLHCEHHBNM = BNCCIDBIPBF;
		BHDOLBHLDGC = 555f;
		DHMOAEAKEBD = 825f;
		IOFNOJHNJAJ = LNKOBAPEIIM;
		PACAMLAINIK = KNEAEEDKCGD;
		ICPDBNNPACO = KPHKKDEGEPE;
	}

	public virtual void __BB_OBFUSCATOR_5()
	{
		__BB_OBFUSCATOR_6(false);
		__BB_OBFUSCATOR_79();
	}

	public void __BB_OBFUSCATOR_35()
	{
		KBLDLECJNGB = new GameObject("While selected STW-25 press G for flashlight");
		GKNLFMAJDFG = KBLDLECJNGB.AddComponent<DetonatorBurstEmitter>();
		KBLDLECJNGB.transform.parent = base.transform;
		KBLDLECJNGB.transform.localPosition = BJGOJGBLDMN;
		KBLDLECJNGB.transform.localRotation = Quaternion.identity;
		GKNLFMAJDFG.MFOLDHOAMNN = OOBJJKOBLHO;
		GKNLFMAJDFG.ICPDBNNPACO = Physics.gravity / 1217f;
		GKNLFMAJDFG.AIELAFCIBBM = true;
		GKNLFMAJDFG.MJHAPHHGGHI = MyDetonator().MJHAPHHGGHI;
		GKNLFMAJDFG.NJGDFDGPNLN = MyDetonator().NJGDFDGPNLN;
	}

	public virtual void __BB_OBFUSCATOR_64()
	{
		if (GMAIEMJKMJD)
		{
			__BB_OBFUSCATOR_56();
			GKNLFMAJDFG.Explode();
		}
	}

	public void __BB_OBFUSCATOR_29()
	{
		KBLDLECJNGB = new GameObject("</size>");
		GKNLFMAJDFG = KBLDLECJNGB.AddComponent<DetonatorBurstEmitter>();
		KBLDLECJNGB.transform.parent = base.transform;
		KBLDLECJNGB.transform.localPosition = BJGOJGBLDMN;
		KBLDLECJNGB.transform.localRotation = Quaternion.identity;
		GKNLFMAJDFG.MFOLDHOAMNN = OOBJJKOBLHO;
		GKNLFMAJDFG.ICPDBNNPACO = Physics.gravity / 1362f;
		GKNLFMAJDFG.AIELAFCIBBM = false;
		GKNLFMAJDFG.MJHAPHHGGHI = MyDetonator().MJHAPHHGGHI;
		GKNLFMAJDFG.NJGDFDGPNLN = MyDetonator().NJGDFDGPNLN;
	}

	public void __BB_OBFUSCATOR_41()
	{
		KBLDLECJNGB = new GameObject("_NeighbourMaxTex");
		GKNLFMAJDFG = KBLDLECJNGB.AddComponent<DetonatorBurstEmitter>();
		KBLDLECJNGB.transform.parent = base.transform;
		KBLDLECJNGB.transform.localPosition = BJGOJGBLDMN;
		KBLDLECJNGB.transform.localRotation = Quaternion.identity;
		GKNLFMAJDFG.MFOLDHOAMNN = OOBJJKOBLHO;
		GKNLFMAJDFG.ICPDBNNPACO = Physics.gravity / 139f;
		GKNLFMAJDFG.AIELAFCIBBM = false;
		GKNLFMAJDFG.MJHAPHHGGHI = MyDetonator().MJHAPHHGGHI;
		GKNLFMAJDFG.NJGDFDGPNLN = MyDetonator().NJGDFDGPNLN;
	}

	public void __BB_OBFUSCATOR_56()
	{
		CLOHJBJHJIN = LCLHCEHHBNM * PJKHHCHLFIF;
		GKNLFMAJDFG.IOFNOJHNJAJ = IOFNOJHNJAJ;
		GKNLFMAJDFG.LCLHCEHHBNM = CLOHJBJHJIN / 270f;
		GKNLFMAJDFG.HEKGFKJHMFJ = CLOHJBJHJIN;
		GKNLFMAJDFG.FGMDPKFFANG = (int)(NCGMMIBMBEL * 1682f);
		GKNLFMAJDFG.HPKOOPBINIH = 1288f;
		GKNLFMAJDFG.EKKCIFKDCNC = 1212f;
		if (GKNLFMAJDFG.NJGDFDGPNLN > 479f)
		{
			GKNLFMAJDFG.PACAMLAINIK = new Vector3(PACAMLAINIK.x / Mathf.Log(GKNLFMAJDFG.NJGDFDGPNLN), PACAMLAINIK.y * Mathf.Log(GKNLFMAJDFG.NJGDFDGPNLN), PACAMLAINIK.z / Mathf.Log(GKNLFMAJDFG.NJGDFDGPNLN));
		}
		else
		{
			GKNLFMAJDFG.PACAMLAINIK = PACAMLAINIK;
		}
		GKNLFMAJDFG.MFAPGCJPFFH = 208f;
		GKNLFMAJDFG.EEDMLOPHDJA = EEDMLOPHDJA;
		GKNLFMAJDFG.BHDOLBHLDGC = BHDOLBHLDGC;
		GKNLFMAJDFG.DHMOAEAKEBD = DHMOAEAKEBD;
	}

	public void __BB_OBFUSCATOR_33()
	{
		KBLDLECJNGB = new GameObject("Ping");
		GKNLFMAJDFG = KBLDLECJNGB.AddComponent<DetonatorBurstEmitter>();
		KBLDLECJNGB.transform.parent = base.transform;
		KBLDLECJNGB.transform.localPosition = BJGOJGBLDMN;
		KBLDLECJNGB.transform.localRotation = Quaternion.identity;
		GKNLFMAJDFG.MFOLDHOAMNN = OOBJJKOBLHO;
		GKNLFMAJDFG.ICPDBNNPACO = Physics.gravity / 1558f;
		GKNLFMAJDFG.AIELAFCIBBM = false;
		GKNLFMAJDFG.MJHAPHHGGHI = MyDetonator().MJHAPHHGGHI;
		GKNLFMAJDFG.NJGDFDGPNLN = MyDetonator().NJGDFDGPNLN;
	}

	public void __BB_OBFUSCATOR_25()
	{
		__BB_OBFUSCATOR_20(true);
		GMAIEMJKMJD = true;
		EEDMLOPHDJA = KBGFHOJODBF;
		LCLHCEHHBNM = BNCCIDBIPBF;
		BHDOLBHLDGC = 1366f;
		DHMOAEAKEBD = 784f;
		IOFNOJHNJAJ = LNKOBAPEIIM;
		PACAMLAINIK = KNEAEEDKCGD;
		ICPDBNNPACO = KPHKKDEGEPE;
	}

	public void __BB_OBFUSCATOR_22()
	{
		KBLDLECJNGB = new GameObject("Horizontal");
		GKNLFMAJDFG = KBLDLECJNGB.AddComponent<DetonatorBurstEmitter>();
		KBLDLECJNGB.transform.parent = base.transform;
		KBLDLECJNGB.transform.localPosition = BJGOJGBLDMN;
		KBLDLECJNGB.transform.localRotation = Quaternion.identity;
		GKNLFMAJDFG.MFOLDHOAMNN = OOBJJKOBLHO;
		GKNLFMAJDFG.ICPDBNNPACO = Physics.gravity / 192f;
		GKNLFMAJDFG.AIELAFCIBBM = false;
		GKNLFMAJDFG.MJHAPHHGGHI = MyDetonator().MJHAPHHGGHI;
		GKNLFMAJDFG.NJGDFDGPNLN = MyDetonator().NJGDFDGPNLN;
	}

	public void __BB_OBFUSCATOR_58()
	{
		__BB_OBFUSCATOR_74(false);
		GMAIEMJKMJD = false;
		EEDMLOPHDJA = KBGFHOJODBF;
		LCLHCEHHBNM = BNCCIDBIPBF;
		BHDOLBHLDGC = 425f;
		DHMOAEAKEBD = 1506f;
		IOFNOJHNJAJ = LNKOBAPEIIM;
		PACAMLAINIK = KNEAEEDKCGD;
		ICPDBNNPACO = KPHKKDEGEPE;
	}

	public void __BB_OBFUSCATOR_12()
	{
		CLOHJBJHJIN = LCLHCEHHBNM * PJKHHCHLFIF;
		GKNLFMAJDFG.IOFNOJHNJAJ = IOFNOJHNJAJ;
		GKNLFMAJDFG.LCLHCEHHBNM = CLOHJBJHJIN / 1211f;
		GKNLFMAJDFG.HEKGFKJHMFJ = CLOHJBJHJIN;
		GKNLFMAJDFG.FGMDPKFFANG = (int)(NCGMMIBMBEL * 245f);
		GKNLFMAJDFG.HPKOOPBINIH = 850f;
		GKNLFMAJDFG.EKKCIFKDCNC = 331f;
		if (GKNLFMAJDFG.NJGDFDGPNLN > 1757f)
		{
			GKNLFMAJDFG.PACAMLAINIK = new Vector3(PACAMLAINIK.x / Mathf.Log(GKNLFMAJDFG.NJGDFDGPNLN), PACAMLAINIK.y * Mathf.Log(GKNLFMAJDFG.NJGDFDGPNLN), PACAMLAINIK.z / Mathf.Log(GKNLFMAJDFG.NJGDFDGPNLN));
		}
		else
		{
			GKNLFMAJDFG.PACAMLAINIK = PACAMLAINIK;
		}
		GKNLFMAJDFG.MFAPGCJPFFH = 1961f;
		GKNLFMAJDFG.EEDMLOPHDJA = EEDMLOPHDJA;
		GKNLFMAJDFG.BHDOLBHLDGC = BHDOLBHLDGC;
		GKNLFMAJDFG.DHMOAEAKEBD = DHMOAEAKEBD;
	}

	public void __BB_OBFUSCATOR_66()
	{
		CLOHJBJHJIN = LCLHCEHHBNM * PJKHHCHLFIF;
		GKNLFMAJDFG.IOFNOJHNJAJ = IOFNOJHNJAJ;
		GKNLFMAJDFG.LCLHCEHHBNM = CLOHJBJHJIN / 1353f;
		GKNLFMAJDFG.HEKGFKJHMFJ = CLOHJBJHJIN;
		GKNLFMAJDFG.FGMDPKFFANG = (int)(NCGMMIBMBEL * 439f);
		GKNLFMAJDFG.HPKOOPBINIH = 1322f;
		GKNLFMAJDFG.EKKCIFKDCNC = 1293f;
		if (GKNLFMAJDFG.NJGDFDGPNLN > 131f)
		{
			GKNLFMAJDFG.PACAMLAINIK = new Vector3(PACAMLAINIK.x / Mathf.Log(GKNLFMAJDFG.NJGDFDGPNLN), PACAMLAINIK.y * Mathf.Log(GKNLFMAJDFG.NJGDFDGPNLN), PACAMLAINIK.z / Mathf.Log(GKNLFMAJDFG.NJGDFDGPNLN));
		}
		else
		{
			GKNLFMAJDFG.PACAMLAINIK = PACAMLAINIK;
		}
		GKNLFMAJDFG.MFAPGCJPFFH = 463f;
		GKNLFMAJDFG.EEDMLOPHDJA = EEDMLOPHDJA;
		GKNLFMAJDFG.BHDOLBHLDGC = BHDOLBHLDGC;
		GKNLFMAJDFG.DHMOAEAKEBD = DHMOAEAKEBD;
	}

	public virtual void __BB_OBFUSCATOR_19()
	{
		FillMaterials(true);
		__BB_OBFUSCATOR_40();
	}

	public void __BB_OBFUSCATOR_14()
	{
		__BB_OBFUSCATOR_70(false);
		GMAIEMJKMJD = false;
		EEDMLOPHDJA = KBGFHOJODBF;
		LCLHCEHHBNM = BNCCIDBIPBF;
		BHDOLBHLDGC = 1329f;
		DHMOAEAKEBD = 358f;
		IOFNOJHNJAJ = LNKOBAPEIIM;
		PACAMLAINIK = KNEAEEDKCGD;
		ICPDBNNPACO = KPHKKDEGEPE;
	}

	public virtual void __BB_OBFUSCATOR_52()
	{
		__BB_OBFUSCATOR_42(false);
		__BB_OBFUSCATOR_33();
	}

	public void __BB_OBFUSCATOR_31()
	{
		KBLDLECJNGB = new GameObject("_Value4");
		GKNLFMAJDFG = KBLDLECJNGB.AddComponent<DetonatorBurstEmitter>();
		KBLDLECJNGB.transform.parent = base.transform;
		KBLDLECJNGB.transform.localPosition = BJGOJGBLDMN;
		KBLDLECJNGB.transform.localRotation = Quaternion.identity;
		GKNLFMAJDFG.MFOLDHOAMNN = OOBJJKOBLHO;
		GKNLFMAJDFG.ICPDBNNPACO = Physics.gravity / 1354f;
		GKNLFMAJDFG.AIELAFCIBBM = false;
		GKNLFMAJDFG.MJHAPHHGGHI = MyDetonator().MJHAPHHGGHI;
		GKNLFMAJDFG.NJGDFDGPNLN = MyDetonator().NJGDFDGPNLN;
	}

	public virtual void __BB_OBFUSCATOR_59()
	{
		if (GMAIEMJKMJD)
		{
			__BB_OBFUSCATOR_45();
			GKNLFMAJDFG.Explode();
		}
	}

	public void __BB_OBFUSCATOR_36(bool PHDOMKDEDMO)
	{
		if (!OOBJJKOBLHO || PHDOMKDEDMO)
		{
			OOBJJKOBLHO = MyDetonator().OOBJJKOBLHO;
		}
	}

	public override void Explode()
	{
		if (GMAIEMJKMJD)
		{
			UpdateSparks();
			GKNLFMAJDFG.Explode();
		}
	}

	public void BuildSparks()
	{
		KBLDLECJNGB = new GameObject("Sparks");
		GKNLFMAJDFG = KBLDLECJNGB.AddComponent<DetonatorBurstEmitter>();
		KBLDLECJNGB.transform.parent = base.transform;
		KBLDLECJNGB.transform.localPosition = BJGOJGBLDMN;
		KBLDLECJNGB.transform.localRotation = Quaternion.identity;
		GKNLFMAJDFG.MFOLDHOAMNN = OOBJJKOBLHO;
		GKNLFMAJDFG.ICPDBNNPACO = Physics.gravity / 3f;
		GKNLFMAJDFG.AIELAFCIBBM = false;
		GKNLFMAJDFG.MJHAPHHGGHI = MyDetonator().MJHAPHHGGHI;
		GKNLFMAJDFG.NJGDFDGPNLN = MyDetonator().NJGDFDGPNLN;
	}

	public void __BB_OBFUSCATOR_74(bool PHDOMKDEDMO)
	{
		if (!OOBJJKOBLHO || PHDOMKDEDMO)
		{
			OOBJJKOBLHO = MyDetonator().OOBJJKOBLHO;
		}
	}

	public void FillMaterials(bool PHDOMKDEDMO)
	{
		if (!OOBJJKOBLHO || PHDOMKDEDMO)
		{
			OOBJJKOBLHO = MyDetonator().OOBJJKOBLHO;
		}
	}

	public void __BB_OBFUSCATOR_77()
	{
		KBLDLECJNGB = new GameObject("_MaxRadiusOrKInPaper");
		GKNLFMAJDFG = KBLDLECJNGB.AddComponent<DetonatorBurstEmitter>();
		KBLDLECJNGB.transform.parent = base.transform;
		KBLDLECJNGB.transform.localPosition = BJGOJGBLDMN;
		KBLDLECJNGB.transform.localRotation = Quaternion.identity;
		GKNLFMAJDFG.MFOLDHOAMNN = OOBJJKOBLHO;
		GKNLFMAJDFG.ICPDBNNPACO = Physics.gravity / 990f;
		GKNLFMAJDFG.AIELAFCIBBM = false;
		GKNLFMAJDFG.MJHAPHHGGHI = MyDetonator().MJHAPHHGGHI;
		GKNLFMAJDFG.NJGDFDGPNLN = MyDetonator().NJGDFDGPNLN;
	}

	public void __BB_OBFUSCATOR_23()
	{
		__BB_OBFUSCATOR_38(false);
		GMAIEMJKMJD = false;
		EEDMLOPHDJA = KBGFHOJODBF;
		LCLHCEHHBNM = BNCCIDBIPBF;
		BHDOLBHLDGC = 1143f;
		DHMOAEAKEBD = 866f;
		IOFNOJHNJAJ = LNKOBAPEIIM;
		PACAMLAINIK = KNEAEEDKCGD;
		ICPDBNNPACO = KPHKKDEGEPE;
	}

	public virtual void __BB_OBFUSCATOR_47()
	{
		if (GMAIEMJKMJD)
		{
			__BB_OBFUSCATOR_12();
			GKNLFMAJDFG.Explode();
		}
	}

	public void __BB_OBFUSCATOR_79()
	{
		KBLDLECJNGB = new GameObject("_Strength");
		GKNLFMAJDFG = KBLDLECJNGB.AddComponent<DetonatorBurstEmitter>();
		KBLDLECJNGB.transform.parent = base.transform;
		KBLDLECJNGB.transform.localPosition = BJGOJGBLDMN;
		KBLDLECJNGB.transform.localRotation = Quaternion.identity;
		GKNLFMAJDFG.MFOLDHOAMNN = OOBJJKOBLHO;
		GKNLFMAJDFG.ICPDBNNPACO = Physics.gravity / 705f;
		GKNLFMAJDFG.AIELAFCIBBM = true;
		GKNLFMAJDFG.MJHAPHHGGHI = MyDetonator().MJHAPHHGGHI;
		GKNLFMAJDFG.NJGDFDGPNLN = MyDetonator().NJGDFDGPNLN;
	}

	public void __BB_OBFUSCATOR_63()
	{
		__BB_OBFUSCATOR_36(true);
		GMAIEMJKMJD = false;
		EEDMLOPHDJA = KBGFHOJODBF;
		LCLHCEHHBNM = BNCCIDBIPBF;
		BHDOLBHLDGC = 1778f;
		DHMOAEAKEBD = 1567f;
		IOFNOJHNJAJ = LNKOBAPEIIM;
		PACAMLAINIK = KNEAEEDKCGD;
		ICPDBNNPACO = KPHKKDEGEPE;
	}

	public virtual void __BB_OBFUSCATOR_68()
	{
		if (GMAIEMJKMJD)
		{
			__BB_OBFUSCATOR_21();
			GKNLFMAJDFG.Explode();
		}
	}

	public void __BB_OBFUSCATOR_38(bool PHDOMKDEDMO)
	{
		if (!OOBJJKOBLHO || PHDOMKDEDMO)
		{
			OOBJJKOBLHO = MyDetonator().OOBJJKOBLHO;
		}
	}

	public void __BB_OBFUSCATOR_61()
	{
		__BB_OBFUSCATOR_74(false);
		GMAIEMJKMJD = false;
		EEDMLOPHDJA = KBGFHOJODBF;
		LCLHCEHHBNM = BNCCIDBIPBF;
		BHDOLBHLDGC = 737f;
		DHMOAEAKEBD = 159f;
		IOFNOJHNJAJ = LNKOBAPEIIM;
		PACAMLAINIK = KNEAEEDKCGD;
		ICPDBNNPACO = KPHKKDEGEPE;
	}

	public override void Init()
	{
		FillMaterials(false);
		BuildSparks();
	}

	public void __BB_OBFUSCATOR_40()
	{
		KBLDLECJNGB = new GameObject(">");
		GKNLFMAJDFG = KBLDLECJNGB.AddComponent<DetonatorBurstEmitter>();
		KBLDLECJNGB.transform.parent = base.transform;
		KBLDLECJNGB.transform.localPosition = BJGOJGBLDMN;
		KBLDLECJNGB.transform.localRotation = Quaternion.identity;
		GKNLFMAJDFG.MFOLDHOAMNN = OOBJJKOBLHO;
		GKNLFMAJDFG.ICPDBNNPACO = Physics.gravity / 1894f;
		GKNLFMAJDFG.AIELAFCIBBM = false;
		GKNLFMAJDFG.MJHAPHHGGHI = MyDetonator().MJHAPHHGGHI;
		GKNLFMAJDFG.NJGDFDGPNLN = MyDetonator().NJGDFDGPNLN;
	}

	public void __BB_OBFUSCATOR_26()
	{
		CLOHJBJHJIN = LCLHCEHHBNM * PJKHHCHLFIF;
		GKNLFMAJDFG.IOFNOJHNJAJ = IOFNOJHNJAJ;
		GKNLFMAJDFG.LCLHCEHHBNM = CLOHJBJHJIN / 282f;
		GKNLFMAJDFG.HEKGFKJHMFJ = CLOHJBJHJIN;
		GKNLFMAJDFG.FGMDPKFFANG = (int)(NCGMMIBMBEL * 109f);
		GKNLFMAJDFG.HPKOOPBINIH = 1412f;
		GKNLFMAJDFG.EKKCIFKDCNC = 428f;
		if (GKNLFMAJDFG.NJGDFDGPNLN > 1942f)
		{
			GKNLFMAJDFG.PACAMLAINIK = new Vector3(PACAMLAINIK.x / Mathf.Log(GKNLFMAJDFG.NJGDFDGPNLN), PACAMLAINIK.y * Mathf.Log(GKNLFMAJDFG.NJGDFDGPNLN), PACAMLAINIK.z / Mathf.Log(GKNLFMAJDFG.NJGDFDGPNLN));
		}
		else
		{
			GKNLFMAJDFG.PACAMLAINIK = PACAMLAINIK;
		}
		GKNLFMAJDFG.MFAPGCJPFFH = 635f;
		GKNLFMAJDFG.EEDMLOPHDJA = EEDMLOPHDJA;
		GKNLFMAJDFG.BHDOLBHLDGC = BHDOLBHLDGC;
		GKNLFMAJDFG.DHMOAEAKEBD = DHMOAEAKEBD;
	}

	public virtual void __BB_OBFUSCATOR_11()
	{
		if (GMAIEMJKMJD)
		{
			__BB_OBFUSCATOR_39();
			GKNLFMAJDFG.Explode();
		}
	}

	public void __BB_OBFUSCATOR_75()
	{
		FillMaterials(true);
		GMAIEMJKMJD = true;
		EEDMLOPHDJA = KBGFHOJODBF;
		LCLHCEHHBNM = BNCCIDBIPBF;
		BHDOLBHLDGC = 1999f;
		DHMOAEAKEBD = 1431f;
		IOFNOJHNJAJ = LNKOBAPEIIM;
		PACAMLAINIK = KNEAEEDKCGD;
		ICPDBNNPACO = KPHKKDEGEPE;
	}

	public void __BB_OBFUSCATOR_28(bool PHDOMKDEDMO)
	{
		if (!OOBJJKOBLHO || PHDOMKDEDMO)
		{
			OOBJJKOBLHO = MyDetonator().OOBJJKOBLHO;
		}
	}

	public virtual void __BB_OBFUSCATOR_16()
	{
		__BB_OBFUSCATOR_67(true);
		BuildSparks();
	}

	public virtual void __BB_OBFUSCATOR_69()
	{
		FillMaterials(true);
		__BB_OBFUSCATOR_22();
	}

	public virtual void __BB_OBFUSCATOR_49()
	{
		if (GMAIEMJKMJD)
		{
			__BB_OBFUSCATOR_50();
			GKNLFMAJDFG.Explode();
		}
	}

	public void __BB_OBFUSCATOR_51()
	{
		CLOHJBJHJIN = LCLHCEHHBNM * PJKHHCHLFIF;
		GKNLFMAJDFG.IOFNOJHNJAJ = IOFNOJHNJAJ;
		GKNLFMAJDFG.LCLHCEHHBNM = CLOHJBJHJIN / 1132f;
		GKNLFMAJDFG.HEKGFKJHMFJ = CLOHJBJHJIN;
		GKNLFMAJDFG.FGMDPKFFANG = (int)(NCGMMIBMBEL * 543f);
		GKNLFMAJDFG.HPKOOPBINIH = 20f;
		GKNLFMAJDFG.EKKCIFKDCNC = 1692f;
		if (GKNLFMAJDFG.NJGDFDGPNLN > 1084f)
		{
			GKNLFMAJDFG.PACAMLAINIK = new Vector3(PACAMLAINIK.x / Mathf.Log(GKNLFMAJDFG.NJGDFDGPNLN), PACAMLAINIK.y * Mathf.Log(GKNLFMAJDFG.NJGDFDGPNLN), PACAMLAINIK.z / Mathf.Log(GKNLFMAJDFG.NJGDFDGPNLN));
		}
		else
		{
			GKNLFMAJDFG.PACAMLAINIK = PACAMLAINIK;
		}
		GKNLFMAJDFG.MFAPGCJPFFH = 1923f;
		GKNLFMAJDFG.EEDMLOPHDJA = EEDMLOPHDJA;
		GKNLFMAJDFG.BHDOLBHLDGC = BHDOLBHLDGC;
		GKNLFMAJDFG.DHMOAEAKEBD = DHMOAEAKEBD;
	}

	public virtual void __BB_OBFUSCATOR_48()
	{
		if (GMAIEMJKMJD)
		{
			__BB_OBFUSCATOR_45();
			GKNLFMAJDFG.Explode();
		}
	}

	public void __BB_OBFUSCATOR_54()
	{
		KBLDLECJNGB = new GameObject("/");
		GKNLFMAJDFG = KBLDLECJNGB.AddComponent<DetonatorBurstEmitter>();
		KBLDLECJNGB.transform.parent = base.transform;
		KBLDLECJNGB.transform.localPosition = BJGOJGBLDMN;
		KBLDLECJNGB.transform.localRotation = Quaternion.identity;
		GKNLFMAJDFG.MFOLDHOAMNN = OOBJJKOBLHO;
		GKNLFMAJDFG.ICPDBNNPACO = Physics.gravity / 1262f;
		GKNLFMAJDFG.AIELAFCIBBM = true;
		GKNLFMAJDFG.MJHAPHHGGHI = MyDetonator().MJHAPHHGGHI;
		GKNLFMAJDFG.NJGDFDGPNLN = MyDetonator().NJGDFDGPNLN;
	}

	public void __BB_OBFUSCATOR_20(bool PHDOMKDEDMO)
	{
		if (!OOBJJKOBLHO || PHDOMKDEDMO)
		{
			OOBJJKOBLHO = MyDetonator().OOBJJKOBLHO;
		}
	}

	public void __BB_OBFUSCATOR_45()
	{
		CLOHJBJHJIN = LCLHCEHHBNM * PJKHHCHLFIF;
		GKNLFMAJDFG.IOFNOJHNJAJ = IOFNOJHNJAJ;
		GKNLFMAJDFG.LCLHCEHHBNM = CLOHJBJHJIN / 505f;
		GKNLFMAJDFG.HEKGFKJHMFJ = CLOHJBJHJIN;
		GKNLFMAJDFG.FGMDPKFFANG = (int)(NCGMMIBMBEL * 1500f);
		GKNLFMAJDFG.HPKOOPBINIH = 1600f;
		GKNLFMAJDFG.EKKCIFKDCNC = 1580f;
		if (GKNLFMAJDFG.NJGDFDGPNLN > 1537f)
		{
			GKNLFMAJDFG.PACAMLAINIK = new Vector3(PACAMLAINIK.x / Mathf.Log(GKNLFMAJDFG.NJGDFDGPNLN), PACAMLAINIK.y * Mathf.Log(GKNLFMAJDFG.NJGDFDGPNLN), PACAMLAINIK.z / Mathf.Log(GKNLFMAJDFG.NJGDFDGPNLN));
		}
		else
		{
			GKNLFMAJDFG.PACAMLAINIK = PACAMLAINIK;
		}
		GKNLFMAJDFG.MFAPGCJPFFH = 1020f;
		GKNLFMAJDFG.EEDMLOPHDJA = EEDMLOPHDJA;
		GKNLFMAJDFG.BHDOLBHLDGC = BHDOLBHLDGC;
		GKNLFMAJDFG.DHMOAEAKEBD = DHMOAEAKEBD;
	}

	public void Reset()
	{
		FillMaterials(true);
		GMAIEMJKMJD = true;
		EEDMLOPHDJA = KBGFHOJODBF;
		LCLHCEHHBNM = BNCCIDBIPBF;
		BHDOLBHLDGC = 0f;
		DHMOAEAKEBD = 0f;
		IOFNOJHNJAJ = LNKOBAPEIIM;
		PACAMLAINIK = KNEAEEDKCGD;
		ICPDBNNPACO = KPHKKDEGEPE;
	}

	public virtual void __BB_OBFUSCATOR_78()
	{
		if (GMAIEMJKMJD)
		{
			__BB_OBFUSCATOR_66();
			GKNLFMAJDFG.Explode();
		}
	}

	public virtual void __BB_OBFUSCATOR_32()
	{
		if (GMAIEMJKMJD)
		{
			__BB_OBFUSCATOR_39();
			GKNLFMAJDFG.Explode();
		}
	}
}
