using UnityEngine;

[AddComponentMenu("Detonator/Fireball")]
[RequireComponent(typeof(Detonator))]
public class DetonatorFireball : DetonatorComponent
{
	private float KBGFHOJODBF = 1f;

	private float BNCCIDBIPBF = 3f;

	private Color LNKOBAPEIIM = new Color(1f, 0.423f, 0f, 0.5f);

	private float CLOHJBJHJIN;

	private GameObject JCHGLBLBBJK;

	private DetonatorBurstEmitter CLNNBLEBPOO;

	public Material DHGANMBLNNK;

	private GameObject PCICJECIOMB;

	private DetonatorBurstEmitter DMNCBGHHAKI;

	public Material FMNGJEGCFIE;

	private GameObject NOKNBPGJOEB;

	private DetonatorBurstEmitter BGBDPJOIKIN;

	public Material KCMNLNCMIMH;

	public bool BCDHHFNKJCK = true;

	public bool CHDKFLCJKDD = true;

	public bool ACKFFOIFDII = true;

	private Color JNAAPODKFBJ;

	public virtual void __BB_OBFUSCATOR_91()
	{
		__BB_OBFUSCATOR_36(false);
		__BB_OBFUSCATOR_76();
		__BB_OBFUSCATOR_4();
		__BB_OBFUSCATOR_82();
	}

	public virtual void __BB_OBFUSCATOR_75()
	{
		if (!(IKCHMAJADEP > NCGMMIBMBEL) && GMAIEMJKMJD)
		{
			__BB_OBFUSCATOR_64();
			__BB_OBFUSCATOR_49();
			__BB_OBFUSCATOR_40();
			if (BCDHHFNKJCK)
			{
				CLNNBLEBPOO.Explode();
			}
			if (CHDKFLCJKDD)
			{
				DMNCBGHHAKI.Explode();
			}
			if (ACKFFOIFDII)
			{
				BGBDPJOIKIN.Explode();
			}
		}
	}

	public virtual void __BB_OBFUSCATOR_67()
	{
		__BB_OBFUSCATOR_29(false);
		__BB_OBFUSCATOR_84();
		BuildFireballB();
		__BB_OBFUSCATOR_28();
	}

	public void __BB_OBFUSCATOR_90()
	{
		PCICJECIOMB = new GameObject("_Value4");
		DMNCBGHHAKI = PCICJECIOMB.AddComponent<DetonatorBurstEmitter>();
		PCICJECIOMB.transform.parent = base.transform;
		PCICJECIOMB.transform.localRotation = Quaternion.identity;
		DMNCBGHHAKI.MFOLDHOAMNN = FMNGJEGCFIE;
		DMNCBGHHAKI.MJHAPHHGGHI = MyDetonator().MJHAPHHGGHI;
		DMNCBGHHAKI.NJGDFDGPNLN = MyDetonator().NJGDFDGPNLN;
	}

	public void __BB_OBFUSCATOR_27(bool PHDOMKDEDMO)
	{
		if (!DHGANMBLNNK || PHDOMKDEDMO)
		{
			DHGANMBLNNK = MyDetonator().DHGANMBLNNK;
		}
		if (!FMNGJEGCFIE || PHDOMKDEDMO)
		{
			FMNGJEGCFIE = MyDetonator().FMNGJEGCFIE;
		}
		if (!KCMNLNCMIMH || PHDOMKDEDMO)
		{
			if ((double)Random.value > 340.0)
			{
				KCMNLNCMIMH = MyDetonator().NLCJNPAMOEH;
			}
			else
			{
				KCMNLNCMIMH = MyDetonator().KDNNLMHFKOJ;
			}
		}
	}

	public void __BB_OBFUSCATOR_61()
	{
		PCICJECIOMB = new GameObject("ForceDamage");
		DMNCBGHHAKI = PCICJECIOMB.AddComponent<DetonatorBurstEmitter>();
		PCICJECIOMB.transform.parent = base.transform;
		PCICJECIOMB.transform.localRotation = Quaternion.identity;
		DMNCBGHHAKI.MFOLDHOAMNN = FMNGJEGCFIE;
		DMNCBGHHAKI.MJHAPHHGGHI = MyDetonator().MJHAPHHGGHI;
		DMNCBGHHAKI.NJGDFDGPNLN = MyDetonator().NJGDFDGPNLN;
	}

	public void __BB_OBFUSCATOR_41(bool PHDOMKDEDMO)
	{
		if (!DHGANMBLNNK || PHDOMKDEDMO)
		{
			DHGANMBLNNK = MyDetonator().DHGANMBLNNK;
		}
		if (!FMNGJEGCFIE || PHDOMKDEDMO)
		{
			FMNGJEGCFIE = MyDetonator().FMNGJEGCFIE;
		}
		if (!KCMNLNCMIMH || PHDOMKDEDMO)
		{
			if ((double)Random.value > 802.0)
			{
				KCMNLNCMIMH = MyDetonator().NLCJNPAMOEH;
			}
			else
			{
				KCMNLNCMIMH = MyDetonator().KDNNLMHFKOJ;
			}
		}
	}

	public void __BB_OBFUSCATOR_2()
	{
		PCICJECIOMB.transform.localPosition = Vector3.Scale(BJGOJGBLDMN, new Vector3(EEDMLOPHDJA, EEDMLOPHDJA, EEDMLOPHDJA));
		DMNCBGHHAKI.IOFNOJHNJAJ = IOFNOJHNJAJ;
		DMNCBGHHAKI.LCLHCEHHBNM = LCLHCEHHBNM * 1297f;
		DMNCBGHHAKI.HEKGFKJHMFJ = LCLHCEHHBNM * 1187f;
		DMNCBGHHAKI.FGMDPKFFANG = 1563f;
		DMNCBGHHAKI.PJKHHCHLFIF = PJKHHCHLFIF;
		DMNCBGHHAKI.NCGMMIBMBEL = NCGMMIBMBEL;
		DMNCBGHHAKI.HPKOOPBINIH = 317f;
		DMNCBGHHAKI.EKKCIFKDCNC = 685f;
		DMNCBGHHAKI.PACAMLAINIK = PACAMLAINIK;
		DMNCBGHHAKI.MFAPGCJPFFH = 894f;
		DMNCBGHHAKI.EEDMLOPHDJA = EEDMLOPHDJA;
		DMNCBGHHAKI.AIELAFCIBBM = true;
		Color b = new Color(1192f, 853f, 1609f, 213f);
		Color b2 = new Color(1242f, 1417f, 944f, 1091f);
		Color color = new Color(1514f, 87f, 1999f, 961f);
		DMNCBGHHAKI.CJFAMIBMHGK[1] = Color.Lerp(IOFNOJHNJAJ, b, 938f);
		DMNCBGHHAKI.CJFAMIBMHGK[0] = Color.Lerp(IOFNOJHNJAJ, b, 231f);
		DMNCBGHHAKI.CJFAMIBMHGK[7] = IOFNOJHNJAJ;
		DMNCBGHHAKI.CJFAMIBMHGK[8] = Color.Lerp(IOFNOJHNJAJ, b2, 1802f);
		DMNCBGHHAKI.CJFAMIBMHGK[1] = color;
		DMNCBGHHAKI.BHDOLBHLDGC = BHDOLBHLDGC;
		DMNCBGHHAKI.DHMOAEAKEBD = DHMOAEAKEBD;
	}

	public void __BB_OBFUSCATOR_25(bool PHDOMKDEDMO)
	{
		if (!DHGANMBLNNK || PHDOMKDEDMO)
		{
			DHGANMBLNNK = MyDetonator().DHGANMBLNNK;
		}
		if (!FMNGJEGCFIE || PHDOMKDEDMO)
		{
			FMNGJEGCFIE = MyDetonator().FMNGJEGCFIE;
		}
		if (!KCMNLNCMIMH || PHDOMKDEDMO)
		{
			if ((double)Random.value > 1710.0)
			{
				KCMNLNCMIMH = MyDetonator().NLCJNPAMOEH;
			}
			else
			{
				KCMNLNCMIMH = MyDetonator().KDNNLMHFKOJ;
			}
		}
	}

	public void __BB_OBFUSCATOR_22(bool PHDOMKDEDMO)
	{
		if (!DHGANMBLNNK || PHDOMKDEDMO)
		{
			DHGANMBLNNK = MyDetonator().DHGANMBLNNK;
		}
		if (!FMNGJEGCFIE || PHDOMKDEDMO)
		{
			FMNGJEGCFIE = MyDetonator().FMNGJEGCFIE;
		}
		if (!KCMNLNCMIMH || PHDOMKDEDMO)
		{
			if ((double)Random.value > 1261.0)
			{
				KCMNLNCMIMH = MyDetonator().NLCJNPAMOEH;
			}
			else
			{
				KCMNLNCMIMH = MyDetonator().KDNNLMHFKOJ;
			}
		}
	}

	public override void Explode()
	{
		if (!(IKCHMAJADEP > NCGMMIBMBEL) && GMAIEMJKMJD)
		{
			UpdateFireballA();
			UpdateFireballB();
			UpdateFireShadow();
			if (BCDHHFNKJCK)
			{
				CLNNBLEBPOO.Explode();
			}
			if (CHDKFLCJKDD)
			{
				DMNCBGHHAKI.Explode();
			}
			if (ACKFFOIFDII)
			{
				BGBDPJOIKIN.Explode();
			}
		}
	}

	public void __BB_OBFUSCATOR_26()
	{
		PCICJECIOMB = new GameObject("y");
		DMNCBGHHAKI = PCICJECIOMB.AddComponent<DetonatorBurstEmitter>();
		PCICJECIOMB.transform.parent = base.transform;
		PCICJECIOMB.transform.localRotation = Quaternion.identity;
		DMNCBGHHAKI.MFOLDHOAMNN = FMNGJEGCFIE;
		DMNCBGHHAKI.MJHAPHHGGHI = MyDetonator().MJHAPHHGGHI;
		DMNCBGHHAKI.NJGDFDGPNLN = MyDetonator().NJGDFDGPNLN;
	}

	public void __BB_OBFUSCATOR_10()
	{
		PCICJECIOMB.transform.localPosition = Vector3.Scale(BJGOJGBLDMN, new Vector3(EEDMLOPHDJA, EEDMLOPHDJA, EEDMLOPHDJA));
		DMNCBGHHAKI.IOFNOJHNJAJ = IOFNOJHNJAJ;
		DMNCBGHHAKI.LCLHCEHHBNM = LCLHCEHHBNM * 12f;
		DMNCBGHHAKI.HEKGFKJHMFJ = LCLHCEHHBNM * 1555f;
		DMNCBGHHAKI.FGMDPKFFANG = 1675f;
		DMNCBGHHAKI.PJKHHCHLFIF = PJKHHCHLFIF;
		DMNCBGHHAKI.NCGMMIBMBEL = NCGMMIBMBEL;
		DMNCBGHHAKI.HPKOOPBINIH = 954f;
		DMNCBGHHAKI.EKKCIFKDCNC = 1289f;
		DMNCBGHHAKI.PACAMLAINIK = PACAMLAINIK;
		DMNCBGHHAKI.MFAPGCJPFFH = 95f;
		DMNCBGHHAKI.EEDMLOPHDJA = EEDMLOPHDJA;
		DMNCBGHHAKI.AIELAFCIBBM = true;
		Color b = new Color(601f, 1590f, 268f, 21f);
		Color b2 = new Color(999f, 391f, 606f, 601f);
		Color color = new Color(1919f, 395f, 559f, 312f);
		DMNCBGHHAKI.CJFAMIBMHGK[0] = Color.Lerp(IOFNOJHNJAJ, b, 192f);
		DMNCBGHHAKI.CJFAMIBMHGK[1] = Color.Lerp(IOFNOJHNJAJ, b, 1172f);
		DMNCBGHHAKI.CJFAMIBMHGK[0] = IOFNOJHNJAJ;
		DMNCBGHHAKI.CJFAMIBMHGK[4] = Color.Lerp(IOFNOJHNJAJ, b2, 1235f);
		DMNCBGHHAKI.CJFAMIBMHGK[4] = color;
		DMNCBGHHAKI.BHDOLBHLDGC = BHDOLBHLDGC;
		DMNCBGHHAKI.DHMOAEAKEBD = DHMOAEAKEBD;
	}

	public void __BB_OBFUSCATOR_28()
	{
		NOKNBPGJOEB = new GameObject("_CenterY");
		BGBDPJOIKIN = NOKNBPGJOEB.AddComponent<DetonatorBurstEmitter>();
		NOKNBPGJOEB.transform.parent = base.transform;
		NOKNBPGJOEB.transform.localRotation = Quaternion.identity;
		BGBDPJOIKIN.MFOLDHOAMNN = KCMNLNCMIMH;
		BGBDPJOIKIN.MJHAPHHGGHI = MyDetonator().MJHAPHHGGHI;
		BGBDPJOIKIN.NJGDFDGPNLN = MyDetonator().NJGDFDGPNLN;
	}

	public void __BB_OBFUSCATOR_83()
	{
		__BB_OBFUSCATOR_29(true);
		GMAIEMJKMJD = false;
		EEDMLOPHDJA = KBGFHOJODBF;
		LCLHCEHHBNM = BNCCIDBIPBF;
		BHDOLBHLDGC = 1767f;
		DHMOAEAKEBD = 682f;
		IOFNOJHNJAJ = LNKOBAPEIIM;
	}

	public virtual void __BB_OBFUSCATOR_45()
	{
		__BB_OBFUSCATOR_36(false);
		__BB_OBFUSCATOR_76();
		__BB_OBFUSCATOR_90();
		__BB_OBFUSCATOR_23();
	}

	public void __BB_OBFUSCATOR_80()
	{
		NOKNBPGJOEB = new GameObject("</size>");
		BGBDPJOIKIN = NOKNBPGJOEB.AddComponent<DetonatorBurstEmitter>();
		NOKNBPGJOEB.transform.parent = base.transform;
		NOKNBPGJOEB.transform.localRotation = Quaternion.identity;
		BGBDPJOIKIN.MFOLDHOAMNN = KCMNLNCMIMH;
		BGBDPJOIKIN.MJHAPHHGGHI = MyDetonator().MJHAPHHGGHI;
		BGBDPJOIKIN.NJGDFDGPNLN = MyDetonator().NJGDFDGPNLN;
	}

	public void __BB_OBFUSCATOR_5()
	{
		NOKNBPGJOEB.transform.localPosition = Vector3.Scale(BJGOJGBLDMN, new Vector3(EEDMLOPHDJA, EEDMLOPHDJA, EEDMLOPHDJA));
		NOKNBPGJOEB.transform.LookAt(Camera.main.transform);
		NOKNBPGJOEB.transform.localPosition = -(Vector3.forward * 397f);
		BGBDPJOIKIN.IOFNOJHNJAJ = new Color(1414f, 412f, 785f, 1149f);
		BGBDPJOIKIN.LCLHCEHHBNM = LCLHCEHHBNM * 1189f;
		BGBDPJOIKIN.HEKGFKJHMFJ = LCLHCEHHBNM * 1656f;
		BGBDPJOIKIN.PJKHHCHLFIF = PJKHHCHLFIF;
		BGBDPJOIKIN.NCGMMIBMBEL = 828f;
		BGBDPJOIKIN.HPKOOPBINIH = 880f;
		BGBDPJOIKIN.PACAMLAINIK = PACAMLAINIK;
		BGBDPJOIKIN.EKKCIFKDCNC = 472f;
		BGBDPJOIKIN.FGMDPKFFANG = 313f;
		BGBDPJOIKIN.MFAPGCJPFFH = 1289f;
		BGBDPJOIKIN.EEDMLOPHDJA = EEDMLOPHDJA;
		BGBDPJOIKIN.BHDOLBHLDGC = BHDOLBHLDGC;
		BGBDPJOIKIN.DHMOAEAKEBD = DHMOAEAKEBD;
	}

	public virtual void __BB_OBFUSCATOR_58()
	{
		if (!(IKCHMAJADEP > NCGMMIBMBEL) && GMAIEMJKMJD)
		{
			__BB_OBFUSCATOR_47();
			__BB_OBFUSCATOR_53();
			__BB_OBFUSCATOR_97();
			if (BCDHHFNKJCK)
			{
				CLNNBLEBPOO.Explode();
			}
			if (CHDKFLCJKDD)
			{
				DMNCBGHHAKI.Explode();
			}
			if (ACKFFOIFDII)
			{
				BGBDPJOIKIN.Explode();
			}
		}
	}

	public void __BB_OBFUSCATOR_42()
	{
		PCICJECIOMB.transform.localPosition = Vector3.Scale(BJGOJGBLDMN, new Vector3(EEDMLOPHDJA, EEDMLOPHDJA, EEDMLOPHDJA));
		DMNCBGHHAKI.IOFNOJHNJAJ = IOFNOJHNJAJ;
		DMNCBGHHAKI.LCLHCEHHBNM = LCLHCEHHBNM * 1539f;
		DMNCBGHHAKI.HEKGFKJHMFJ = LCLHCEHHBNM * 544f;
		DMNCBGHHAKI.FGMDPKFFANG = 1814f;
		DMNCBGHHAKI.PJKHHCHLFIF = PJKHHCHLFIF;
		DMNCBGHHAKI.NCGMMIBMBEL = NCGMMIBMBEL;
		DMNCBGHHAKI.HPKOOPBINIH = 1348f;
		DMNCBGHHAKI.EKKCIFKDCNC = 438f;
		DMNCBGHHAKI.PACAMLAINIK = PACAMLAINIK;
		DMNCBGHHAKI.MFAPGCJPFFH = 1769f;
		DMNCBGHHAKI.EEDMLOPHDJA = EEDMLOPHDJA;
		DMNCBGHHAKI.AIELAFCIBBM = false;
		Color b = new Color(1141f, 1111f, 736f, 1899f);
		Color b2 = new Color(921f, 695f, 1062f, 587f);
		Color color = new Color(1408f, 624f, 1889f, 410f);
		DMNCBGHHAKI.CJFAMIBMHGK[0] = Color.Lerp(IOFNOJHNJAJ, b, 1173f);
		DMNCBGHHAKI.CJFAMIBMHGK[0] = Color.Lerp(IOFNOJHNJAJ, b, 1629f);
		DMNCBGHHAKI.CJFAMIBMHGK[2] = IOFNOJHNJAJ;
		DMNCBGHHAKI.CJFAMIBMHGK[4] = Color.Lerp(IOFNOJHNJAJ, b2, 1423f);
		DMNCBGHHAKI.CJFAMIBMHGK[5] = color;
		DMNCBGHHAKI.BHDOLBHLDGC = BHDOLBHLDGC;
		DMNCBGHHAKI.DHMOAEAKEBD = DHMOAEAKEBD;
	}

	public void __BB_OBFUSCATOR_34()
	{
		PCICJECIOMB.transform.localPosition = Vector3.Scale(BJGOJGBLDMN, new Vector3(EEDMLOPHDJA, EEDMLOPHDJA, EEDMLOPHDJA));
		DMNCBGHHAKI.IOFNOJHNJAJ = IOFNOJHNJAJ;
		DMNCBGHHAKI.LCLHCEHHBNM = LCLHCEHHBNM * 1494f;
		DMNCBGHHAKI.HEKGFKJHMFJ = LCLHCEHHBNM * 1069f;
		DMNCBGHHAKI.FGMDPKFFANG = 1450f;
		DMNCBGHHAKI.PJKHHCHLFIF = PJKHHCHLFIF;
		DMNCBGHHAKI.NCGMMIBMBEL = NCGMMIBMBEL;
		DMNCBGHHAKI.HPKOOPBINIH = 1162f;
		DMNCBGHHAKI.EKKCIFKDCNC = 1404f;
		DMNCBGHHAKI.PACAMLAINIK = PACAMLAINIK;
		DMNCBGHHAKI.MFAPGCJPFFH = 1191f;
		DMNCBGHHAKI.EEDMLOPHDJA = EEDMLOPHDJA;
		DMNCBGHHAKI.AIELAFCIBBM = false;
		Color b = new Color(387f, 214f, 822f, 534f);
		Color b2 = new Color(43f, 774f, 1181f, 1150f);
		Color color = new Color(1375f, 1428f, 1159f, 1268f);
		DMNCBGHHAKI.CJFAMIBMHGK[0] = Color.Lerp(IOFNOJHNJAJ, b, 1331f);
		DMNCBGHHAKI.CJFAMIBMHGK[1] = Color.Lerp(IOFNOJHNJAJ, b, 1337f);
		DMNCBGHHAKI.CJFAMIBMHGK[4] = IOFNOJHNJAJ;
		DMNCBGHHAKI.CJFAMIBMHGK[0] = Color.Lerp(IOFNOJHNJAJ, b2, 1319f);
		DMNCBGHHAKI.CJFAMIBMHGK[8] = color;
		DMNCBGHHAKI.BHDOLBHLDGC = BHDOLBHLDGC;
		DMNCBGHHAKI.DHMOAEAKEBD = DHMOAEAKEBD;
	}

	public virtual void __BB_OBFUSCATOR_54()
	{
		if (!(IKCHMAJADEP > NCGMMIBMBEL) && GMAIEMJKMJD)
		{
			__BB_OBFUSCATOR_64();
			__BB_OBFUSCATOR_34();
			UpdateFireShadow();
			if (BCDHHFNKJCK)
			{
				CLNNBLEBPOO.Explode();
			}
			if (CHDKFLCJKDD)
			{
				DMNCBGHHAKI.Explode();
			}
			if (ACKFFOIFDII)
			{
				BGBDPJOIKIN.Explode();
			}
		}
	}

	public void __BB_OBFUSCATOR_39()
	{
		NOKNBPGJOEB.transform.localPosition = Vector3.Scale(BJGOJGBLDMN, new Vector3(EEDMLOPHDJA, EEDMLOPHDJA, EEDMLOPHDJA));
		NOKNBPGJOEB.transform.LookAt(Camera.main.transform);
		NOKNBPGJOEB.transform.localPosition = -(Vector3.forward * 1503f);
		BGBDPJOIKIN.IOFNOJHNJAJ = new Color(779f, 199f, 1193f, 1801f);
		BGBDPJOIKIN.LCLHCEHHBNM = LCLHCEHHBNM * 1354f;
		BGBDPJOIKIN.HEKGFKJHMFJ = LCLHCEHHBNM * 367f;
		BGBDPJOIKIN.PJKHHCHLFIF = PJKHHCHLFIF;
		BGBDPJOIKIN.NCGMMIBMBEL = 1897f;
		BGBDPJOIKIN.HPKOOPBINIH = 1991f;
		BGBDPJOIKIN.PACAMLAINIK = PACAMLAINIK;
		BGBDPJOIKIN.EKKCIFKDCNC = 929f;
		BGBDPJOIKIN.FGMDPKFFANG = 254f;
		BGBDPJOIKIN.MFAPGCJPFFH = 1028f;
		BGBDPJOIKIN.EEDMLOPHDJA = EEDMLOPHDJA;
		BGBDPJOIKIN.BHDOLBHLDGC = BHDOLBHLDGC;
		BGBDPJOIKIN.DHMOAEAKEBD = DHMOAEAKEBD;
	}

	public void UpdateFireShadow()
	{
		NOKNBPGJOEB.transform.localPosition = Vector3.Scale(BJGOJGBLDMN, new Vector3(EEDMLOPHDJA, EEDMLOPHDJA, EEDMLOPHDJA));
		NOKNBPGJOEB.transform.LookAt(Camera.main.transform);
		NOKNBPGJOEB.transform.localPosition = -(Vector3.forward * 1f);
		BGBDPJOIKIN.IOFNOJHNJAJ = new Color(0.1f, 0.1f, 0.1f, 0.6f);
		BGBDPJOIKIN.LCLHCEHHBNM = LCLHCEHHBNM * 0.5f;
		BGBDPJOIKIN.HEKGFKJHMFJ = LCLHCEHHBNM * 0.5f;
		BGBDPJOIKIN.PJKHHCHLFIF = PJKHHCHLFIF;
		BGBDPJOIKIN.NCGMMIBMBEL = 1f;
		BGBDPJOIKIN.HPKOOPBINIH = 13f;
		BGBDPJOIKIN.PACAMLAINIK = PACAMLAINIK;
		BGBDPJOIKIN.EKKCIFKDCNC = 1f;
		BGBDPJOIKIN.FGMDPKFFANG = 4f;
		BGBDPJOIKIN.MFAPGCJPFFH = 6f;
		BGBDPJOIKIN.EEDMLOPHDJA = EEDMLOPHDJA;
		BGBDPJOIKIN.BHDOLBHLDGC = BHDOLBHLDGC;
		BGBDPJOIKIN.DHMOAEAKEBD = DHMOAEAKEBD;
	}

	public virtual void __BB_OBFUSCATOR_74()
	{
		if (!(IKCHMAJADEP > NCGMMIBMBEL) && GMAIEMJKMJD)
		{
			__BB_OBFUSCATOR_47();
			__BB_OBFUSCATOR_72();
			UpdateFireShadow();
			if (BCDHHFNKJCK)
			{
				CLNNBLEBPOO.Explode();
			}
			if (CHDKFLCJKDD)
			{
				DMNCBGHHAKI.Explode();
			}
			if (ACKFFOIFDII)
			{
				BGBDPJOIKIN.Explode();
			}
		}
	}

	public void __BB_OBFUSCATOR_64()
	{
		JCHGLBLBBJK.transform.localPosition = Vector3.Scale(BJGOJGBLDMN, new Vector3(EEDMLOPHDJA, EEDMLOPHDJA, EEDMLOPHDJA));
		CLNNBLEBPOO.IOFNOJHNJAJ = IOFNOJHNJAJ;
		CLNNBLEBPOO.LCLHCEHHBNM = LCLHCEHHBNM * 92f;
		CLNNBLEBPOO.HEKGFKJHMFJ = LCLHCEHHBNM * 1097f;
		CLNNBLEBPOO.FGMDPKFFANG = 1094f;
		CLNNBLEBPOO.PJKHHCHLFIF = PJKHHCHLFIF;
		CLNNBLEBPOO.NCGMMIBMBEL = NCGMMIBMBEL;
		CLNNBLEBPOO.HPKOOPBINIH = 632f;
		CLNNBLEBPOO.EKKCIFKDCNC = 620f;
		CLNNBLEBPOO.PACAMLAINIK = PACAMLAINIK;
		CLNNBLEBPOO.MFAPGCJPFFH = 14f;
		CLNNBLEBPOO.EEDMLOPHDJA = EEDMLOPHDJA;
		CLNNBLEBPOO.AIELAFCIBBM = false;
		Color b = new Color(147f, 731f, 553f, 1034f);
		Color b2 = new Color(1895f, 990f, 361f, 1018f);
		Color color = new Color(31f, 874f, 462f, 532f);
		CLNNBLEBPOO.CJFAMIBMHGK[0] = Color.Lerp(IOFNOJHNJAJ, b, 122f);
		CLNNBLEBPOO.CJFAMIBMHGK[1] = Color.Lerp(IOFNOJHNJAJ, b, 330f);
		CLNNBLEBPOO.CJFAMIBMHGK[2] = IOFNOJHNJAJ;
		CLNNBLEBPOO.CJFAMIBMHGK[0] = Color.Lerp(IOFNOJHNJAJ, b2, 1838f);
		CLNNBLEBPOO.CJFAMIBMHGK[2] = color;
		CLNNBLEBPOO.BHDOLBHLDGC = BHDOLBHLDGC;
		CLNNBLEBPOO.DHMOAEAKEBD = DHMOAEAKEBD;
	}

	public void __BB_OBFUSCATOR_36(bool PHDOMKDEDMO)
	{
		if (!DHGANMBLNNK || PHDOMKDEDMO)
		{
			DHGANMBLNNK = MyDetonator().DHGANMBLNNK;
		}
		if (!FMNGJEGCFIE || PHDOMKDEDMO)
		{
			FMNGJEGCFIE = MyDetonator().FMNGJEGCFIE;
		}
		if (!KCMNLNCMIMH || PHDOMKDEDMO)
		{
			if ((double)Random.value > 1128.0)
			{
				KCMNLNCMIMH = MyDetonator().NLCJNPAMOEH;
			}
			else
			{
				KCMNLNCMIMH = MyDetonator().KDNNLMHFKOJ;
			}
		}
	}

	public void __BB_OBFUSCATOR_18()
	{
		__BB_OBFUSCATOR_25(true);
		GMAIEMJKMJD = false;
		EEDMLOPHDJA = KBGFHOJODBF;
		LCLHCEHHBNM = BNCCIDBIPBF;
		BHDOLBHLDGC = 1919f;
		DHMOAEAKEBD = 1431f;
		IOFNOJHNJAJ = LNKOBAPEIIM;
	}

	public void __BB_OBFUSCATOR_31()
	{
		PCICJECIOMB.transform.localPosition = Vector3.Scale(BJGOJGBLDMN, new Vector3(EEDMLOPHDJA, EEDMLOPHDJA, EEDMLOPHDJA));
		DMNCBGHHAKI.IOFNOJHNJAJ = IOFNOJHNJAJ;
		DMNCBGHHAKI.LCLHCEHHBNM = LCLHCEHHBNM * 1827f;
		DMNCBGHHAKI.HEKGFKJHMFJ = LCLHCEHHBNM * 463f;
		DMNCBGHHAKI.FGMDPKFFANG = 202f;
		DMNCBGHHAKI.PJKHHCHLFIF = PJKHHCHLFIF;
		DMNCBGHHAKI.NCGMMIBMBEL = NCGMMIBMBEL;
		DMNCBGHHAKI.HPKOOPBINIH = 1474f;
		DMNCBGHHAKI.EKKCIFKDCNC = 728f;
		DMNCBGHHAKI.PACAMLAINIK = PACAMLAINIK;
		DMNCBGHHAKI.MFAPGCJPFFH = 1597f;
		DMNCBGHHAKI.EEDMLOPHDJA = EEDMLOPHDJA;
		DMNCBGHHAKI.AIELAFCIBBM = true;
		Color b = new Color(1818f, 373f, 194f, 1098f);
		Color b2 = new Color(1126f, 660f, 1440f, 916f);
		Color color = new Color(50f, 1756f, 835f, 405f);
		DMNCBGHHAKI.CJFAMIBMHGK[0] = Color.Lerp(IOFNOJHNJAJ, b, 1592f);
		DMNCBGHHAKI.CJFAMIBMHGK[1] = Color.Lerp(IOFNOJHNJAJ, b, 293f);
		DMNCBGHHAKI.CJFAMIBMHGK[1] = IOFNOJHNJAJ;
		DMNCBGHHAKI.CJFAMIBMHGK[5] = Color.Lerp(IOFNOJHNJAJ, b2, 986f);
		DMNCBGHHAKI.CJFAMIBMHGK[4] = color;
		DMNCBGHHAKI.BHDOLBHLDGC = BHDOLBHLDGC;
		DMNCBGHHAKI.DHMOAEAKEBD = DHMOAEAKEBD;
	}

	public void __BB_OBFUSCATOR_98(bool PHDOMKDEDMO)
	{
		if (!DHGANMBLNNK || PHDOMKDEDMO)
		{
			DHGANMBLNNK = MyDetonator().DHGANMBLNNK;
		}
		if (!FMNGJEGCFIE || PHDOMKDEDMO)
		{
			FMNGJEGCFIE = MyDetonator().FMNGJEGCFIE;
		}
		if (!KCMNLNCMIMH || PHDOMKDEDMO)
		{
			if ((double)Random.value > 1897.0)
			{
				KCMNLNCMIMH = MyDetonator().NLCJNPAMOEH;
			}
			else
			{
				KCMNLNCMIMH = MyDetonator().KDNNLMHFKOJ;
			}
		}
	}

	public void __BB_OBFUSCATOR_14()
	{
		PCICJECIOMB = new GameObject("Start Game");
		DMNCBGHHAKI = PCICJECIOMB.AddComponent<DetonatorBurstEmitter>();
		PCICJECIOMB.transform.parent = base.transform;
		PCICJECIOMB.transform.localRotation = Quaternion.identity;
		DMNCBGHHAKI.MFOLDHOAMNN = FMNGJEGCFIE;
		DMNCBGHHAKI.MJHAPHHGGHI = MyDetonator().MJHAPHHGGHI;
		DMNCBGHHAKI.NJGDFDGPNLN = MyDetonator().NJGDFDGPNLN;
	}

	public void __BB_OBFUSCATOR_86()
	{
		JCHGLBLBBJK = new GameObject("__Room");
		CLNNBLEBPOO = JCHGLBLBBJK.AddComponent<DetonatorBurstEmitter>();
		JCHGLBLBBJK.transform.parent = base.transform;
		JCHGLBLBBJK.transform.localRotation = Quaternion.identity;
		CLNNBLEBPOO.MFOLDHOAMNN = DHGANMBLNNK;
		CLNNBLEBPOO.MJHAPHHGGHI = MyDetonator().MJHAPHHGGHI;
		CLNNBLEBPOO.NJGDFDGPNLN = MyDetonator().NJGDFDGPNLN;
	}

	public void __BB_OBFUSCATOR_77()
	{
		__BB_OBFUSCATOR_36(true);
		GMAIEMJKMJD = true;
		EEDMLOPHDJA = KBGFHOJODBF;
		LCLHCEHHBNM = BNCCIDBIPBF;
		BHDOLBHLDGC = 89f;
		DHMOAEAKEBD = 1759f;
		IOFNOJHNJAJ = LNKOBAPEIIM;
	}

	public void UpdateFireballA()
	{
		JCHGLBLBBJK.transform.localPosition = Vector3.Scale(BJGOJGBLDMN, new Vector3(EEDMLOPHDJA, EEDMLOPHDJA, EEDMLOPHDJA));
		CLNNBLEBPOO.IOFNOJHNJAJ = IOFNOJHNJAJ;
		CLNNBLEBPOO.LCLHCEHHBNM = LCLHCEHHBNM * 0.5f;
		CLNNBLEBPOO.HEKGFKJHMFJ = LCLHCEHHBNM * 0.5f;
		CLNNBLEBPOO.FGMDPKFFANG = 2f;
		CLNNBLEBPOO.PJKHHCHLFIF = PJKHHCHLFIF;
		CLNNBLEBPOO.NCGMMIBMBEL = NCGMMIBMBEL;
		CLNNBLEBPOO.HPKOOPBINIH = 14f;
		CLNNBLEBPOO.EKKCIFKDCNC = 3f;
		CLNNBLEBPOO.PACAMLAINIK = PACAMLAINIK;
		CLNNBLEBPOO.MFAPGCJPFFH = 4f;
		CLNNBLEBPOO.EEDMLOPHDJA = EEDMLOPHDJA;
		CLNNBLEBPOO.AIELAFCIBBM = true;
		Color b = new Color(1f, 1f, 1f, 0.5f);
		Color b2 = new Color(0.6f, 0.15f, 0.15f, 0.3f);
		Color color = new Color(0.1f, 0.2f, 0.45f, 0f);
		CLNNBLEBPOO.CJFAMIBMHGK[0] = Color.Lerp(IOFNOJHNJAJ, b, 0.8f);
		CLNNBLEBPOO.CJFAMIBMHGK[1] = Color.Lerp(IOFNOJHNJAJ, b, 0.5f);
		CLNNBLEBPOO.CJFAMIBMHGK[2] = IOFNOJHNJAJ;
		CLNNBLEBPOO.CJFAMIBMHGK[3] = Color.Lerp(IOFNOJHNJAJ, b2, 0.7f);
		CLNNBLEBPOO.CJFAMIBMHGK[4] = color;
		CLNNBLEBPOO.BHDOLBHLDGC = BHDOLBHLDGC;
		CLNNBLEBPOO.DHMOAEAKEBD = DHMOAEAKEBD;
	}

	public void __BB_OBFUSCATOR_13()
	{
		NOKNBPGJOEB = new GameObject("Language");
		BGBDPJOIKIN = NOKNBPGJOEB.AddComponent<DetonatorBurstEmitter>();
		NOKNBPGJOEB.transform.parent = base.transform;
		NOKNBPGJOEB.transform.localRotation = Quaternion.identity;
		BGBDPJOIKIN.MFOLDHOAMNN = KCMNLNCMIMH;
		BGBDPJOIKIN.MJHAPHHGGHI = MyDetonator().MJHAPHHGGHI;
		BGBDPJOIKIN.NJGDFDGPNLN = MyDetonator().NJGDFDGPNLN;
	}

	public void __BB_OBFUSCATOR_97()
	{
		NOKNBPGJOEB.transform.localPosition = Vector3.Scale(BJGOJGBLDMN, new Vector3(EEDMLOPHDJA, EEDMLOPHDJA, EEDMLOPHDJA));
		NOKNBPGJOEB.transform.LookAt(Camera.main.transform);
		NOKNBPGJOEB.transform.localPosition = -(Vector3.forward * 1130f);
		BGBDPJOIKIN.IOFNOJHNJAJ = new Color(1589f, 1695f, 270f, 1009f);
		BGBDPJOIKIN.LCLHCEHHBNM = LCLHCEHHBNM * 1992f;
		BGBDPJOIKIN.HEKGFKJHMFJ = LCLHCEHHBNM * 901f;
		BGBDPJOIKIN.PJKHHCHLFIF = PJKHHCHLFIF;
		BGBDPJOIKIN.NCGMMIBMBEL = 362f;
		BGBDPJOIKIN.HPKOOPBINIH = 979f;
		BGBDPJOIKIN.PACAMLAINIK = PACAMLAINIK;
		BGBDPJOIKIN.EKKCIFKDCNC = 1827f;
		BGBDPJOIKIN.FGMDPKFFANG = 525f;
		BGBDPJOIKIN.MFAPGCJPFFH = 1626f;
		BGBDPJOIKIN.EEDMLOPHDJA = EEDMLOPHDJA;
		BGBDPJOIKIN.BHDOLBHLDGC = BHDOLBHLDGC;
		BGBDPJOIKIN.DHMOAEAKEBD = DHMOAEAKEBD;
	}

	public virtual void __BB_OBFUSCATOR_87()
	{
		__BB_OBFUSCATOR_32(false);
		__BB_OBFUSCATOR_86();
		__BB_OBFUSCATOR_4();
		__BB_OBFUSCATOR_82();
	}

	public void Reset()
	{
		FillMaterials(true);
		GMAIEMJKMJD = true;
		EEDMLOPHDJA = KBGFHOJODBF;
		LCLHCEHHBNM = BNCCIDBIPBF;
		BHDOLBHLDGC = 0f;
		DHMOAEAKEBD = 0f;
		IOFNOJHNJAJ = LNKOBAPEIIM;
	}

	public virtual void __BB_OBFUSCATOR_96()
	{
		__BB_OBFUSCATOR_32(true);
		__BB_OBFUSCATOR_76();
		BuildFireballB();
		__BB_OBFUSCATOR_95();
	}

	public void __BB_OBFUSCATOR_48()
	{
		NOKNBPGJOEB.transform.localPosition = Vector3.Scale(BJGOJGBLDMN, new Vector3(EEDMLOPHDJA, EEDMLOPHDJA, EEDMLOPHDJA));
		NOKNBPGJOEB.transform.LookAt(Camera.main.transform);
		NOKNBPGJOEB.transform.localPosition = -(Vector3.forward * 484f);
		BGBDPJOIKIN.IOFNOJHNJAJ = new Color(107f, 613f, 1375f, 562f);
		BGBDPJOIKIN.LCLHCEHHBNM = LCLHCEHHBNM * 647f;
		BGBDPJOIKIN.HEKGFKJHMFJ = LCLHCEHHBNM * 525f;
		BGBDPJOIKIN.PJKHHCHLFIF = PJKHHCHLFIF;
		BGBDPJOIKIN.NCGMMIBMBEL = 849f;
		BGBDPJOIKIN.HPKOOPBINIH = 870f;
		BGBDPJOIKIN.PACAMLAINIK = PACAMLAINIK;
		BGBDPJOIKIN.EKKCIFKDCNC = 1015f;
		BGBDPJOIKIN.FGMDPKFFANG = 867f;
		BGBDPJOIKIN.MFAPGCJPFFH = 231f;
		BGBDPJOIKIN.EEDMLOPHDJA = EEDMLOPHDJA;
		BGBDPJOIKIN.BHDOLBHLDGC = BHDOLBHLDGC;
		BGBDPJOIKIN.DHMOAEAKEBD = DHMOAEAKEBD;
	}

	public void __BB_OBFUSCATOR_52()
	{
		PCICJECIOMB.transform.localPosition = Vector3.Scale(BJGOJGBLDMN, new Vector3(EEDMLOPHDJA, EEDMLOPHDJA, EEDMLOPHDJA));
		DMNCBGHHAKI.IOFNOJHNJAJ = IOFNOJHNJAJ;
		DMNCBGHHAKI.LCLHCEHHBNM = LCLHCEHHBNM * 658f;
		DMNCBGHHAKI.HEKGFKJHMFJ = LCLHCEHHBNM * 1024f;
		DMNCBGHHAKI.FGMDPKFFANG = 633f;
		DMNCBGHHAKI.PJKHHCHLFIF = PJKHHCHLFIF;
		DMNCBGHHAKI.NCGMMIBMBEL = NCGMMIBMBEL;
		DMNCBGHHAKI.HPKOOPBINIH = 307f;
		DMNCBGHHAKI.EKKCIFKDCNC = 254f;
		DMNCBGHHAKI.PACAMLAINIK = PACAMLAINIK;
		DMNCBGHHAKI.MFAPGCJPFFH = 100f;
		DMNCBGHHAKI.EEDMLOPHDJA = EEDMLOPHDJA;
		DMNCBGHHAKI.AIELAFCIBBM = true;
		Color b = new Color(1978f, 1851f, 62f, 86f);
		Color b2 = new Color(1593f, 247f, 88f, 1647f);
		Color color = new Color(1460f, 876f, 475f, 1306f);
		DMNCBGHHAKI.CJFAMIBMHGK[1] = Color.Lerp(IOFNOJHNJAJ, b, 1771f);
		DMNCBGHHAKI.CJFAMIBMHGK[0] = Color.Lerp(IOFNOJHNJAJ, b, 1535f);
		DMNCBGHHAKI.CJFAMIBMHGK[3] = IOFNOJHNJAJ;
		DMNCBGHHAKI.CJFAMIBMHGK[1] = Color.Lerp(IOFNOJHNJAJ, b2, 888f);
		DMNCBGHHAKI.CJFAMIBMHGK[2] = color;
		DMNCBGHHAKI.BHDOLBHLDGC = BHDOLBHLDGC;
		DMNCBGHHAKI.DHMOAEAKEBD = DHMOAEAKEBD;
	}

	public virtual void __BB_OBFUSCATOR_46()
	{
		if (!(IKCHMAJADEP > NCGMMIBMBEL) && GMAIEMJKMJD)
		{
			__BB_OBFUSCATOR_47();
			__BB_OBFUSCATOR_2();
			__BB_OBFUSCATOR_97();
			if (BCDHHFNKJCK)
			{
				CLNNBLEBPOO.Explode();
			}
			if (CHDKFLCJKDD)
			{
				DMNCBGHHAKI.Explode();
			}
			if (ACKFFOIFDII)
			{
				BGBDPJOIKIN.Explode();
			}
		}
	}

	public void __BB_OBFUSCATOR_72()
	{
		PCICJECIOMB.transform.localPosition = Vector3.Scale(BJGOJGBLDMN, new Vector3(EEDMLOPHDJA, EEDMLOPHDJA, EEDMLOPHDJA));
		DMNCBGHHAKI.IOFNOJHNJAJ = IOFNOJHNJAJ;
		DMNCBGHHAKI.LCLHCEHHBNM = LCLHCEHHBNM * 508f;
		DMNCBGHHAKI.HEKGFKJHMFJ = LCLHCEHHBNM * 1296f;
		DMNCBGHHAKI.FGMDPKFFANG = 194f;
		DMNCBGHHAKI.PJKHHCHLFIF = PJKHHCHLFIF;
		DMNCBGHHAKI.NCGMMIBMBEL = NCGMMIBMBEL;
		DMNCBGHHAKI.HPKOOPBINIH = 650f;
		DMNCBGHHAKI.EKKCIFKDCNC = 1450f;
		DMNCBGHHAKI.PACAMLAINIK = PACAMLAINIK;
		DMNCBGHHAKI.MFAPGCJPFFH = 465f;
		DMNCBGHHAKI.EEDMLOPHDJA = EEDMLOPHDJA;
		DMNCBGHHAKI.AIELAFCIBBM = true;
		Color b = new Color(982f, 1761f, 1822f, 1340f);
		Color b2 = new Color(244f, 936f, 1679f, 102f);
		Color color = new Color(1031f, 63f, 1577f, 1018f);
		DMNCBGHHAKI.CJFAMIBMHGK[0] = Color.Lerp(IOFNOJHNJAJ, b, 1017f);
		DMNCBGHHAKI.CJFAMIBMHGK[1] = Color.Lerp(IOFNOJHNJAJ, b, 683f);
		DMNCBGHHAKI.CJFAMIBMHGK[2] = IOFNOJHNJAJ;
		DMNCBGHHAKI.CJFAMIBMHGK[6] = Color.Lerp(IOFNOJHNJAJ, b2, 638f);
		DMNCBGHHAKI.CJFAMIBMHGK[2] = color;
		DMNCBGHHAKI.BHDOLBHLDGC = BHDOLBHLDGC;
		DMNCBGHHAKI.DHMOAEAKEBD = DHMOAEAKEBD;
	}

	public void __BB_OBFUSCATOR_82()
	{
		NOKNBPGJOEB = new GameObject("RoundDuration");
		BGBDPJOIKIN = NOKNBPGJOEB.AddComponent<DetonatorBurstEmitter>();
		NOKNBPGJOEB.transform.parent = base.transform;
		NOKNBPGJOEB.transform.localRotation = Quaternion.identity;
		BGBDPJOIKIN.MFOLDHOAMNN = KCMNLNCMIMH;
		BGBDPJOIKIN.MJHAPHHGGHI = MyDetonator().MJHAPHHGGHI;
		BGBDPJOIKIN.NJGDFDGPNLN = MyDetonator().NJGDFDGPNLN;
	}

	public void __BB_OBFUSCATOR_35()
	{
		NOKNBPGJOEB = new GameObject("_Value");
		BGBDPJOIKIN = NOKNBPGJOEB.AddComponent<DetonatorBurstEmitter>();
		NOKNBPGJOEB.transform.parent = base.transform;
		NOKNBPGJOEB.transform.localRotation = Quaternion.identity;
		BGBDPJOIKIN.MFOLDHOAMNN = KCMNLNCMIMH;
		BGBDPJOIKIN.MJHAPHHGGHI = MyDetonator().MJHAPHHGGHI;
		BGBDPJOIKIN.NJGDFDGPNLN = MyDetonator().NJGDFDGPNLN;
	}

	public void __BB_OBFUSCATOR_49()
	{
		PCICJECIOMB.transform.localPosition = Vector3.Scale(BJGOJGBLDMN, new Vector3(EEDMLOPHDJA, EEDMLOPHDJA, EEDMLOPHDJA));
		DMNCBGHHAKI.IOFNOJHNJAJ = IOFNOJHNJAJ;
		DMNCBGHHAKI.LCLHCEHHBNM = LCLHCEHHBNM * 156f;
		DMNCBGHHAKI.HEKGFKJHMFJ = LCLHCEHHBNM * 62f;
		DMNCBGHHAKI.FGMDPKFFANG = 812f;
		DMNCBGHHAKI.PJKHHCHLFIF = PJKHHCHLFIF;
		DMNCBGHHAKI.NCGMMIBMBEL = NCGMMIBMBEL;
		DMNCBGHHAKI.HPKOOPBINIH = 645f;
		DMNCBGHHAKI.EKKCIFKDCNC = 896f;
		DMNCBGHHAKI.PACAMLAINIK = PACAMLAINIK;
		DMNCBGHHAKI.MFAPGCJPFFH = 1208f;
		DMNCBGHHAKI.EEDMLOPHDJA = EEDMLOPHDJA;
		DMNCBGHHAKI.AIELAFCIBBM = true;
		Color b = new Color(1102f, 1682f, 794f, 929f);
		Color b2 = new Color(129f, 1900f, 1577f, 92f);
		Color color = new Color(172f, 1914f, 1013f, 1758f);
		DMNCBGHHAKI.CJFAMIBMHGK[0] = Color.Lerp(IOFNOJHNJAJ, b, 258f);
		DMNCBGHHAKI.CJFAMIBMHGK[0] = Color.Lerp(IOFNOJHNJAJ, b, 953f);
		DMNCBGHHAKI.CJFAMIBMHGK[7] = IOFNOJHNJAJ;
		DMNCBGHHAKI.CJFAMIBMHGK[1] = Color.Lerp(IOFNOJHNJAJ, b2, 44f);
		DMNCBGHHAKI.CJFAMIBMHGK[8] = color;
		DMNCBGHHAKI.BHDOLBHLDGC = BHDOLBHLDGC;
		DMNCBGHHAKI.DHMOAEAKEBD = DHMOAEAKEBD;
	}

	public void __BB_OBFUSCATOR_94()
	{
		NOKNBPGJOEB.transform.localPosition = Vector3.Scale(BJGOJGBLDMN, new Vector3(EEDMLOPHDJA, EEDMLOPHDJA, EEDMLOPHDJA));
		NOKNBPGJOEB.transform.LookAt(Camera.main.transform);
		NOKNBPGJOEB.transform.localPosition = -(Vector3.forward * 1269f);
		BGBDPJOIKIN.IOFNOJHNJAJ = new Color(968f, 936f, 969f, 1943f);
		BGBDPJOIKIN.LCLHCEHHBNM = LCLHCEHHBNM * 805f;
		BGBDPJOIKIN.HEKGFKJHMFJ = LCLHCEHHBNM * 1073f;
		BGBDPJOIKIN.PJKHHCHLFIF = PJKHHCHLFIF;
		BGBDPJOIKIN.NCGMMIBMBEL = 1317f;
		BGBDPJOIKIN.HPKOOPBINIH = 1362f;
		BGBDPJOIKIN.PACAMLAINIK = PACAMLAINIK;
		BGBDPJOIKIN.EKKCIFKDCNC = 783f;
		BGBDPJOIKIN.FGMDPKFFANG = 586f;
		BGBDPJOIKIN.MFAPGCJPFFH = 1086f;
		BGBDPJOIKIN.EEDMLOPHDJA = EEDMLOPHDJA;
		BGBDPJOIKIN.BHDOLBHLDGC = BHDOLBHLDGC;
		BGBDPJOIKIN.DHMOAEAKEBD = DHMOAEAKEBD;
	}

	public void __BB_OBFUSCATOR_93()
	{
		PCICJECIOMB = new GameObject("\n\t\t\tProperty: \"Lcl Scaling\", \"Lcl Scaling\", \"A+\",");
		DMNCBGHHAKI = PCICJECIOMB.AddComponent<DetonatorBurstEmitter>();
		PCICJECIOMB.transform.parent = base.transform;
		PCICJECIOMB.transform.localRotation = Quaternion.identity;
		DMNCBGHHAKI.MFOLDHOAMNN = FMNGJEGCFIE;
		DMNCBGHHAKI.MJHAPHHGGHI = MyDetonator().MJHAPHHGGHI;
		DMNCBGHHAKI.NJGDFDGPNLN = MyDetonator().NJGDFDGPNLN;
	}

	public void __BB_OBFUSCATOR_76()
	{
		JCHGLBLBBJK = new GameObject("b");
		CLNNBLEBPOO = JCHGLBLBBJK.AddComponent<DetonatorBurstEmitter>();
		JCHGLBLBBJK.transform.parent = base.transform;
		JCHGLBLBBJK.transform.localRotation = Quaternion.identity;
		CLNNBLEBPOO.MFOLDHOAMNN = DHGANMBLNNK;
		CLNNBLEBPOO.MJHAPHHGGHI = MyDetonator().MJHAPHHGGHI;
		CLNNBLEBPOO.NJGDFDGPNLN = MyDetonator().NJGDFDGPNLN;
	}

	public void __BB_OBFUSCATOR_53()
	{
		PCICJECIOMB.transform.localPosition = Vector3.Scale(BJGOJGBLDMN, new Vector3(EEDMLOPHDJA, EEDMLOPHDJA, EEDMLOPHDJA));
		DMNCBGHHAKI.IOFNOJHNJAJ = IOFNOJHNJAJ;
		DMNCBGHHAKI.LCLHCEHHBNM = LCLHCEHHBNM * 414f;
		DMNCBGHHAKI.HEKGFKJHMFJ = LCLHCEHHBNM * 1047f;
		DMNCBGHHAKI.FGMDPKFFANG = 213f;
		DMNCBGHHAKI.PJKHHCHLFIF = PJKHHCHLFIF;
		DMNCBGHHAKI.NCGMMIBMBEL = NCGMMIBMBEL;
		DMNCBGHHAKI.HPKOOPBINIH = 1256f;
		DMNCBGHHAKI.EKKCIFKDCNC = 1294f;
		DMNCBGHHAKI.PACAMLAINIK = PACAMLAINIK;
		DMNCBGHHAKI.MFAPGCJPFFH = 1723f;
		DMNCBGHHAKI.EEDMLOPHDJA = EEDMLOPHDJA;
		DMNCBGHHAKI.AIELAFCIBBM = false;
		Color b = new Color(331f, 1035f, 1702f, 1067f);
		Color b2 = new Color(418f, 52f, 1836f, 880f);
		Color color = new Color(104f, 1250f, 1731f, 720f);
		DMNCBGHHAKI.CJFAMIBMHGK[1] = Color.Lerp(IOFNOJHNJAJ, b, 1481f);
		DMNCBGHHAKI.CJFAMIBMHGK[0] = Color.Lerp(IOFNOJHNJAJ, b, 280f);
		DMNCBGHHAKI.CJFAMIBMHGK[6] = IOFNOJHNJAJ;
		DMNCBGHHAKI.CJFAMIBMHGK[0] = Color.Lerp(IOFNOJHNJAJ, b2, 1742f);
		DMNCBGHHAKI.CJFAMIBMHGK[6] = color;
		DMNCBGHHAKI.BHDOLBHLDGC = BHDOLBHLDGC;
		DMNCBGHHAKI.DHMOAEAKEBD = DHMOAEAKEBD;
	}

	public void __BB_OBFUSCATOR_56()
	{
		PCICJECIOMB = new GameObject("Dead");
		DMNCBGHHAKI = PCICJECIOMB.AddComponent<DetonatorBurstEmitter>();
		PCICJECIOMB.transform.parent = base.transform;
		PCICJECIOMB.transform.localRotation = Quaternion.identity;
		DMNCBGHHAKI.MFOLDHOAMNN = FMNGJEGCFIE;
		DMNCBGHHAKI.MJHAPHHGGHI = MyDetonator().MJHAPHHGGHI;
		DMNCBGHHAKI.NJGDFDGPNLN = MyDetonator().NJGDFDGPNLN;
	}

	public void __BB_OBFUSCATOR_40()
	{
		NOKNBPGJOEB.transform.localPosition = Vector3.Scale(BJGOJGBLDMN, new Vector3(EEDMLOPHDJA, EEDMLOPHDJA, EEDMLOPHDJA));
		NOKNBPGJOEB.transform.LookAt(Camera.main.transform);
		NOKNBPGJOEB.transform.localPosition = -(Vector3.forward * 168f);
		BGBDPJOIKIN.IOFNOJHNJAJ = new Color(1639f, 388f, 1429f, 220f);
		BGBDPJOIKIN.LCLHCEHHBNM = LCLHCEHHBNM * 1124f;
		BGBDPJOIKIN.HEKGFKJHMFJ = LCLHCEHHBNM * 1642f;
		BGBDPJOIKIN.PJKHHCHLFIF = PJKHHCHLFIF;
		BGBDPJOIKIN.NCGMMIBMBEL = 1179f;
		BGBDPJOIKIN.HPKOOPBINIH = 1646f;
		BGBDPJOIKIN.PACAMLAINIK = PACAMLAINIK;
		BGBDPJOIKIN.EKKCIFKDCNC = 42f;
		BGBDPJOIKIN.FGMDPKFFANG = 1286f;
		BGBDPJOIKIN.MFAPGCJPFFH = 736f;
		BGBDPJOIKIN.EEDMLOPHDJA = EEDMLOPHDJA;
		BGBDPJOIKIN.BHDOLBHLDGC = BHDOLBHLDGC;
		BGBDPJOIKIN.DHMOAEAKEBD = DHMOAEAKEBD;
	}

	public void __BB_OBFUSCATOR_66()
	{
		__BB_OBFUSCATOR_27(false);
		GMAIEMJKMJD = true;
		EEDMLOPHDJA = KBGFHOJODBF;
		LCLHCEHHBNM = BNCCIDBIPBF;
		BHDOLBHLDGC = 1508f;
		DHMOAEAKEBD = 859f;
		IOFNOJHNJAJ = LNKOBAPEIIM;
	}

	public void __BB_OBFUSCATOR_6()
	{
		NOKNBPGJOEB = new GameObject(" x ");
		BGBDPJOIKIN = NOKNBPGJOEB.AddComponent<DetonatorBurstEmitter>();
		NOKNBPGJOEB.transform.parent = base.transform;
		NOKNBPGJOEB.transform.localRotation = Quaternion.identity;
		BGBDPJOIKIN.MFOLDHOAMNN = KCMNLNCMIMH;
		BGBDPJOIKIN.MJHAPHHGGHI = MyDetonator().MJHAPHHGGHI;
		BGBDPJOIKIN.NJGDFDGPNLN = MyDetonator().NJGDFDGPNLN;
	}

	public void __BB_OBFUSCATOR_55()
	{
		NOKNBPGJOEB.transform.localPosition = Vector3.Scale(BJGOJGBLDMN, new Vector3(EEDMLOPHDJA, EEDMLOPHDJA, EEDMLOPHDJA));
		NOKNBPGJOEB.transform.LookAt(Camera.main.transform);
		NOKNBPGJOEB.transform.localPosition = -(Vector3.forward * 1820f);
		BGBDPJOIKIN.IOFNOJHNJAJ = new Color(368f, 878f, 358f, 1075f);
		BGBDPJOIKIN.LCLHCEHHBNM = LCLHCEHHBNM * 1586f;
		BGBDPJOIKIN.HEKGFKJHMFJ = LCLHCEHHBNM * 1327f;
		BGBDPJOIKIN.PJKHHCHLFIF = PJKHHCHLFIF;
		BGBDPJOIKIN.NCGMMIBMBEL = 1891f;
		BGBDPJOIKIN.HPKOOPBINIH = 715f;
		BGBDPJOIKIN.PACAMLAINIK = PACAMLAINIK;
		BGBDPJOIKIN.EKKCIFKDCNC = 924f;
		BGBDPJOIKIN.FGMDPKFFANG = 1804f;
		BGBDPJOIKIN.MFAPGCJPFFH = 955f;
		BGBDPJOIKIN.EEDMLOPHDJA = EEDMLOPHDJA;
		BGBDPJOIKIN.BHDOLBHLDGC = BHDOLBHLDGC;
		BGBDPJOIKIN.DHMOAEAKEBD = DHMOAEAKEBD;
	}

	public void __BB_OBFUSCATOR_3()
	{
		JCHGLBLBBJK = new GameObject("_InvRenderTargetSize");
		CLNNBLEBPOO = JCHGLBLBBJK.AddComponent<DetonatorBurstEmitter>();
		JCHGLBLBBJK.transform.parent = base.transform;
		JCHGLBLBBJK.transform.localRotation = Quaternion.identity;
		CLNNBLEBPOO.MFOLDHOAMNN = DHGANMBLNNK;
		CLNNBLEBPOO.MJHAPHHGGHI = MyDetonator().MJHAPHHGGHI;
		CLNNBLEBPOO.NJGDFDGPNLN = MyDetonator().NJGDFDGPNLN;
	}

	public void __BB_OBFUSCATOR_1()
	{
		__BB_OBFUSCATOR_32(false);
		GMAIEMJKMJD = false;
		EEDMLOPHDJA = KBGFHOJODBF;
		LCLHCEHHBNM = BNCCIDBIPBF;
		BHDOLBHLDGC = 1645f;
		DHMOAEAKEBD = 1065f;
		IOFNOJHNJAJ = LNKOBAPEIIM;
	}

	public void __BB_OBFUSCATOR_79()
	{
		__BB_OBFUSCATOR_41(true);
		GMAIEMJKMJD = false;
		EEDMLOPHDJA = KBGFHOJODBF;
		LCLHCEHHBNM = BNCCIDBIPBF;
		BHDOLBHLDGC = 1791f;
		DHMOAEAKEBD = 622f;
		IOFNOJHNJAJ = LNKOBAPEIIM;
	}

	public void __BB_OBFUSCATOR_73()
	{
		JCHGLBLBBJK.transform.localPosition = Vector3.Scale(BJGOJGBLDMN, new Vector3(EEDMLOPHDJA, EEDMLOPHDJA, EEDMLOPHDJA));
		CLNNBLEBPOO.IOFNOJHNJAJ = IOFNOJHNJAJ;
		CLNNBLEBPOO.LCLHCEHHBNM = LCLHCEHHBNM * 1169f;
		CLNNBLEBPOO.HEKGFKJHMFJ = LCLHCEHHBNM * 287f;
		CLNNBLEBPOO.FGMDPKFFANG = 609f;
		CLNNBLEBPOO.PJKHHCHLFIF = PJKHHCHLFIF;
		CLNNBLEBPOO.NCGMMIBMBEL = NCGMMIBMBEL;
		CLNNBLEBPOO.HPKOOPBINIH = 1888f;
		CLNNBLEBPOO.EKKCIFKDCNC = 1128f;
		CLNNBLEBPOO.PACAMLAINIK = PACAMLAINIK;
		CLNNBLEBPOO.MFAPGCJPFFH = 38f;
		CLNNBLEBPOO.EEDMLOPHDJA = EEDMLOPHDJA;
		CLNNBLEBPOO.AIELAFCIBBM = true;
		Color b = new Color(1116f, 1231f, 868f, 1188f);
		Color b2 = new Color(962f, 1517f, 1554f, 325f);
		Color color = new Color(1110f, 1281f, 111f, 519f);
		CLNNBLEBPOO.CJFAMIBMHGK[1] = Color.Lerp(IOFNOJHNJAJ, b, 593f);
		CLNNBLEBPOO.CJFAMIBMHGK[0] = Color.Lerp(IOFNOJHNJAJ, b, 786f);
		CLNNBLEBPOO.CJFAMIBMHGK[5] = IOFNOJHNJAJ;
		CLNNBLEBPOO.CJFAMIBMHGK[4] = Color.Lerp(IOFNOJHNJAJ, b2, 1871f);
		CLNNBLEBPOO.CJFAMIBMHGK[0] = color;
		CLNNBLEBPOO.BHDOLBHLDGC = BHDOLBHLDGC;
		CLNNBLEBPOO.DHMOAEAKEBD = DHMOAEAKEBD;
	}

	public virtual void __BB_OBFUSCATOR_38()
	{
		if (!(IKCHMAJADEP > NCGMMIBMBEL) && GMAIEMJKMJD)
		{
			__BB_OBFUSCATOR_73();
			__BB_OBFUSCATOR_60();
			__BB_OBFUSCATOR_63();
			if (BCDHHFNKJCK)
			{
				CLNNBLEBPOO.Explode();
			}
			if (CHDKFLCJKDD)
			{
				DMNCBGHHAKI.Explode();
			}
			if (ACKFFOIFDII)
			{
				BGBDPJOIKIN.Explode();
			}
		}
	}

	public void __BB_OBFUSCATOR_95()
	{
		NOKNBPGJOEB = new GameObject("_Value4");
		BGBDPJOIKIN = NOKNBPGJOEB.AddComponent<DetonatorBurstEmitter>();
		NOKNBPGJOEB.transform.parent = base.transform;
		NOKNBPGJOEB.transform.localRotation = Quaternion.identity;
		BGBDPJOIKIN.MFOLDHOAMNN = KCMNLNCMIMH;
		BGBDPJOIKIN.MJHAPHHGGHI = MyDetonator().MJHAPHHGGHI;
		BGBDPJOIKIN.NJGDFDGPNLN = MyDetonator().NJGDFDGPNLN;
	}

	public virtual void __BB_OBFUSCATOR_57()
	{
		if (!(IKCHMAJADEP > NCGMMIBMBEL) && GMAIEMJKMJD)
		{
			__BB_OBFUSCATOR_12();
			__BB_OBFUSCATOR_53();
			__BB_OBFUSCATOR_0();
			if (BCDHHFNKJCK)
			{
				CLNNBLEBPOO.Explode();
			}
			if (CHDKFLCJKDD)
			{
				DMNCBGHHAKI.Explode();
			}
			if (ACKFFOIFDII)
			{
				BGBDPJOIKIN.Explode();
			}
		}
	}

	public void __BB_OBFUSCATOR_12()
	{
		JCHGLBLBBJK.transform.localPosition = Vector3.Scale(BJGOJGBLDMN, new Vector3(EEDMLOPHDJA, EEDMLOPHDJA, EEDMLOPHDJA));
		CLNNBLEBPOO.IOFNOJHNJAJ = IOFNOJHNJAJ;
		CLNNBLEBPOO.LCLHCEHHBNM = LCLHCEHHBNM * 665f;
		CLNNBLEBPOO.HEKGFKJHMFJ = LCLHCEHHBNM * 760f;
		CLNNBLEBPOO.FGMDPKFFANG = 1398f;
		CLNNBLEBPOO.PJKHHCHLFIF = PJKHHCHLFIF;
		CLNNBLEBPOO.NCGMMIBMBEL = NCGMMIBMBEL;
		CLNNBLEBPOO.HPKOOPBINIH = 1543f;
		CLNNBLEBPOO.EKKCIFKDCNC = 1254f;
		CLNNBLEBPOO.PACAMLAINIK = PACAMLAINIK;
		CLNNBLEBPOO.MFAPGCJPFFH = 1366f;
		CLNNBLEBPOO.EEDMLOPHDJA = EEDMLOPHDJA;
		CLNNBLEBPOO.AIELAFCIBBM = true;
		Color b = new Color(757f, 1411f, 1971f, 1801f);
		Color b2 = new Color(1687f, 83f, 317f, 1809f);
		Color color = new Color(971f, 1098f, 1399f, 1381f);
		CLNNBLEBPOO.CJFAMIBMHGK[1] = Color.Lerp(IOFNOJHNJAJ, b, 0f);
		CLNNBLEBPOO.CJFAMIBMHGK[1] = Color.Lerp(IOFNOJHNJAJ, b, 1454f);
		CLNNBLEBPOO.CJFAMIBMHGK[6] = IOFNOJHNJAJ;
		CLNNBLEBPOO.CJFAMIBMHGK[1] = Color.Lerp(IOFNOJHNJAJ, b2, 888f);
		CLNNBLEBPOO.CJFAMIBMHGK[5] = color;
		CLNNBLEBPOO.BHDOLBHLDGC = BHDOLBHLDGC;
		CLNNBLEBPOO.DHMOAEAKEBD = DHMOAEAKEBD;
	}

	public virtual void __BB_OBFUSCATOR_92()
	{
		if (!(IKCHMAJADEP > NCGMMIBMBEL) && GMAIEMJKMJD)
		{
			__BB_OBFUSCATOR_47();
			__BB_OBFUSCATOR_2();
			__BB_OBFUSCATOR_39();
			if (BCDHHFNKJCK)
			{
				CLNNBLEBPOO.Explode();
			}
			if (CHDKFLCJKDD)
			{
				DMNCBGHHAKI.Explode();
			}
			if (ACKFFOIFDII)
			{
				BGBDPJOIKIN.Explode();
			}
		}
	}

	public void __BB_OBFUSCATOR_84()
	{
		JCHGLBLBBJK = new GameObject("TDM");
		CLNNBLEBPOO = JCHGLBLBBJK.AddComponent<DetonatorBurstEmitter>();
		JCHGLBLBBJK.transform.parent = base.transform;
		JCHGLBLBBJK.transform.localRotation = Quaternion.identity;
		CLNNBLEBPOO.MFOLDHOAMNN = DHGANMBLNNK;
		CLNNBLEBPOO.MJHAPHHGGHI = MyDetonator().MJHAPHHGGHI;
		CLNNBLEBPOO.NJGDFDGPNLN = MyDetonator().NJGDFDGPNLN;
	}

	public void __BB_OBFUSCATOR_47()
	{
		JCHGLBLBBJK.transform.localPosition = Vector3.Scale(BJGOJGBLDMN, new Vector3(EEDMLOPHDJA, EEDMLOPHDJA, EEDMLOPHDJA));
		CLNNBLEBPOO.IOFNOJHNJAJ = IOFNOJHNJAJ;
		CLNNBLEBPOO.LCLHCEHHBNM = LCLHCEHHBNM * 303f;
		CLNNBLEBPOO.HEKGFKJHMFJ = LCLHCEHHBNM * 201f;
		CLNNBLEBPOO.FGMDPKFFANG = 1724f;
		CLNNBLEBPOO.PJKHHCHLFIF = PJKHHCHLFIF;
		CLNNBLEBPOO.NCGMMIBMBEL = NCGMMIBMBEL;
		CLNNBLEBPOO.HPKOOPBINIH = 1624f;
		CLNNBLEBPOO.EKKCIFKDCNC = 1812f;
		CLNNBLEBPOO.PACAMLAINIK = PACAMLAINIK;
		CLNNBLEBPOO.MFAPGCJPFFH = 1349f;
		CLNNBLEBPOO.EEDMLOPHDJA = EEDMLOPHDJA;
		CLNNBLEBPOO.AIELAFCIBBM = true;
		Color b = new Color(599f, 1967f, 969f, 1807f);
		Color b2 = new Color(1240f, 1234f, 539f, 780f);
		Color color = new Color(1500f, 165f, 119f, 46f);
		CLNNBLEBPOO.CJFAMIBMHGK[0] = Color.Lerp(IOFNOJHNJAJ, b, 242f);
		CLNNBLEBPOO.CJFAMIBMHGK[0] = Color.Lerp(IOFNOJHNJAJ, b, 1450f);
		CLNNBLEBPOO.CJFAMIBMHGK[8] = IOFNOJHNJAJ;
		CLNNBLEBPOO.CJFAMIBMHGK[2] = Color.Lerp(IOFNOJHNJAJ, b2, 1927f);
		CLNNBLEBPOO.CJFAMIBMHGK[0] = color;
		CLNNBLEBPOO.BHDOLBHLDGC = BHDOLBHLDGC;
		CLNNBLEBPOO.DHMOAEAKEBD = DHMOAEAKEBD;
	}

	public void __BB_OBFUSCATOR_60()
	{
		PCICJECIOMB.transform.localPosition = Vector3.Scale(BJGOJGBLDMN, new Vector3(EEDMLOPHDJA, EEDMLOPHDJA, EEDMLOPHDJA));
		DMNCBGHHAKI.IOFNOJHNJAJ = IOFNOJHNJAJ;
		DMNCBGHHAKI.LCLHCEHHBNM = LCLHCEHHBNM * 835f;
		DMNCBGHHAKI.HEKGFKJHMFJ = LCLHCEHHBNM * 93f;
		DMNCBGHHAKI.FGMDPKFFANG = 922f;
		DMNCBGHHAKI.PJKHHCHLFIF = PJKHHCHLFIF;
		DMNCBGHHAKI.NCGMMIBMBEL = NCGMMIBMBEL;
		DMNCBGHHAKI.HPKOOPBINIH = 1389f;
		DMNCBGHHAKI.EKKCIFKDCNC = 75f;
		DMNCBGHHAKI.PACAMLAINIK = PACAMLAINIK;
		DMNCBGHHAKI.MFAPGCJPFFH = 1442f;
		DMNCBGHHAKI.EEDMLOPHDJA = EEDMLOPHDJA;
		DMNCBGHHAKI.AIELAFCIBBM = true;
		Color b = new Color(1221f, 1643f, 630f, 1779f);
		Color b2 = new Color(1832f, 426f, 1506f, 528f);
		Color color = new Color(167f, 908f, 659f, 283f);
		DMNCBGHHAKI.CJFAMIBMHGK[1] = Color.Lerp(IOFNOJHNJAJ, b, 338f);
		DMNCBGHHAKI.CJFAMIBMHGK[0] = Color.Lerp(IOFNOJHNJAJ, b, 200f);
		DMNCBGHHAKI.CJFAMIBMHGK[7] = IOFNOJHNJAJ;
		DMNCBGHHAKI.CJFAMIBMHGK[7] = Color.Lerp(IOFNOJHNJAJ, b2, 438f);
		DMNCBGHHAKI.CJFAMIBMHGK[5] = color;
		DMNCBGHHAKI.BHDOLBHLDGC = BHDOLBHLDGC;
		DMNCBGHHAKI.DHMOAEAKEBD = DHMOAEAKEBD;
	}

	public virtual void __BB_OBFUSCATOR_30()
	{
		if (!(IKCHMAJADEP > NCGMMIBMBEL) && GMAIEMJKMJD)
		{
			__BB_OBFUSCATOR_47();
			__BB_OBFUSCATOR_72();
			__BB_OBFUSCATOR_0();
			if (BCDHHFNKJCK)
			{
				CLNNBLEBPOO.Explode();
			}
			if (CHDKFLCJKDD)
			{
				DMNCBGHHAKI.Explode();
			}
			if (ACKFFOIFDII)
			{
				BGBDPJOIKIN.Explode();
			}
		}
	}

	public void BuildFireballA()
	{
		JCHGLBLBBJK = new GameObject("FireballA");
		CLNNBLEBPOO = JCHGLBLBBJK.AddComponent<DetonatorBurstEmitter>();
		JCHGLBLBBJK.transform.parent = base.transform;
		JCHGLBLBBJK.transform.localRotation = Quaternion.identity;
		CLNNBLEBPOO.MFOLDHOAMNN = DHGANMBLNNK;
		CLNNBLEBPOO.MJHAPHHGGHI = MyDetonator().MJHAPHHGGHI;
		CLNNBLEBPOO.NJGDFDGPNLN = MyDetonator().NJGDFDGPNLN;
	}

	public void __BB_OBFUSCATOR_23()
	{
		NOKNBPGJOEB = new GameObject("_ScreenResolution");
		BGBDPJOIKIN = NOKNBPGJOEB.AddComponent<DetonatorBurstEmitter>();
		NOKNBPGJOEB.transform.parent = base.transform;
		NOKNBPGJOEB.transform.localRotation = Quaternion.identity;
		BGBDPJOIKIN.MFOLDHOAMNN = KCMNLNCMIMH;
		BGBDPJOIKIN.MJHAPHHGGHI = MyDetonator().MJHAPHHGGHI;
		BGBDPJOIKIN.NJGDFDGPNLN = MyDetonator().NJGDFDGPNLN;
	}

	public void __BB_OBFUSCATOR_59()
	{
		JCHGLBLBBJK.transform.localPosition = Vector3.Scale(BJGOJGBLDMN, new Vector3(EEDMLOPHDJA, EEDMLOPHDJA, EEDMLOPHDJA));
		CLNNBLEBPOO.IOFNOJHNJAJ = IOFNOJHNJAJ;
		CLNNBLEBPOO.LCLHCEHHBNM = LCLHCEHHBNM * 1199f;
		CLNNBLEBPOO.HEKGFKJHMFJ = LCLHCEHHBNM * 888f;
		CLNNBLEBPOO.FGMDPKFFANG = 787f;
		CLNNBLEBPOO.PJKHHCHLFIF = PJKHHCHLFIF;
		CLNNBLEBPOO.NCGMMIBMBEL = NCGMMIBMBEL;
		CLNNBLEBPOO.HPKOOPBINIH = 931f;
		CLNNBLEBPOO.EKKCIFKDCNC = 194f;
		CLNNBLEBPOO.PACAMLAINIK = PACAMLAINIK;
		CLNNBLEBPOO.MFAPGCJPFFH = 1955f;
		CLNNBLEBPOO.EEDMLOPHDJA = EEDMLOPHDJA;
		CLNNBLEBPOO.AIELAFCIBBM = true;
		Color b = new Color(578f, 1622f, 1436f, 342f);
		Color b2 = new Color(1285f, 1555f, 192f, 504f);
		Color color = new Color(534f, 790f, 1603f, 363f);
		CLNNBLEBPOO.CJFAMIBMHGK[1] = Color.Lerp(IOFNOJHNJAJ, b, 747f);
		CLNNBLEBPOO.CJFAMIBMHGK[1] = Color.Lerp(IOFNOJHNJAJ, b, 638f);
		CLNNBLEBPOO.CJFAMIBMHGK[5] = IOFNOJHNJAJ;
		CLNNBLEBPOO.CJFAMIBMHGK[8] = Color.Lerp(IOFNOJHNJAJ, b2, 943f);
		CLNNBLEBPOO.CJFAMIBMHGK[1] = color;
		CLNNBLEBPOO.BHDOLBHLDGC = BHDOLBHLDGC;
		CLNNBLEBPOO.DHMOAEAKEBD = DHMOAEAKEBD;
	}

	public void UpdateFireballB()
	{
		PCICJECIOMB.transform.localPosition = Vector3.Scale(BJGOJGBLDMN, new Vector3(EEDMLOPHDJA, EEDMLOPHDJA, EEDMLOPHDJA));
		DMNCBGHHAKI.IOFNOJHNJAJ = IOFNOJHNJAJ;
		DMNCBGHHAKI.LCLHCEHHBNM = LCLHCEHHBNM * 0.5f;
		DMNCBGHHAKI.HEKGFKJHMFJ = LCLHCEHHBNM * 0.5f;
		DMNCBGHHAKI.FGMDPKFFANG = 2f;
		DMNCBGHHAKI.PJKHHCHLFIF = PJKHHCHLFIF;
		DMNCBGHHAKI.NCGMMIBMBEL = NCGMMIBMBEL;
		DMNCBGHHAKI.HPKOOPBINIH = 10f;
		DMNCBGHHAKI.EKKCIFKDCNC = 6f;
		DMNCBGHHAKI.PACAMLAINIK = PACAMLAINIK;
		DMNCBGHHAKI.MFAPGCJPFFH = 4f;
		DMNCBGHHAKI.EEDMLOPHDJA = EEDMLOPHDJA;
		DMNCBGHHAKI.AIELAFCIBBM = true;
		Color b = new Color(1f, 1f, 1f, 0.5f);
		Color b2 = new Color(0.6f, 0.15f, 0.15f, 0.3f);
		Color color = new Color(0.1f, 0.2f, 0.45f, 0f);
		DMNCBGHHAKI.CJFAMIBMHGK[0] = Color.Lerp(IOFNOJHNJAJ, b, 0.8f);
		DMNCBGHHAKI.CJFAMIBMHGK[1] = Color.Lerp(IOFNOJHNJAJ, b, 0.5f);
		DMNCBGHHAKI.CJFAMIBMHGK[2] = IOFNOJHNJAJ;
		DMNCBGHHAKI.CJFAMIBMHGK[3] = Color.Lerp(IOFNOJHNJAJ, b2, 0.7f);
		DMNCBGHHAKI.CJFAMIBMHGK[4] = color;
		DMNCBGHHAKI.BHDOLBHLDGC = BHDOLBHLDGC;
		DMNCBGHHAKI.DHMOAEAKEBD = DHMOAEAKEBD;
	}

	public void __BB_OBFUSCATOR_29(bool PHDOMKDEDMO)
	{
		if (!DHGANMBLNNK || PHDOMKDEDMO)
		{
			DHGANMBLNNK = MyDetonator().DHGANMBLNNK;
		}
		if (!FMNGJEGCFIE || PHDOMKDEDMO)
		{
			FMNGJEGCFIE = MyDetonator().FMNGJEGCFIE;
		}
		if (!KCMNLNCMIMH || PHDOMKDEDMO)
		{
			if ((double)Random.value > 685.0)
			{
				KCMNLNCMIMH = MyDetonator().NLCJNPAMOEH;
			}
			else
			{
				KCMNLNCMIMH = MyDetonator().KDNNLMHFKOJ;
			}
		}
	}

	public void __BB_OBFUSCATOR_4()
	{
		PCICJECIOMB = new GameObject("Ping");
		DMNCBGHHAKI = PCICJECIOMB.AddComponent<DetonatorBurstEmitter>();
		PCICJECIOMB.transform.parent = base.transform;
		PCICJECIOMB.transform.localRotation = Quaternion.identity;
		DMNCBGHHAKI.MFOLDHOAMNN = FMNGJEGCFIE;
		DMNCBGHHAKI.MJHAPHHGGHI = MyDetonator().MJHAPHHGGHI;
		DMNCBGHHAKI.NJGDFDGPNLN = MyDetonator().NJGDFDGPNLN;
	}

	public void BuildFireShadow()
	{
		NOKNBPGJOEB = new GameObject("FireShadow");
		BGBDPJOIKIN = NOKNBPGJOEB.AddComponent<DetonatorBurstEmitter>();
		NOKNBPGJOEB.transform.parent = base.transform;
		NOKNBPGJOEB.transform.localRotation = Quaternion.identity;
		BGBDPJOIKIN.MFOLDHOAMNN = KCMNLNCMIMH;
		BGBDPJOIKIN.MJHAPHHGGHI = MyDetonator().MJHAPHHGGHI;
		BGBDPJOIKIN.NJGDFDGPNLN = MyDetonator().NJGDFDGPNLN;
	}

	public void BuildFireballB()
	{
		PCICJECIOMB = new GameObject("FireballB");
		DMNCBGHHAKI = PCICJECIOMB.AddComponent<DetonatorBurstEmitter>();
		PCICJECIOMB.transform.parent = base.transform;
		PCICJECIOMB.transform.localRotation = Quaternion.identity;
		DMNCBGHHAKI.MFOLDHOAMNN = FMNGJEGCFIE;
		DMNCBGHHAKI.MJHAPHHGGHI = MyDetonator().MJHAPHHGGHI;
		DMNCBGHHAKI.NJGDFDGPNLN = MyDetonator().NJGDFDGPNLN;
	}

	public virtual void __BB_OBFUSCATOR_85()
	{
		__BB_OBFUSCATOR_98(false);
		__BB_OBFUSCATOR_76();
		__BB_OBFUSCATOR_93();
		__BB_OBFUSCATOR_23();
	}

	public virtual void __BB_OBFUSCATOR_16()
	{
		if (!(IKCHMAJADEP > NCGMMIBMBEL) && GMAIEMJKMJD)
		{
			__BB_OBFUSCATOR_59();
			__BB_OBFUSCATOR_42();
			UpdateFireShadow();
			if (BCDHHFNKJCK)
			{
				CLNNBLEBPOO.Explode();
			}
			if (CHDKFLCJKDD)
			{
				DMNCBGHHAKI.Explode();
			}
			if (ACKFFOIFDII)
			{
				BGBDPJOIKIN.Explode();
			}
		}
	}

	public void __BB_OBFUSCATOR_32(bool PHDOMKDEDMO)
	{
		if (!DHGANMBLNNK || PHDOMKDEDMO)
		{
			DHGANMBLNNK = MyDetonator().DHGANMBLNNK;
		}
		if (!FMNGJEGCFIE || PHDOMKDEDMO)
		{
			FMNGJEGCFIE = MyDetonator().FMNGJEGCFIE;
		}
		if (!KCMNLNCMIMH || PHDOMKDEDMO)
		{
			if ((double)Random.value > 896.0)
			{
				KCMNLNCMIMH = MyDetonator().NLCJNPAMOEH;
			}
			else
			{
				KCMNLNCMIMH = MyDetonator().KDNNLMHFKOJ;
			}
		}
	}

	public void __BB_OBFUSCATOR_62()
	{
		__BB_OBFUSCATOR_71(false);
		GMAIEMJKMJD = true;
		EEDMLOPHDJA = KBGFHOJODBF;
		LCLHCEHHBNM = BNCCIDBIPBF;
		BHDOLBHLDGC = 1937f;
		DHMOAEAKEBD = 23f;
		IOFNOJHNJAJ = LNKOBAPEIIM;
	}

	public void __BB_OBFUSCATOR_50()
	{
		JCHGLBLBBJK.transform.localPosition = Vector3.Scale(BJGOJGBLDMN, new Vector3(EEDMLOPHDJA, EEDMLOPHDJA, EEDMLOPHDJA));
		CLNNBLEBPOO.IOFNOJHNJAJ = IOFNOJHNJAJ;
		CLNNBLEBPOO.LCLHCEHHBNM = LCLHCEHHBNM * 113f;
		CLNNBLEBPOO.HEKGFKJHMFJ = LCLHCEHHBNM * 1381f;
		CLNNBLEBPOO.FGMDPKFFANG = 1316f;
		CLNNBLEBPOO.PJKHHCHLFIF = PJKHHCHLFIF;
		CLNNBLEBPOO.NCGMMIBMBEL = NCGMMIBMBEL;
		CLNNBLEBPOO.HPKOOPBINIH = 1871f;
		CLNNBLEBPOO.EKKCIFKDCNC = 477f;
		CLNNBLEBPOO.PACAMLAINIK = PACAMLAINIK;
		CLNNBLEBPOO.MFAPGCJPFFH = 244f;
		CLNNBLEBPOO.EEDMLOPHDJA = EEDMLOPHDJA;
		CLNNBLEBPOO.AIELAFCIBBM = true;
		Color b = new Color(1455f, 978f, 770f, 592f);
		Color b2 = new Color(960f, 404f, 798f, 1317f);
		Color color = new Color(1959f, 1747f, 1883f, 784f);
		CLNNBLEBPOO.CJFAMIBMHGK[0] = Color.Lerp(IOFNOJHNJAJ, b, 1391f);
		CLNNBLEBPOO.CJFAMIBMHGK[0] = Color.Lerp(IOFNOJHNJAJ, b, 12f);
		CLNNBLEBPOO.CJFAMIBMHGK[4] = IOFNOJHNJAJ;
		CLNNBLEBPOO.CJFAMIBMHGK[5] = Color.Lerp(IOFNOJHNJAJ, b2, 1725f);
		CLNNBLEBPOO.CJFAMIBMHGK[6] = color;
		CLNNBLEBPOO.BHDOLBHLDGC = BHDOLBHLDGC;
		CLNNBLEBPOO.DHMOAEAKEBD = DHMOAEAKEBD;
	}

	public void __BB_OBFUSCATOR_65(bool PHDOMKDEDMO)
	{
		if (!DHGANMBLNNK || PHDOMKDEDMO)
		{
			DHGANMBLNNK = MyDetonator().DHGANMBLNNK;
		}
		if (!FMNGJEGCFIE || PHDOMKDEDMO)
		{
			FMNGJEGCFIE = MyDetonator().FMNGJEGCFIE;
		}
		if (!KCMNLNCMIMH || PHDOMKDEDMO)
		{
			if ((double)Random.value > 1491.0)
			{
				KCMNLNCMIMH = MyDetonator().NLCJNPAMOEH;
			}
			else
			{
				KCMNLNCMIMH = MyDetonator().KDNNLMHFKOJ;
			}
		}
	}

	public void __BB_OBFUSCATOR_43()
	{
		__BB_OBFUSCATOR_98(true);
		GMAIEMJKMJD = false;
		EEDMLOPHDJA = KBGFHOJODBF;
		LCLHCEHHBNM = BNCCIDBIPBF;
		BHDOLBHLDGC = 1731f;
		DHMOAEAKEBD = 1719f;
		IOFNOJHNJAJ = LNKOBAPEIIM;
	}

	public void FillMaterials(bool PHDOMKDEDMO)
	{
		if (!DHGANMBLNNK || PHDOMKDEDMO)
		{
			DHGANMBLNNK = MyDetonator().DHGANMBLNNK;
		}
		if (!FMNGJEGCFIE || PHDOMKDEDMO)
		{
			FMNGJEGCFIE = MyDetonator().FMNGJEGCFIE;
		}
		if (!KCMNLNCMIMH || PHDOMKDEDMO)
		{
			if ((double)Random.value > 0.5)
			{
				KCMNLNCMIMH = MyDetonator().NLCJNPAMOEH;
			}
			else
			{
				KCMNLNCMIMH = MyDetonator().KDNNLMHFKOJ;
			}
		}
	}

	public void __BB_OBFUSCATOR_0()
	{
		NOKNBPGJOEB.transform.localPosition = Vector3.Scale(BJGOJGBLDMN, new Vector3(EEDMLOPHDJA, EEDMLOPHDJA, EEDMLOPHDJA));
		NOKNBPGJOEB.transform.LookAt(Camera.main.transform);
		NOKNBPGJOEB.transform.localPosition = -(Vector3.forward * 1781f);
		BGBDPJOIKIN.IOFNOJHNJAJ = new Color(758f, 167f, 1662f, 537f);
		BGBDPJOIKIN.LCLHCEHHBNM = LCLHCEHHBNM * 1306f;
		BGBDPJOIKIN.HEKGFKJHMFJ = LCLHCEHHBNM * 1900f;
		BGBDPJOIKIN.PJKHHCHLFIF = PJKHHCHLFIF;
		BGBDPJOIKIN.NCGMMIBMBEL = 324f;
		BGBDPJOIKIN.HPKOOPBINIH = 786f;
		BGBDPJOIKIN.PACAMLAINIK = PACAMLAINIK;
		BGBDPJOIKIN.EKKCIFKDCNC = 187f;
		BGBDPJOIKIN.FGMDPKFFANG = 78f;
		BGBDPJOIKIN.MFAPGCJPFFH = 718f;
		BGBDPJOIKIN.EEDMLOPHDJA = EEDMLOPHDJA;
		BGBDPJOIKIN.BHDOLBHLDGC = BHDOLBHLDGC;
		BGBDPJOIKIN.DHMOAEAKEBD = DHMOAEAKEBD;
	}

	public void __BB_OBFUSCATOR_71(bool PHDOMKDEDMO)
	{
		if (!DHGANMBLNNK || PHDOMKDEDMO)
		{
			DHGANMBLNNK = MyDetonator().DHGANMBLNNK;
		}
		if (!FMNGJEGCFIE || PHDOMKDEDMO)
		{
			FMNGJEGCFIE = MyDetonator().FMNGJEGCFIE;
		}
		if (!KCMNLNCMIMH || PHDOMKDEDMO)
		{
			if ((double)Random.value > 837.0)
			{
				KCMNLNCMIMH = MyDetonator().NLCJNPAMOEH;
			}
			else
			{
				KCMNLNCMIMH = MyDetonator().KDNNLMHFKOJ;
			}
		}
	}

	public void __BB_OBFUSCATOR_63()
	{
		NOKNBPGJOEB.transform.localPosition = Vector3.Scale(BJGOJGBLDMN, new Vector3(EEDMLOPHDJA, EEDMLOPHDJA, EEDMLOPHDJA));
		NOKNBPGJOEB.transform.LookAt(Camera.main.transform);
		NOKNBPGJOEB.transform.localPosition = -(Vector3.forward * 410f);
		BGBDPJOIKIN.IOFNOJHNJAJ = new Color(48f, 942f, 870f, 1453f);
		BGBDPJOIKIN.LCLHCEHHBNM = LCLHCEHHBNM * 463f;
		BGBDPJOIKIN.HEKGFKJHMFJ = LCLHCEHHBNM * 852f;
		BGBDPJOIKIN.PJKHHCHLFIF = PJKHHCHLFIF;
		BGBDPJOIKIN.NCGMMIBMBEL = 787f;
		BGBDPJOIKIN.HPKOOPBINIH = 1588f;
		BGBDPJOIKIN.PACAMLAINIK = PACAMLAINIK;
		BGBDPJOIKIN.EKKCIFKDCNC = 1128f;
		BGBDPJOIKIN.FGMDPKFFANG = 1619f;
		BGBDPJOIKIN.MFAPGCJPFFH = 563f;
		BGBDPJOIKIN.EEDMLOPHDJA = EEDMLOPHDJA;
		BGBDPJOIKIN.BHDOLBHLDGC = BHDOLBHLDGC;
		BGBDPJOIKIN.DHMOAEAKEBD = DHMOAEAKEBD;
	}

	public virtual void __BB_OBFUSCATOR_89()
	{
		__BB_OBFUSCATOR_71(false);
		BuildFireballA();
		__BB_OBFUSCATOR_93();
		BuildFireShadow();
	}

	public void __BB_OBFUSCATOR_9()
	{
		__BB_OBFUSCATOR_27(false);
		GMAIEMJKMJD = true;
		EEDMLOPHDJA = KBGFHOJODBF;
		LCLHCEHHBNM = BNCCIDBIPBF;
		BHDOLBHLDGC = 1280f;
		DHMOAEAKEBD = 764f;
		IOFNOJHNJAJ = LNKOBAPEIIM;
	}

	public virtual void __BB_OBFUSCATOR_78()
	{
		__BB_OBFUSCATOR_98(false);
		__BB_OBFUSCATOR_86();
		__BB_OBFUSCATOR_26();
		__BB_OBFUSCATOR_28();
	}

	public void __BB_OBFUSCATOR_20()
	{
		__BB_OBFUSCATOR_71(false);
		GMAIEMJKMJD = true;
		EEDMLOPHDJA = KBGFHOJODBF;
		LCLHCEHHBNM = BNCCIDBIPBF;
		BHDOLBHLDGC = 78f;
		DHMOAEAKEBD = 993f;
		IOFNOJHNJAJ = LNKOBAPEIIM;
	}

	public void __BB_OBFUSCATOR_24(bool PHDOMKDEDMO)
	{
		if (!DHGANMBLNNK || PHDOMKDEDMO)
		{
			DHGANMBLNNK = MyDetonator().DHGANMBLNNK;
		}
		if (!FMNGJEGCFIE || PHDOMKDEDMO)
		{
			FMNGJEGCFIE = MyDetonator().FMNGJEGCFIE;
		}
		if (!KCMNLNCMIMH || PHDOMKDEDMO)
		{
			if ((double)Random.value > 1378.0)
			{
				KCMNLNCMIMH = MyDetonator().NLCJNPAMOEH;
			}
			else
			{
				KCMNLNCMIMH = MyDetonator().KDNNLMHFKOJ;
			}
		}
	}

	public void __BB_OBFUSCATOR_33()
	{
		PCICJECIOMB = new GameObject("0");
		DMNCBGHHAKI = PCICJECIOMB.AddComponent<DetonatorBurstEmitter>();
		PCICJECIOMB.transform.parent = base.transform;
		PCICJECIOMB.transform.localRotation = Quaternion.identity;
		DMNCBGHHAKI.MFOLDHOAMNN = FMNGJEGCFIE;
		DMNCBGHHAKI.MJHAPHHGGHI = MyDetonator().MJHAPHHGGHI;
		DMNCBGHHAKI.NJGDFDGPNLN = MyDetonator().NJGDFDGPNLN;
	}

	public override void Init()
	{
		FillMaterials(false);
		BuildFireballA();
		BuildFireballB();
		BuildFireShadow();
	}

	public virtual void __BB_OBFUSCATOR_21()
	{
		if (!(IKCHMAJADEP > NCGMMIBMBEL) && GMAIEMJKMJD)
		{
			__BB_OBFUSCATOR_12();
			__BB_OBFUSCATOR_34();
			__BB_OBFUSCATOR_97();
			if (BCDHHFNKJCK)
			{
				CLNNBLEBPOO.Explode();
			}
			if (CHDKFLCJKDD)
			{
				DMNCBGHHAKI.Explode();
			}
			if (ACKFFOIFDII)
			{
				BGBDPJOIKIN.Explode();
			}
		}
	}

	public void __BB_OBFUSCATOR_7()
	{
		NOKNBPGJOEB = new GameObject("Your team survived");
		BGBDPJOIKIN = NOKNBPGJOEB.AddComponent<DetonatorBurstEmitter>();
		NOKNBPGJOEB.transform.parent = base.transform;
		NOKNBPGJOEB.transform.localRotation = Quaternion.identity;
		BGBDPJOIKIN.MFOLDHOAMNN = KCMNLNCMIMH;
		BGBDPJOIKIN.MJHAPHHGGHI = MyDetonator().MJHAPHHGGHI;
		BGBDPJOIKIN.NJGDFDGPNLN = MyDetonator().NJGDFDGPNLN;
	}

	public virtual void __BB_OBFUSCATOR_44()
	{
		__BB_OBFUSCATOR_41(false);
		BuildFireballA();
		__BB_OBFUSCATOR_26();
		__BB_OBFUSCATOR_7();
	}

	public virtual void __BB_OBFUSCATOR_81()
	{
		if (!(IKCHMAJADEP > NCGMMIBMBEL) && GMAIEMJKMJD)
		{
			__BB_OBFUSCATOR_50();
			__BB_OBFUSCATOR_60();
			__BB_OBFUSCATOR_0();
			if (BCDHHFNKJCK)
			{
				CLNNBLEBPOO.Explode();
			}
			if (CHDKFLCJKDD)
			{
				DMNCBGHHAKI.Explode();
			}
			if (ACKFFOIFDII)
			{
				BGBDPJOIKIN.Explode();
			}
		}
	}

	public virtual void __BB_OBFUSCATOR_8()
	{
		__BB_OBFUSCATOR_29(false);
		__BB_OBFUSCATOR_86();
		__BB_OBFUSCATOR_90();
		BuildFireShadow();
	}

	public void __BB_OBFUSCATOR_15(bool PHDOMKDEDMO)
	{
		if (!DHGANMBLNNK || PHDOMKDEDMO)
		{
			DHGANMBLNNK = MyDetonator().DHGANMBLNNK;
		}
		if (!FMNGJEGCFIE || PHDOMKDEDMO)
		{
			FMNGJEGCFIE = MyDetonator().FMNGJEGCFIE;
		}
		if (!KCMNLNCMIMH || PHDOMKDEDMO)
		{
			if ((double)Random.value > 1080.0)
			{
				KCMNLNCMIMH = MyDetonator().NLCJNPAMOEH;
			}
			else
			{
				KCMNLNCMIMH = MyDetonator().KDNNLMHFKOJ;
			}
		}
	}
}
