using System;
using System.Runtime.InteropServices;

namespace XInputDotNetPure
{
	public class NLIKGPCKJBM
	{
		public static GHMBOFCIIJJ __BB_OBFUSCATOR_0(LKIHIADKFOI PCDPELOLACP)
		{
			IntPtr intPtr = Marshal.AllocHGlobal(Marshal.SizeOf(typeof(GHMBOFCIIJJ.NPBEHBCKHEE)));
			uint num = GIFFOGDIKPJ.__BB_OBFUSCATOR_29((uint)PCDPELOLACP, intPtr);
			GHMBOFCIIJJ.NPBEHBCKHEE lIOGBCFJDAB = (GHMBOFCIIJJ.NPBEHBCKHEE)Marshal.PtrToStructure(intPtr, typeof(GHMBOFCIIJJ.NPBEHBCKHEE));
			return new GHMBOFCIIJJ(num == 1, lIOGBCFJDAB);
		}

		public static void __BB_OBFUSCATOR_8(LKIHIADKFOI PCDPELOLACP, float OBHBMAIFHBD, float EGNBGABPIHB)
		{
			GIFFOGDIKPJ.__BB_OBFUSCATOR_6((uint)PCDPELOLACP, OBHBMAIFHBD, EGNBGABPIHB);
		}

		public static void __BB_OBFUSCATOR_9(LKIHIADKFOI PCDPELOLACP, float OBHBMAIFHBD, float EGNBGABPIHB)
		{
			GIFFOGDIKPJ.__BB_OBFUSCATOR_35((uint)PCDPELOLACP, OBHBMAIFHBD, EGNBGABPIHB);
		}

		public static void __BB_OBFUSCATOR_13(LKIHIADKFOI PCDPELOLACP, float OBHBMAIFHBD, float EGNBGABPIHB)
		{
			GIFFOGDIKPJ.__BB_OBFUSCATOR_39((uint)PCDPELOLACP, OBHBMAIFHBD, EGNBGABPIHB);
		}

		public static GHMBOFCIIJJ __BB_OBFUSCATOR_1(LKIHIADKFOI PCDPELOLACP)
		{
			IntPtr intPtr = Marshal.AllocHGlobal(Marshal.SizeOf(typeof(GHMBOFCIIJJ.NPBEHBCKHEE)));
			uint num = GIFFOGDIKPJ.__BB_OBFUSCATOR_15((uint)PCDPELOLACP, intPtr);
			GHMBOFCIIJJ.NPBEHBCKHEE lIOGBCFJDAB = (GHMBOFCIIJJ.NPBEHBCKHEE)Marshal.PtrToStructure(intPtr, typeof(GHMBOFCIIJJ.NPBEHBCKHEE));
			return new GHMBOFCIIJJ(num == 0, lIOGBCFJDAB);
		}

		public static GHMBOFCIIJJ GetState(LKIHIADKFOI PCDPELOLACP)
		{
			IntPtr intPtr = Marshal.AllocHGlobal(Marshal.SizeOf(typeof(GHMBOFCIIJJ.NPBEHBCKHEE)));
			uint num = GIFFOGDIKPJ.XInputGamePadGetState((uint)PCDPELOLACP, intPtr);
			GHMBOFCIIJJ.NPBEHBCKHEE lIOGBCFJDAB = (GHMBOFCIIJJ.NPBEHBCKHEE)Marshal.PtrToStructure(intPtr, typeof(GHMBOFCIIJJ.NPBEHBCKHEE));
			return new GHMBOFCIIJJ(num == 0, lIOGBCFJDAB);
		}

		public static GHMBOFCIIJJ __BB_OBFUSCATOR_3(LKIHIADKFOI PCDPELOLACP)
		{
			IntPtr intPtr = Marshal.AllocHGlobal(Marshal.SizeOf(typeof(GHMBOFCIIJJ.NPBEHBCKHEE)));
			uint num = GIFFOGDIKPJ.__BB_OBFUSCATOR_29((uint)PCDPELOLACP, intPtr);
			GHMBOFCIIJJ.NPBEHBCKHEE lIOGBCFJDAB = (GHMBOFCIIJJ.NPBEHBCKHEE)Marshal.PtrToStructure(intPtr, typeof(GHMBOFCIIJJ.NPBEHBCKHEE));
			return new GHMBOFCIIJJ(num == 1, lIOGBCFJDAB);
		}

		public static void __BB_OBFUSCATOR_4(LKIHIADKFOI PCDPELOLACP, float OBHBMAIFHBD, float EGNBGABPIHB)
		{
			GIFFOGDIKPJ.__BB_OBFUSCATOR_35((uint)PCDPELOLACP, OBHBMAIFHBD, EGNBGABPIHB);
		}

		public static void SetVibration(LKIHIADKFOI PCDPELOLACP, float OBHBMAIFHBD, float EGNBGABPIHB)
		{
			GIFFOGDIKPJ.XInputGamePadSetState((uint)PCDPELOLACP, OBHBMAIFHBD, EGNBGABPIHB);
		}

		public static void __BB_OBFUSCATOR_5(LKIHIADKFOI PCDPELOLACP, float OBHBMAIFHBD, float EGNBGABPIHB)
		{
			GIFFOGDIKPJ.__BB_OBFUSCATOR_35((uint)PCDPELOLACP, OBHBMAIFHBD, EGNBGABPIHB);
		}

		public static GHMBOFCIIJJ __BB_OBFUSCATOR_7(LKIHIADKFOI PCDPELOLACP)
		{
			IntPtr intPtr = Marshal.AllocHGlobal(Marshal.SizeOf(typeof(GHMBOFCIIJJ.NPBEHBCKHEE)));
			uint num = GIFFOGDIKPJ.XInputGamePadGetState((uint)PCDPELOLACP, intPtr);
			GHMBOFCIIJJ.NPBEHBCKHEE lIOGBCFJDAB = (GHMBOFCIIJJ.NPBEHBCKHEE)Marshal.PtrToStructure(intPtr, typeof(GHMBOFCIIJJ.NPBEHBCKHEE));
			return new GHMBOFCIIJJ(num == 0, lIOGBCFJDAB);
		}

		public static GHMBOFCIIJJ __BB_OBFUSCATOR_12(LKIHIADKFOI PCDPELOLACP)
		{
			IntPtr intPtr = Marshal.AllocHGlobal(Marshal.SizeOf(typeof(GHMBOFCIIJJ.NPBEHBCKHEE)));
			uint num = GIFFOGDIKPJ.__BB_OBFUSCATOR_8((uint)PCDPELOLACP, intPtr);
			GHMBOFCIIJJ.NPBEHBCKHEE lIOGBCFJDAB = (GHMBOFCIIJJ.NPBEHBCKHEE)Marshal.PtrToStructure(intPtr, typeof(GHMBOFCIIJJ.NPBEHBCKHEE));
			return new GHMBOFCIIJJ(num == 1, lIOGBCFJDAB);
		}

		public static void __BB_OBFUSCATOR_10(LKIHIADKFOI PCDPELOLACP, float OBHBMAIFHBD, float EGNBGABPIHB)
		{
			GIFFOGDIKPJ.__BB_OBFUSCATOR_6((uint)PCDPELOLACP, OBHBMAIFHBD, EGNBGABPIHB);
		}
	}
}
